
import IShopPaintColor from "@models/shop/graphics/IShopPaintColor"

const shopPaintColor: IShopPaintColor[] = [
    { id: 1, type: 'paint_color', hex: '#FBCEB1', for_vehicle: '*', name: 'Абрикосовый', price: 1000, },
    { id: 2, type: 'paint_color', hex: '#B5B8B1', for_vehicle: '*', name: 'Агатовый серый', price: 1000, },
    { id: 3, type: 'paint_color', hex: '#7FFFD4', for_vehicle: '*', name: 'Аквамариновый', price: 1000, },
    { id: 4, type: 'paint_color', hex: '#E32636', for_vehicle: '*', name: 'Ализариновый красный', price: 1000, },
    { id: 5, type: 'paint_color', hex: '#AB274F', for_vehicle: '*', name: 'Амарантово-пурпурный', price: 1000, },
    { id: 6, type: 'paint_color', hex: '#9966CC', for_vehicle: '*', name: 'Аметистовый', price: 1000, },
    { id: 7, type: 'paint_color', hex: '#CD9575', for_vehicle: '*', name: 'Античная латунь', price: 1000, },
    { id: 8, type: 'paint_color', hex: '#464451', for_vehicle: '*', name: 'Антрацитовый', price: 1000, },
    { id: 9, type: 'paint_color', hex: '#44944A', for_vehicle: '*', name: 'Арлекин', price: 1000, },
    { id: 10, type: 'paint_color', hex: '#6A5ACD', for_vehicle: '*', name: 'Аспидно-синий', price: 1000, },
    { id: 11, type: 'paint_color', hex: '#003153', for_vehicle: '*', name: 'Берлинская лазурь', price: 1000, },
    { id: 12, type: 'paint_color', hex: '#A5260A', for_vehicle: '*', name: 'Бисмарк-фуриозо', price: 1000, },
    { id: 13, type: 'paint_color', hex: '#6495ED', for_vehicle: '*', name: 'Васильковый', price: 1000, },
    { id: 14, type: 'paint_color', hex: '#FFCF48', for_vehicle: '*', name: 'Восход солнца', price: 1000, },
    { id: 15, type: 'paint_color', hex: '#DCDCDC', for_vehicle: '*', name: 'Гейнсборо', price: 1000, },
    { id: 16, type: 'paint_color', hex: '#30BA8F', for_vehicle: '*', name: 'Горный луг', price: 1000, },
    { id: 17, type: 'paint_color', hex: '#F34723', for_vehicle: '*', name: 'Гранатовый', price: 1000, },
    { id: 18, type: 'paint_color', hex: '#1C1C1C', for_vehicle: '*', name: 'Графитно-черный', price: 1000, },
    { id: 19, type: 'paint_color', hex: '#474A51', for_vehicle: '*', name: 'Графитовый серый', price: 1000, },
    { id: 20, type: 'paint_color', hex: '#2F353B', for_vehicle: '*', name: 'Гранитный', price: 1000, },
    { id: 21, type: 'paint_color', hex: '#D1E231', for_vehicle: '*', name: 'Грушево-зеленый', price: 1000, },
    { id: 22, type: 'paint_color', hex: '#00693E', for_vehicle: '*', name: 'Дартмутский зеленый', price: 1000, },
    { id: 23, type: 'paint_color', hex: '#CA3767', for_vehicle: '*', name: 'Джазовый джем', price: 1000, },
    { id: 24, type: 'paint_color', hex: '#1560BD', for_vehicle: '*', name: 'Джинсовый синий', price: 1000, },
    { id: 25, type: 'paint_color', hex: '#009B77', for_vehicle: '*', name: 'Изумруд', price: 1000, },
    { id: 26, type: 'paint_color', hex: '#4B0082', for_vehicle: '*', name: 'Индиго', price: 1000, },
    { id: 27, type: 'paint_color', hex: '#4C5866', for_vehicle: '*', name: 'Маренго', price: 1000, },
    { id: 28, type: 'paint_color', hex: '#AD655F', for_vehicle: '*', name: 'Марсала', price: 1000, },
    { id: 29, type: 'paint_color', hex: '#B87333', for_vehicle: '*', name: 'Медный', price: 1000, },
    { id: 30, type: 'paint_color', hex: '#808000', for_vehicle: '*', name: 'Оливковый', price: 1000, },
    { id: 31, type: 'paint_color', hex: '#121910', for_vehicle: '*', name: 'Оливково-черный', price: 1000, },
    { id: 32, type: 'paint_color', hex: '#015D52', for_vehicle: '*', name: 'Опаловый зеленый', price: 1000, },
    { id: 33, type: 'paint_color', hex: '#FD5E53', for_vehicle: '*', name: 'Оранжевая заря', price: 1000, },
    { id: 34, type: 'paint_color', hex: '#A65E2E', for_vehicle: '*', name: 'Оранжево-коричневый', price: 1000, },
]

export default shopPaintColor