/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./bentayga.gltf --types --transform --shadows --keepnames --keepmeshes --keepmaterials 
Files: ./bentayga.gltf [246.62KB] > bentayga-transformed.glb [1.88MB] (-661%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
// api, models
import IDeclaredBodypartData from '@models/styling/IDeclaredBodypartData'
// mobx, store
import { observer } from 'mobx-react-lite'
import storeStyling from '@stores/storeStyling'

type GLTFResult = GLTF & {
  nodes: {
    door_front_right_1: THREE.Mesh
    door_front_right_2: THREE.Mesh
    door_front_right_3: THREE.Mesh
    door_front_right_4: THREE.Mesh
    door_front_right_5: THREE.Mesh
    door_front_right_6: THREE.Mesh
    door_front_right_7: THREE.Mesh
    door_front_right_8: THREE.Mesh
    door_front_right_9: THREE.Mesh
    door_front_right_10: THREE.Mesh
    door_front_left_1: THREE.Mesh
    door_front_left_2: THREE.Mesh
    door_front_left_3: THREE.Mesh
    door_front_left_4: THREE.Mesh
    door_front_left_5: THREE.Mesh
    door_front_left_6: THREE.Mesh
    door_front_left_7: THREE.Mesh
    door_front_left_8: THREE.Mesh
    door_front_left_9: THREE.Mesh
    door_front_left_10: THREE.Mesh
    door_front_left_11: THREE.Mesh
    door_front_left_12: THREE.Mesh
    door_front_left_13: THREE.Mesh
    door_front_left_14: THREE.Mesh
    door_front_left_15: THREE.Mesh
    door_rear_right_1: THREE.Mesh
    door_rear_right_2: THREE.Mesh
    door_rear_right_3: THREE.Mesh
    door_rear_right_4: THREE.Mesh
    door_rear_right_5: THREE.Mesh
    door_rear_right_6: THREE.Mesh
    door_rear_right_7: THREE.Mesh
    bodyshell_1: THREE.Mesh
    bodyshell_2: THREE.Mesh
    bodyshell_3: THREE.Mesh
    bodyshell_4: THREE.Mesh
    bodyshell_5: THREE.Mesh
    bodyshell_6: THREE.Mesh
    bodyshell_7: THREE.Mesh
    bodyshell_8: THREE.Mesh
    bodyshell_9: THREE.Mesh
    bodyshell_10: THREE.Mesh
    bodyshell_11: THREE.Mesh
    bodyshell_12: THREE.Mesh
    bodyshell_13: THREE.Mesh
    interior_1: THREE.Mesh
    interior_2: THREE.Mesh
    interior_3: THREE.Mesh
    interior_4: THREE.Mesh
    interior_5: THREE.Mesh
    interior_6: THREE.Mesh
    interior_7: THREE.Mesh
    interior_8: THREE.Mesh
    interior_9: THREE.Mesh
    interior_10: THREE.Mesh
    interior_11: THREE.Mesh
    interior_12: THREE.Mesh
    interior_13: THREE.Mesh
    interior_14: THREE.Mesh
    interior_15: THREE.Mesh
    interior_16: THREE.Mesh
    engine_1: THREE.Mesh
    engine_2: THREE.Mesh
    engine_3: THREE.Mesh
    engine_4: THREE.Mesh
    engine_5: THREE.Mesh
    engine_6: THREE.Mesh
    engine_7: THREE.Mesh
    engine_8: THREE.Mesh
    engine_9: THREE.Mesh
    engine_10: THREE.Mesh
    engine_11: THREE.Mesh
    bumper_front_1_1: THREE.Mesh
    bumper_front_1_2: THREE.Mesh
    bumper_front_1_3: THREE.Mesh
    bumper_front_1_4: THREE.Mesh
    bumper_front_1_5: THREE.Mesh
    bumper_front_1_6: THREE.Mesh
    bumper_front_1_7: THREE.Mesh
    bumper_front_1_8: THREE.Mesh
    bumper_front_1_9: THREE.Mesh
    bumper_front_1_10: THREE.Mesh
    bumper_front_1_11: THREE.Mesh
    bumper_rear_1_1: THREE.Mesh
    bumper_rear_1_2: THREE.Mesh
    bumper_rear_1_3: THREE.Mesh
    bumper_rear_1_4: THREE.Mesh
    bumper_rear_1_5: THREE.Mesh
    bumper_rear_1_6: THREE.Mesh
    bonnet_1_1: THREE.Mesh
    bonnet_1_2: THREE.Mesh
    bonnet_1_3: THREE.Mesh
    trunk_1: THREE.Mesh
    trunk_2: THREE.Mesh
    trunk_3: THREE.Mesh
    trunk_4: THREE.Mesh
    trunk_5: THREE.Mesh
    trunk_6: THREE.Mesh
    trunk_7: THREE.Mesh
    trunk_8: THREE.Mesh
    trunk_9: THREE.Mesh
    trunk_10: THREE.Mesh
    trunk_11: THREE.Mesh
    trunk_12: THREE.Mesh
    trunk_13: THREE.Mesh
    front_glass: THREE.Mesh
    door_rear_left_1: THREE.Mesh
    door_rear_left_2: THREE.Mesh
    door_rear_left_3: THREE.Mesh
    door_rear_left_4: THREE.Mesh
    door_rear_left_5: THREE.Mesh
    door_rear_left_6: THREE.Mesh
    door_rear_left_7: THREE.Mesh
    door_rear_left_8: THREE.Mesh
    door_rear_left_9: THREE.Mesh
    door_rear_left_10: THREE.Mesh
    door_rear_left_11: THREE.Mesh
    spoiler_1_1: THREE.Mesh
    spoiler_1_2: THREE.Mesh
    spoiler_1_3: THREE.Mesh
    spoiler_1_4: THREE.Mesh
    wings_front_1: THREE.Mesh
    top_glass: THREE.Mesh
    wheel_front_left_1: THREE.Mesh
    wheel_front_left_2: THREE.Mesh
    wheel_front_left_3: THREE.Mesh
    wheel_front_left_4: THREE.Mesh
    wheel_front_left_5: THREE.Mesh
    wheel_front_left_6: THREE.Mesh
    wheel_front_right_1: THREE.Mesh
    wheel_front_right_2: THREE.Mesh
    wheel_front_right_3: THREE.Mesh
    wheel_front_right_4: THREE.Mesh
    wheel_front_right_5: THREE.Mesh
    wheel_front_right_6: THREE.Mesh
    wheel_rear_left_1: THREE.Mesh
    wheel_rear_left_2: THREE.Mesh
    wheel_rear_left_3: THREE.Mesh
    wheel_rear_left_4: THREE.Mesh
    wheel_rear_left_5: THREE.Mesh
    wheel_rear_left_6: THREE.Mesh
    wheel_rear_right_1: THREE.Mesh
    wheel_rear_right_2: THREE.Mesh
    wheel_rear_right_3: THREE.Mesh
    wheel_rear_right_4: THREE.Mesh
    wheel_rear_right_5: THREE.Mesh
    wheel_rear_right_6: THREE.Mesh
    wings_front_2_1: THREE.Mesh
    wings_front_2_2: THREE.Mesh
    wings_rear_1_1: THREE.Mesh
    wings_rear_1_2: THREE.Mesh
    bumper_front_2_1: THREE.Mesh
    bumper_front_2_2: THREE.Mesh
    bumper_front_2_3: THREE.Mesh
    bumper_front_2_4: THREE.Mesh
    bumper_front_2_5: THREE.Mesh
    bumper_front_2_6: THREE.Mesh
    bumper_front_2_7: THREE.Mesh
    bumper_front_2_8: THREE.Mesh
    bumper_front_2_9: THREE.Mesh
    bumper_front_2_10: THREE.Mesh
    bumper_front_2_11: THREE.Mesh
    bumper_rear_2_1: THREE.Mesh
    bumper_rear_2_2: THREE.Mesh
    bumper_rear_2_3: THREE.Mesh
    bumper_rear_2_4: THREE.Mesh
    bumper_rear_2_5: THREE.Mesh
    bumper_rear_2_6: THREE.Mesh
    bonnet_2_1: THREE.Mesh
    bonnet_2_2: THREE.Mesh
    bonnet_2_3: THREE.Mesh
    bonnet_2_4: THREE.Mesh
    spoiler_2_1: THREE.Mesh
    spoiler_2_2: THREE.Mesh
    door_glass_front_right: THREE.Mesh
    door_glass_front_left: THREE.Mesh
    door_glass_rear_right: THREE.Mesh
    door_glass_rear_left: THREE.Mesh
  }
  materials: {
    glass: THREE.MeshStandardMaterial
    dark_plastic: THREE.MeshStandardMaterial
    primary: THREE.MeshPhysicalMaterial
    interior_panel_1: THREE.MeshStandardMaterial
    interior_skin_1: THREE.MeshStandardMaterial
    interior_secondary: THREE.MeshStandardMaterial
    interior_skin_2: THREE.MeshStandardMaterial
    side_mirror_turn_light: THREE.MeshStandardMaterial
    mirror: THREE.MeshStandardMaterial
    tertiary: THREE.MeshStandardMaterial
    dark_rubber: THREE.MeshStandardMaterial
    ['glass.011']: THREE.MeshStandardMaterial
    engine_admixture_color_6: THREE.MeshStandardMaterial
    ['door_rf.013']: THREE.MeshStandardMaterial
    bottom: THREE.MeshStandardMaterial
    tail_lights_1: THREE.MeshStandardMaterial
    tail_lights_turn: THREE.MeshStandardMaterial
    front_light_primary: THREE.MeshStandardMaterial
    tail_lights_brakelight: THREE.MeshStandardMaterial
    front_light_secondary: THREE.MeshStandardMaterial
    ['interior.001']: THREE.MeshStandardMaterial
    brand_logo_secondary: THREE.MeshStandardMaterial
    ['interior.003']: THREE.MeshStandardMaterial
    interior_skin_4: THREE.MeshStandardMaterial
    engine_metal: THREE.MeshStandardMaterial
    wheel_nopaint: THREE.MeshStandardMaterial
    brand_logo_primary: THREE.MeshStandardMaterial
    engine_admixture_color_1: THREE.MeshStandardMaterial
    engine_admixture_color_2: THREE.MeshStandardMaterial
    engine_admixture_color_3: THREE.MeshStandardMaterial
    engine_admixture_color_4: THREE.MeshStandardMaterial
    radiator_grille: THREE.MeshStandardMaterial
    numberplate_numbers: THREE.MeshStandardMaterial
    numberplate_face: THREE.MeshStandardMaterial
    diffuser: THREE.MeshStandardMaterial
    ['glass.014']: THREE.MeshStandardMaterial
    ['bumper_r0.001']: THREE.MeshStandardMaterial
    ['glass.015']: THREE.MeshStandardMaterial
    wheel_secondary: THREE.MeshStandardMaterial
    wheel_primary: THREE.MeshStandardMaterial
    wheel_brakes: THREE.MeshStandardMaterial
    wheel_tire: THREE.MeshStandardMaterial
    carbon: THREE.MeshStandardMaterial
    ['bumper_f1.001']: THREE.MeshPhysicalMaterial
    exhaust_inside: THREE.MeshStandardMaterial
  }
}

export const declaredBodypartsData: IDeclaredBodypartData[] = [
  { from_category: 'bumpers_front', id: 1, name: '[Stock]', price: 0 },
  { from_category: 'bumpers_front', id: 2, name: 'StormX', price: 7500 },
  { from_category: 'bumpers_rear', id: 1, name: '[Stock]', price: 0 },
  { from_category: 'bumpers_rear', id: 2, name: 'StormX', price: 7500 },
  { from_category: 'bonnets', id: 1, name: '[Stock]', price: 0 },
  { from_category: 'bonnets', id: 2, name: 'StormX', price: 7500 },
  { from_category: 'spoilers', id: 1, name: '[Stock]', price: 0 },
  { from_category: 'spoilers', id: 2, name: 'StormX', price: 7500 },
  { from_category: 'wings_front', id: 1, name: '[Stock]', price: 0 },
  { from_category: 'wings_front', id: 2, name: 'StormX', price: 7500 },
  { from_category: 'wings_rear', id: 1, name: '[Remove]', price: 0 },
  { from_category: 'wings_rear', id: 2, name: 'StormX', price: 7500 },
]

function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('assets/3d/transformed_gltf/cars/bentley/bentayga/bentayga-transformed.glb') as GLTFResult

  React.useEffect(() => {
    materials.primary.color = new THREE.Color('black')
    materials.primary.roughness = 0.8
    materials.primary.metalness = 0.8
    // materials.primary.clearcoat = 0.1
    // materials.primary.clearcoatRoughness = 0.1
    materials.primary.sheen = 0.6
    materials.primary.sheenColor = new THREE.Color('green')
    materials.primary.sheenRoughness = 0.15
  }, [])

  return (
    <group {...props} dispose={null}>
      <group name='door_front_right' position={[1.006, 0.211, -0.941]}>
        <mesh name='door_front_right_1' castShadow receiveShadow geometry={nodes.door_front_right_1.geometry} material={materials.glass} />
        <mesh name='door_front_right_2' castShadow receiveShadow geometry={nodes.door_front_right_2.geometry} material={materials.dark_plastic} />
        <mesh name='door_front_right_3' castShadow receiveShadow geometry={nodes.door_front_right_3.geometry} material={materials.primary} />
        <mesh name='door_front_right_4' castShadow receiveShadow geometry={nodes.door_front_right_4.geometry} material={materials.interior_panel_1} />
        <mesh name='door_front_right_5' castShadow receiveShadow geometry={nodes.door_front_right_5.geometry} material={materials.interior_skin_1} />
        <mesh name='door_front_right_6' castShadow receiveShadow geometry={nodes.door_front_right_6.geometry} material={materials.interior_secondary} />
        <mesh name='door_front_right_7' castShadow receiveShadow geometry={nodes.door_front_right_7.geometry} material={materials.interior_skin_2} />
        <mesh name='door_front_right_8' castShadow receiveShadow geometry={nodes.door_front_right_8.geometry} material={materials.interior_skin_1} />
        <mesh name='door_front_right_9' castShadow receiveShadow geometry={nodes.door_front_right_9.geometry} material={materials.side_mirror_turn_light} />
        <mesh name='door_front_right_10' castShadow receiveShadow geometry={nodes.door_front_right_10.geometry} material={materials.mirror} />
      </group>
      <group name='door_front_left' position={[-1.005, 0.211, -0.94]}>
        <mesh name='door_front_left_1' castShadow receiveShadow geometry={nodes.door_front_left_1.geometry} material={materials.glass} />
        <mesh name='door_front_left_2' castShadow receiveShadow geometry={nodes.door_front_left_2.geometry} material={materials.tertiary} />
        <mesh name='door_front_left_3' castShadow receiveShadow geometry={nodes.door_front_left_3.geometry} material={materials.dark_rubber} />
        <mesh name='door_front_left_4' castShadow receiveShadow geometry={nodes.door_front_left_4.geometry} material={materials.primary} />
        <mesh name='door_front_left_5' castShadow receiveShadow geometry={nodes.door_front_left_5.geometry} material={materials.interior_panel_1} />
        <mesh name='door_front_left_6' castShadow receiveShadow geometry={nodes.door_front_left_6.geometry} material={materials['glass.011']} />
        <mesh name='door_front_left_7' castShadow receiveShadow geometry={nodes.door_front_left_7.geometry} material={materials.engine_admixture_color_6} />
        <mesh name='door_front_left_8' castShadow receiveShadow geometry={nodes.door_front_left_8.geometry} material={materials.interior_skin_1} />
        <mesh name='door_front_left_9' castShadow receiveShadow geometry={nodes.door_front_left_9.geometry} material={materials.interior_secondary} />
        <mesh name='door_front_left_10' castShadow receiveShadow geometry={nodes.door_front_left_10.geometry} material={materials['door_rf.013']} />
        <mesh name='door_front_left_11' castShadow receiveShadow geometry={nodes.door_front_left_11.geometry} material={materials.interior_skin_2} />
        <mesh name='door_front_left_12' castShadow receiveShadow geometry={nodes.door_front_left_12.geometry} material={materials.interior_skin_1} />
        <mesh name='door_front_left_13' castShadow receiveShadow geometry={nodes.door_front_left_13.geometry} material={materials['glass.011']} />
        <mesh name='door_front_left_14' castShadow receiveShadow geometry={nodes.door_front_left_14.geometry} material={materials.interior_secondary} />
        <mesh name='door_front_left_15' castShadow receiveShadow geometry={nodes.door_front_left_15.geometry} material={materials.mirror} />
      </group>
      <group name='door_rear_right' position={[1.012, 0.151, 0.285]}>
        <mesh name='door_rear_right_1' castShadow receiveShadow geometry={nodes.door_rear_right_1.geometry} material={materials.dark_plastic} />
        <mesh name='door_rear_right_2' castShadow receiveShadow geometry={nodes.door_rear_right_2.geometry} material={materials.primary} />
        <mesh name='door_rear_right_3' castShadow receiveShadow geometry={nodes.door_rear_right_3.geometry} material={materials.interior_panel_1} />
        <mesh name='door_rear_right_4' castShadow receiveShadow geometry={nodes.door_rear_right_4.geometry} material={materials.interior_skin_1} />
        <mesh name='door_rear_right_5' castShadow receiveShadow geometry={nodes.door_rear_right_5.geometry} material={materials.interior_secondary} />
        <mesh name='door_rear_right_6' castShadow receiveShadow geometry={nodes.door_rear_right_6.geometry} material={materials.interior_skin_2} />
        <mesh name='door_rear_right_7' castShadow receiveShadow geometry={nodes.door_rear_right_7.geometry} material={materials.interior_skin_1} />
      </group>
      <group name='bodyshell' position={[0, 0.016, 0.068]}>
        <mesh name='bodyshell_1' castShadow receiveShadow geometry={nodes.bodyshell_1.geometry} material={materials.tertiary} />
        <mesh name='bodyshell_2' castShadow receiveShadow geometry={nodes.bodyshell_2.geometry} material={materials.dark_plastic} />
        <mesh name='bodyshell_3' castShadow receiveShadow geometry={nodes.bodyshell_3.geometry} material={materials.primary} />
        <mesh name='bodyshell_4' castShadow receiveShadow geometry={nodes.bodyshell_4.geometry} material={materials.interior_panel_1} />
        <mesh name='bodyshell_5' castShadow receiveShadow geometry={nodes.bodyshell_5.geometry} material={materials.bottom} />
        <mesh name='bodyshell_6' castShadow receiveShadow geometry={nodes.bodyshell_6.geometry} material={materials.tail_lights_1} />
        <mesh name='bodyshell_7' castShadow receiveShadow geometry={nodes.bodyshell_7.geometry} material={materials.tail_lights_turn} />
        <mesh name='bodyshell_8' castShadow receiveShadow geometry={nodes.bodyshell_8.geometry} material={materials.front_light_primary} />
        <mesh name='bodyshell_9' castShadow receiveShadow geometry={nodes.bodyshell_9.geometry} material={materials.interior_secondary} />
        <mesh name='bodyshell_10' castShadow receiveShadow geometry={nodes.bodyshell_10.geometry} material={materials.glass} />
        <mesh name='bodyshell_11' castShadow receiveShadow geometry={nodes.bodyshell_11.geometry} material={materials.tail_lights_brakelight} />
        <mesh name='bodyshell_12' castShadow receiveShadow geometry={nodes.bodyshell_12.geometry} material={materials.glass} />
        <mesh name='bodyshell_13' castShadow receiveShadow geometry={nodes.bodyshell_13.geometry} material={materials.front_light_secondary} />
      </group>
      <group name='bumper_front_1' position={[-0.001, -0.17, -2.502]} visible={storeStyling.demonstrativeBodyparts.bumper_front_id === 1}>
        <mesh name='bumper_front_1_1' castShadow receiveShadow geometry={nodes.bumper_front_1_1.geometry} material={materials.tertiary} />
        <mesh name='bumper_front_1_2' castShadow receiveShadow geometry={nodes.bumper_front_1_2.geometry} material={materials.dark_rubber} />
        <mesh name='bumper_front_1_3' castShadow receiveShadow geometry={nodes.bumper_front_1_3.geometry} material={materials.bottom} />
        <mesh name='bumper_front_1_4' castShadow receiveShadow geometry={nodes.bumper_front_1_4.geometry} material={materials.front_light_primary} />
        <mesh name='bumper_front_1_5' castShadow receiveShadow geometry={nodes.bumper_front_1_5.geometry} material={materials.brand_logo_primary} />
        <mesh name='bumper_front_1_6' castShadow receiveShadow geometry={nodes.bumper_front_1_6.geometry} material={materials.brand_logo_secondary} />
        <mesh name='bumper_front_1_7' castShadow receiveShadow geometry={nodes.bumper_front_1_7.geometry} material={materials.radiator_grille} />
        <mesh name='bumper_front_1_8' castShadow receiveShadow geometry={nodes.bumper_front_1_8.geometry} material={materials.wheel_nopaint} />
        <mesh name='bumper_front_1_9' castShadow receiveShadow geometry={nodes.bumper_front_1_9.geometry} material={materials.numberplate_numbers} />
        <mesh name='bumper_front_1_10' castShadow receiveShadow geometry={nodes.bumper_front_1_10.geometry} material={materials.numberplate_face} />
        <mesh name='bumper_front_1_11' castShadow receiveShadow geometry={nodes.bumper_front_1_11.geometry} material={materials.primary} />
      </group>
      <group name='bumper_rear_1' position={[-0.001, -0.209, 2.638]} visible={storeStyling.demonstrativeBodyparts.bumper_rear_id === 1}>
        <mesh name='bumper_rear_1_1' castShadow receiveShadow geometry={nodes.bumper_rear_1_1.geometry} material={materials.dark_rubber} />
        <mesh name='bumper_rear_1_2' castShadow receiveShadow geometry={nodes.bumper_rear_1_2.geometry} material={materials.diffuser} />
        <mesh name='bumper_rear_1_3' castShadow receiveShadow geometry={nodes.bumper_rear_1_3.geometry} material={materials.tail_lights_1} />
        <mesh name='bumper_rear_1_4' castShadow receiveShadow geometry={nodes.bumper_rear_1_4.geometry} material={materials['glass.014']} />
        <mesh name='bumper_rear_1_5' castShadow receiveShadow geometry={nodes.bumper_rear_1_5.geometry} material={materials.primary} />
        <mesh name='bumper_rear_1_6' castShadow receiveShadow geometry={nodes.bumper_rear_1_6.geometry} material={materials['bumper_r0.001']} />
      </group>
      <group name='bonnet_1' position={[0, 0.486, -1.129]} visible={storeStyling.demonstrativeBodyparts.bonnet_id === 1}>
        <mesh name='bonnet_1_1' castShadow receiveShadow geometry={nodes.bonnet_1_1.geometry} material={materials.bottom} />
        <mesh name='bonnet_1_2' castShadow receiveShadow geometry={nodes.bonnet_1_2.geometry} material={materials.dark_rubber} />
        <mesh name='bonnet_1_3' castShadow receiveShadow geometry={nodes.bonnet_1_3.geometry} material={materials.primary} />
      </group>
      <group name='trunk' position={[0, 0.97, 1.919]}>
        <mesh name='trunk_1' castShadow receiveShadow geometry={nodes.trunk_1.geometry} material={materials.tertiary} />
        <mesh name='trunk_2' castShadow receiveShadow geometry={nodes.trunk_2.geometry} material={materials.dark_rubber} />
        <mesh name='trunk_3' castShadow receiveShadow geometry={nodes.trunk_3.geometry} material={materials.primary} />
        <mesh name='trunk_4' castShadow receiveShadow geometry={nodes.trunk_4.geometry} material={materials.tail_lights_1} />
        <mesh name='trunk_5' castShadow receiveShadow geometry={nodes.trunk_5.geometry} material={materials.tail_lights_turn} />
        <mesh name='trunk_6' castShadow receiveShadow geometry={nodes.trunk_6.geometry} material={materials.front_light_primary} />
        <mesh name='trunk_7' castShadow receiveShadow geometry={nodes.trunk_7.geometry} material={materials.interior_skin_4} />
        <mesh name='trunk_8' castShadow receiveShadow geometry={nodes.trunk_8.geometry} material={materials.wheel_nopaint} />
        <mesh name='trunk_9' castShadow receiveShadow geometry={nodes.trunk_9.geometry} material={materials.numberplate_numbers} />
        <mesh name='trunk_10' castShadow receiveShadow geometry={nodes.trunk_10.geometry} material={materials.numberplate_face} />
        <mesh name='trunk_11' castShadow receiveShadow geometry={nodes.trunk_11.geometry} material={materials.glass} />
        <mesh name='trunk_12' castShadow receiveShadow geometry={nodes.trunk_12.geometry} material={materials.tail_lights_brakelight} />
        <mesh name='trunk_13' castShadow receiveShadow geometry={nodes.trunk_13.geometry} material={materials.side_mirror_turn_light} />
      </group>
      <mesh name='front_glass' castShadow receiveShadow geometry={nodes.front_glass.geometry} material={materials.glass} position={[0, 0.723, -0.78]} />
      <group name='door_rear_left' position={[-1.011, 0.151, 0.285]}>
        <mesh name='door_rear_left_1' castShadow receiveShadow geometry={nodes.door_rear_left_1.geometry} material={materials.tertiary} />
        <mesh name='door_rear_left_2' castShadow receiveShadow geometry={nodes.door_rear_left_2.geometry} material={materials.dark_rubber} />
        <mesh name='door_rear_left_3' castShadow receiveShadow geometry={nodes.door_rear_left_3.geometry} material={materials.primary} />
        <mesh name='door_rear_left_4' castShadow receiveShadow geometry={nodes.door_rear_left_4.geometry} material={materials.interior_panel_1} />
        <mesh name='door_rear_left_5' castShadow receiveShadow geometry={nodes.door_rear_left_5.geometry} material={materials.engine_admixture_color_6} />
        <mesh name='door_rear_left_6' castShadow receiveShadow geometry={nodes.door_rear_left_6.geometry} material={materials.interior_skin_1} />
        <mesh name='door_rear_left_7' castShadow receiveShadow geometry={nodes.door_rear_left_7.geometry} material={materials.interior_secondary} />
        <mesh name='door_rear_left_8' castShadow receiveShadow geometry={nodes.door_rear_left_8.geometry} material={materials['door_rf.013']} />
        <mesh name='door_rear_left_9' castShadow receiveShadow geometry={nodes.door_rear_left_9.geometry} material={materials.interior_skin_2} />
        <mesh name='door_rear_left_10' castShadow receiveShadow geometry={nodes.door_rear_left_10.geometry} material={materials['glass.015']} />
        <mesh name='door_rear_left_11' castShadow receiveShadow geometry={nodes.door_rear_left_11.geometry} material={materials.interior_skin_1} />
      </group>
      <group name='spoiler_1' position={[0, 0.97, 1.919]} visible={storeStyling.demonstrativeBodyparts.spoiler_id === 1}>
        <mesh name='spoiler_1_1' castShadow receiveShadow geometry={nodes.spoiler_1_1.geometry} material={materials.tertiary} />
        <mesh name='spoiler_1_2' castShadow receiveShadow geometry={nodes.spoiler_1_2.geometry} material={materials.brand_logo_primary} />
        <mesh name='spoiler_1_3' castShadow receiveShadow geometry={nodes.spoiler_1_3.geometry} material={materials.brand_logo_secondary} />
        <mesh name='spoiler_1_4' castShadow receiveShadow geometry={nodes.spoiler_1_4.geometry} material={materials.primary} />
      </group>
      <mesh
        name='wings_front_1'
        castShadow
        receiveShadow
        geometry={nodes.wings_front_1.geometry}
        material={materials.dark_plastic}
        position={[0, 0.15, -1.158]}
        visible={storeStyling.demonstrativeBodyparts.wings_front_id === 1}
      />
      <mesh name='top_glass' castShadow receiveShadow geometry={nodes.top_glass.geometry} material={materials.glass} position={[0, 0.016, 0.068]} />
      <group name='wheel_front_left' position={[0, 0.486, -1.129]}>
        <mesh name='wheel_front_left_1' castShadow receiveShadow geometry={nodes.wheel_front_left_1.geometry} material={materials.wheel_secondary} />
        <mesh name='wheel_front_left_2' castShadow receiveShadow geometry={nodes.wheel_front_left_2.geometry} material={materials.wheel_primary} />
        <mesh name='wheel_front_left_3' castShadow receiveShadow geometry={nodes.wheel_front_left_3.geometry} material={materials.wheel_nopaint} />
        <mesh name='wheel_front_left_4' castShadow receiveShadow geometry={nodes.wheel_front_left_4.geometry} material={materials.brand_logo_primary} />
        <mesh name='wheel_front_left_5' castShadow receiveShadow geometry={nodes.wheel_front_left_5.geometry} material={materials.wheel_brakes} />
        <mesh name='wheel_front_left_6' castShadow receiveShadow geometry={nodes.wheel_front_left_6.geometry} material={materials.wheel_tire} />
      </group>
      <group name='wheel_rear_left' position={[0, 0.486, 2.171]}>
        <mesh name='wheel_front_left_1' castShadow receiveShadow geometry={nodes.wheel_front_left_1.geometry} material={materials.wheel_secondary} />
        <mesh name='wheel_front_left_2' castShadow receiveShadow geometry={nodes.wheel_front_left_2.geometry} material={materials.wheel_primary} />
        <mesh name='wheel_front_left_3' castShadow receiveShadow geometry={nodes.wheel_front_left_3.geometry} material={materials.wheel_nopaint} />
        <mesh name='wheel_front_left_4' castShadow receiveShadow geometry={nodes.wheel_front_left_4.geometry} material={materials.brand_logo_primary} />
        <mesh name='wheel_front_left_5' castShadow receiveShadow geometry={nodes.wheel_front_left_5.geometry} material={materials.wheel_brakes} />
        <mesh name='wheel_front_left_6' castShadow receiveShadow geometry={nodes.wheel_front_left_6.geometry} material={materials.wheel_tire} />
      </group>
      <group name='wheel_front_right' position={[0, 0.486, -1.129]}>
        <mesh name='wheel_front_right_1' castShadow receiveShadow geometry={nodes.wheel_front_right_1.geometry} material={materials.wheel_secondary} />
        <mesh name='wheel_front_right_2' castShadow receiveShadow geometry={nodes.wheel_front_right_2.geometry} material={materials.wheel_primary} />
        <mesh name='wheel_front_right_3' castShadow receiveShadow geometry={nodes.wheel_front_right_3.geometry} material={materials.wheel_nopaint} />
        <mesh name='wheel_front_right_4' castShadow receiveShadow geometry={nodes.wheel_front_right_4.geometry} material={materials.brand_logo_primary} />
        <mesh name='wheel_front_right_5' castShadow receiveShadow geometry={nodes.wheel_front_right_5.geometry} material={materials.wheel_brakes} />
        <mesh name='wheel_front_right_6' castShadow receiveShadow geometry={nodes.wheel_front_right_6.geometry} material={materials.wheel_tire} />
      </group>
      <group name='wheel_rear_right' position={[0, 0.486, 2.171]}>
        <mesh name='wheel_front_right_1' castShadow receiveShadow geometry={nodes.wheel_front_right_1.geometry} material={materials.wheel_secondary} />
        <mesh name='wheel_front_right_2' castShadow receiveShadow geometry={nodes.wheel_front_right_2.geometry} material={materials.wheel_primary} />
        <mesh name='wheel_front_right_3' castShadow receiveShadow geometry={nodes.wheel_front_right_3.geometry} material={materials.wheel_nopaint} />
        <mesh name='wheel_front_right_4' castShadow receiveShadow geometry={nodes.wheel_front_right_4.geometry} material={materials.brand_logo_primary} />
        <mesh name='wheel_front_right_5' castShadow receiveShadow geometry={nodes.wheel_front_right_5.geometry} material={materials.wheel_brakes} />
        <mesh name='wheel_front_right_6' castShadow receiveShadow geometry={nodes.wheel_front_right_6.geometry} material={materials.wheel_tire} />
      </group>
      <group name='wings_front_2' position={[0, 0.15, -1.158]} visible={storeStyling.demonstrativeBodyparts.wings_front_id === 2}>
        <mesh name='wings_front_2_1' castShadow receiveShadow geometry={nodes.wings_front_2_1.geometry} material={materials.primary} />
        <mesh name='wings_front_2_2' castShadow receiveShadow geometry={nodes.wings_front_2_2.geometry} material={materials.carbon} />
      </group>
      <group name='wings_rear_1' position={[0, -0.11, 1.309]} visible={storeStyling.demonstrativeBodyparts.wings_rear_id === 2}>
        <mesh name='wings_rear_1_1' castShadow receiveShadow geometry={nodes.wings_rear_1_1.geometry} material={materials.primary} />
        <mesh name='wings_rear_1_2' castShadow receiveShadow geometry={nodes.wings_rear_1_2.geometry} material={materials.carbon} />
      </group>
      <group name='bumper_front_2' position={[-0.001, -0.17, -2.502]} visible={storeStyling.demonstrativeBodyparts.bumper_front_id === 2}>
        <mesh name='bumper_front_2_1' castShadow receiveShadow geometry={nodes.bumper_front_2_1.geometry} material={materials.tertiary} />
        <mesh name='bumper_front_2_2' castShadow receiveShadow geometry={nodes.bumper_front_2_2.geometry} material={materials.dark_rubber} />
        <mesh name='bumper_front_2_3' castShadow receiveShadow geometry={nodes.bumper_front_2_3.geometry} material={materials.bottom} />
        <mesh name='bumper_front_2_4' castShadow receiveShadow geometry={nodes.bumper_front_2_4.geometry} material={materials.front_light_primary} />
        <mesh name='bumper_front_2_5' castShadow receiveShadow geometry={nodes.bumper_front_2_5.geometry} material={materials.wheel_nopaint} />
        <mesh name='bumper_front_2_6' castShadow receiveShadow geometry={nodes.bumper_front_2_6.geometry} material={materials.numberplate_numbers} />
        <mesh name='bumper_front_2_7' castShadow receiveShadow geometry={nodes.bumper_front_2_7.geometry} material={materials.numberplate_face} />
        <mesh name='bumper_front_2_8' castShadow receiveShadow geometry={nodes.bumper_front_2_8.geometry} material={materials.carbon} />
        <mesh name='bumper_front_2_9' castShadow receiveShadow geometry={nodes.bumper_front_2_9.geometry} material={materials['bumper_f1.001']} />
        <mesh name='bumper_front_2_10' castShadow receiveShadow geometry={nodes.bumper_front_2_10.geometry} material={materials.primary} />
        <mesh name='bumper_front_2_11' castShadow receiveShadow geometry={nodes.bumper_front_2_11.geometry} material={materials.radiator_grille} />
      </group>
      <group name='bumper_rear_2' position={[-0.001, -0.209, 2.638]} visible={storeStyling.demonstrativeBodyparts.bumper_rear_id === 2}>
        <mesh name='bumper_rear_2_1' castShadow receiveShadow geometry={nodes.bumper_rear_2_1.geometry} material={materials.bottom} />
        <mesh name='bumper_rear_2_2' castShadow receiveShadow geometry={nodes.bumper_rear_2_2.geometry} material={materials['glass.014']} />
        <mesh name='bumper_rear_2_3' castShadow receiveShadow geometry={nodes.bumper_rear_2_3.geometry} material={materials.carbon} />
        <mesh name='bumper_rear_2_4' castShadow receiveShadow geometry={nodes.bumper_rear_2_4.geometry} material={materials.interior_panel_1} />
        <mesh name='bumper_rear_2_5' castShadow receiveShadow geometry={nodes.bumper_rear_2_5.geometry} material={materials.primary} />
        <mesh name='bumper_rear_2_6' castShadow receiveShadow geometry={nodes.bumper_rear_2_6.geometry} material={materials.exhaust_inside} />
      </group>
      <group name='bonnet_2' position={[0, 0.486, -1.129]} visible={storeStyling.demonstrativeBodyparts.bonnet_id === 2}>
        <mesh name='bonnet_2_1' castShadow receiveShadow geometry={nodes.bonnet_2_1.geometry} material={materials.tertiary} />
        <mesh name='bonnet_2_2' castShadow receiveShadow geometry={nodes.bonnet_2_2.geometry} material={materials.dark_rubber} />
        <mesh name='bonnet_2_3' castShadow receiveShadow geometry={nodes.bonnet_2_3.geometry} material={materials.radiator_grille} />
        <mesh name='bonnet_2_4' castShadow receiveShadow geometry={nodes.bonnet_2_4.geometry} material={materials.primary} />
      </group>
      <group name='spoiler_2' position={[0, 0.97, 1.919]} visible={storeStyling.demonstrativeBodyparts.spoiler_id === 2}>
        <mesh name='spoiler_2_1' castShadow receiveShadow geometry={nodes.spoiler_2_1.geometry} material={materials.carbon} />
        <mesh name='spoiler_2_2' castShadow receiveShadow geometry={nodes.spoiler_2_2.geometry} material={materials['bumper_f1.001']} />
      </group>
      <mesh
        name='door_glass_front_right'
        castShadow
        receiveShadow
        geometry={nodes.door_glass_front_right.geometry}
        material={materials.glass}
        position={[1.006, 0.211, -0.941]}
      />
      <mesh
        name='door_glass_front_left'
        castShadow
        receiveShadow
        geometry={nodes.door_glass_front_left.geometry}
        material={materials.glass}
        position={[-1.005, 0.211, -0.94]}
      />
      <mesh
        name='door_glass_rear_right'
        castShadow
        receiveShadow
        geometry={nodes.door_glass_rear_right.geometry}
        material={materials.glass}
        position={[1.012, 0.151, 0.285]}
      />
      <mesh
        name='door_glass_rear_left'
        castShadow
        receiveShadow
        geometry={nodes.door_glass_rear_left.geometry}
        material={materials.glass}
        position={[-1.011, 0.151, 0.285]}
      />
      <mesh name='interior_1' castShadow receiveShadow geometry={nodes.interior_1.geometry} material={materials.dark_plastic} />
      <mesh name='interior_2' castShadow receiveShadow geometry={nodes.interior_2.geometry} material={materials.interior_panel_1} />
      <mesh name='interior_3' castShadow receiveShadow geometry={nodes.interior_3.geometry} material={materials.bottom} />
      <mesh name='interior_4' castShadow receiveShadow geometry={nodes.interior_4.geometry} material={materials.engine_admixture_color_6} />
      <mesh name='interior_5' castShadow receiveShadow geometry={nodes.interior_5.geometry} material={materials['interior.001']} />
      <mesh name='interior_6' castShadow receiveShadow geometry={nodes.interior_6.geometry} material={materials.interior_secondary} />
      <mesh name='interior_7' castShadow receiveShadow geometry={nodes.interior_7.geometry} material={materials['door_rf.013']} />
      <mesh name='interior_8' castShadow receiveShadow geometry={nodes.interior_8.geometry} material={materials.interior_skin_2} />
      <mesh name='interior_9' castShadow receiveShadow geometry={nodes.interior_9.geometry} material={materials.brand_logo_secondary} />
      <mesh name='interior_10' castShadow receiveShadow geometry={nodes.interior_10.geometry} material={materials['interior.003']} />
      <mesh name='interior_11' castShadow receiveShadow geometry={nodes.interior_11.geometry} material={materials.bottom} />
      <mesh name='interior_12' castShadow receiveShadow geometry={nodes.interior_12.geometry} material={materials.interior_skin_4} />
      <mesh name='interior_13' castShadow receiveShadow geometry={nodes.interior_13.geometry} material={materials.interior_skin_1} />
      <mesh name='interior_14' castShadow receiveShadow geometry={nodes.interior_14.geometry} material={materials.tertiary} />
      <mesh name='interior_15' castShadow receiveShadow geometry={nodes.interior_15.geometry} material={materials.interior_skin_1} />
      <mesh name='interior_16' castShadow receiveShadow geometry={nodes.interior_16.geometry} material={materials.mirror} />
      <mesh name='engine_1' castShadow receiveShadow geometry={nodes.engine_1.geometry} material={materials.engine_metal} />
      <mesh name='engine_2' castShadow receiveShadow geometry={nodes.engine_2.geometry} material={materials.interior_panel_1} />
      <mesh name='engine_3' castShadow receiveShadow geometry={nodes.engine_3.geometry} material={materials.bottom} />
      <mesh name='engine_4' castShadow receiveShadow geometry={nodes.engine_4.geometry} material={materials.wheel_nopaint} />
      <mesh name='engine_5' castShadow receiveShadow geometry={nodes.engine_5.geometry} material={materials.brand_logo_primary} />
      <mesh name='engine_6' castShadow receiveShadow geometry={nodes.engine_6.geometry} material={materials.engine_admixture_color_1} />
      <mesh name='engine_7' castShadow receiveShadow geometry={nodes.engine_7.geometry} material={materials.engine_admixture_color_2} />
      <mesh name='engine_8' castShadow receiveShadow geometry={nodes.engine_8.geometry} material={materials.engine_admixture_color_3} />
      <mesh name='engine_9' castShadow receiveShadow geometry={nodes.engine_9.geometry} material={materials.engine_admixture_color_4} />
      <mesh name='engine_10' castShadow receiveShadow geometry={nodes.engine_10.geometry} material={materials['interior.003']} />
      <mesh name='engine_11' castShadow receiveShadow geometry={nodes.engine_11.geometry} material={materials.engine_admixture_color_6} />
    </group>
  )
}

useGLTF.preload('assets/3d/transformed_gltf/cars/bentley/bentayga/bentayga-transformed.glb')

export default observer(Model)
