/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./audi_a8.gltf --transform --types --shadows --keepnames --keepmaterials --keepmeshes 
Files: ./audi_a8.gltf [209.25KB] > audi_a8-transformed.glb [1.73MB] (-726%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { degToRad } from 'three/src/math/MathUtils'

type GLTFResult = GLTF & {
  nodes: {
    door_front_right_1: THREE.Mesh
    door_front_right_2: THREE.Mesh
    door_front_right_3: THREE.Mesh
    door_front_right_4: THREE.Mesh
    door_front_right_5: THREE.Mesh
    door_front_right_6: THREE.Mesh
    door_front_left_1: THREE.Mesh
    door_front_left_2: THREE.Mesh
    door_front_left_3: THREE.Mesh
    door_front_left_4: THREE.Mesh
    door_front_left_5: THREE.Mesh
    door_front_left_6: THREE.Mesh
    door_rear_left_1: THREE.Mesh
    door_rear_left_2: THREE.Mesh
    door_rear_left_3: THREE.Mesh
    door_rear_left_4: THREE.Mesh
    door_rear_left_5: THREE.Mesh
    door_rear_right_1: THREE.Mesh
    door_rear_right_2: THREE.Mesh
    door_rear_right_3: THREE.Mesh
    door_rear_right_4: THREE.Mesh
    door_rear_right_5: THREE.Mesh
    bodyshell_1: THREE.Mesh
    bodyshell_2: THREE.Mesh
    bodyshell_3: THREE.Mesh
    bodyshell_4: THREE.Mesh
    bodyshell_5: THREE.Mesh
    bodyshell_6: THREE.Mesh
    bodyshell_7: THREE.Mesh
    interior_1: THREE.Mesh
    interior_2: THREE.Mesh
    interior_3: THREE.Mesh
    interior_4: THREE.Mesh
    interior_5: THREE.Mesh
    interior_6: THREE.Mesh
    interior_7: THREE.Mesh
    interior_8: THREE.Mesh
    interior_9: THREE.Mesh
    shield_glass_rear: THREE.Mesh
    engine_1: THREE.Mesh
    engine_2: THREE.Mesh
    engine_3: THREE.Mesh
    engine_4: THREE.Mesh
    engine_5: THREE.Mesh
    streering_wheel_1: THREE.Mesh
    shield_glass_front: THREE.Mesh
    wheel_tire_front_right: THREE.Mesh
    wheel_brake_disk_front_right: THREE.Mesh
    wheel_disk_front_right_1: THREE.Mesh
    wheel_disk_front_right_2: THREE.Mesh
    bumper_front_2_1: THREE.Mesh
    bumper_front_2_2: THREE.Mesh
    bumper_front_2_3: THREE.Mesh
    bumper_front_2_4: THREE.Mesh
    bumper_front_2_5: THREE.Mesh
    bumper_front_2_6: THREE.Mesh
    bumper_front_2_7: THREE.Mesh
    bumper_front_2_8: THREE.Mesh
    trunk_2_1: THREE.Mesh
    trunk_2_2: THREE.Mesh
    trunk_2_3: THREE.Mesh
    trunk_2_4: THREE.Mesh
    trunk_2_5: THREE.Mesh
    trunk_2_6: THREE.Mesh
    trunk_2_7: THREE.Mesh
    trunk_2_8: THREE.Mesh
    trunk_2_9: THREE.Mesh
    trunk_2_10: THREE.Mesh
    bonnet_2: THREE.Mesh
    bumper_rear_2_1: THREE.Mesh
    bumper_rear_2_2: THREE.Mesh
    bumper_rear_2_3: THREE.Mesh
    bumper_rear_2_4: THREE.Mesh
    wings_front_2: THREE.Mesh
    head_lights_2_1: THREE.Mesh
    head_lights_2_2: THREE.Mesh
    head_lights_2_3: THREE.Mesh
    head_lights_2_4: THREE.Mesh
    head_lights_2_5: THREE.Mesh
    head_lights_2_6: THREE.Mesh
    head_lights_2_7: THREE.Mesh
    head_lights_2_8: THREE.Mesh
    head_lights_2_9: THREE.Mesh
    head_lights_2_10: THREE.Mesh
    tail_lights1: THREE.Mesh
    tail_lights1_1: THREE.Mesh
    tail_lights1_2: THREE.Mesh
    tail_lights1_3: THREE.Mesh
    tail_lights1_4: THREE.Mesh
    tail_lights1_5: THREE.Mesh
    tail_lights1_6: THREE.Mesh
    tail_lights1_7: THREE.Mesh
    exhaust_2_1: THREE.Mesh
    exhaust_2_2: THREE.Mesh
    bumper_front_1_1: THREE.Mesh
    bumper_front_1_2: THREE.Mesh
    bumper_front_1_3: THREE.Mesh
    bumper_front_1_4: THREE.Mesh
    bumper_front_1_5: THREE.Mesh
    bumper_front_1_6: THREE.Mesh
    bumper_front_1_7: THREE.Mesh
    bumper_front_1_8: THREE.Mesh
    trunk_1_1: THREE.Mesh
    trunk_1_2: THREE.Mesh
    trunk_1_3: THREE.Mesh
    trunk_1_4: THREE.Mesh
    trunk_1_5: THREE.Mesh
    trunk_1_6: THREE.Mesh
    trunk_1_7: THREE.Mesh
    trunk_1_8: THREE.Mesh
    trunk_1_9: THREE.Mesh
    trunk_1_10: THREE.Mesh
    trunk_1_11: THREE.Mesh
    bonnet_1: THREE.Mesh
    wings_front_1: THREE.Mesh
    bumper_rear_1_1: THREE.Mesh
    bumper_rear_1_2: THREE.Mesh
    bumper_rear_1_3: THREE.Mesh
    bumper_rear_1_4: THREE.Mesh
    bumper_rear_1_5: THREE.Mesh
    rear_lights_1_1: THREE.Mesh
    rear_lights_1_2: THREE.Mesh
    rear_lights_1_3: THREE.Mesh
    rear_lights_1_4: THREE.Mesh
    rear_lights_1_5: THREE.Mesh
    rear_lights_1_6: THREE.Mesh
    rear_lights_1_7: THREE.Mesh
    rear_lights_1_8: THREE.Mesh
    head_lights_1_1: THREE.Mesh
    head_lights_1_2: THREE.Mesh
    head_lights_1_3: THREE.Mesh
    head_lights_1_4: THREE.Mesh
    head_lights_1_5: THREE.Mesh
    head_lights_1_6: THREE.Mesh
    head_lights_1_7: THREE.Mesh
    head_lights_1_8: THREE.Mesh
    exhaust_1_1: THREE.Mesh
    exhaust_1_2: THREE.Mesh
    door_glass_front_right: THREE.Mesh
    door_glass_front_left: THREE.Mesh
    door_glass_rear_left: THREE.Mesh
    door_glass_rear_right: THREE.Mesh
    wheel_brake_body_front_right: THREE.Mesh
    wheel_brake_support_front_right: THREE.Mesh
    wheel_brake_support_nuts_front_right: THREE.Mesh
  }
  materials: {
    primary: THREE.MeshPhysicalMaterial
    ['door_rf.1']: THREE.MeshStandardMaterial
    secondary: THREE.MeshStandardMaterial
    front_light_turn: THREE.MeshStandardMaterial
    ['head_lights0.3']: THREE.MeshStandardMaterial
    ['bodyshell.5']: THREE.MeshStandardMaterial
    ['bodyshell.6']: THREE.MeshStandardMaterial
    wheel_1: THREE.MeshStandardMaterial
    ['secondary.001']: THREE.MeshStandardMaterial
    ['Interior.5']: THREE.MeshStandardMaterial
    ['secondary.002']: THREE.MeshStandardMaterial
    ['Interior.7']: THREE.MeshStandardMaterial
    ['secondary.003']: THREE.MeshStandardMaterial
    glass: THREE.MeshPhysicalMaterial
    light_far: THREE.MeshStandardMaterial
    ['engine.3']: THREE.MeshStandardMaterial
    ['engine.4']: THREE.MeshStandardMaterial
    wheeL_tire: THREE.MeshStandardMaterial
    BrakeDisk_Mat1: THREE.MeshStandardMaterial
    wheel_disk_primary: THREE.MeshStandardMaterial
    ['head_lights1.7']: THREE.MeshStandardMaterial
    ['bumper_f1.11']: THREE.MeshStandardMaterial
    ['door_rf.5']: THREE.MeshStandardMaterial
    rear_light_dimensions: THREE.MeshStandardMaterial
    plastic_glass: THREE.MeshPhysicalMaterial
    rear_light_stop: THREE.MeshStandardMaterial
    ['head_lights0.4']: THREE.MeshStandardMaterial
    ['glass.002']: THREE.MeshStandardMaterial
    rear_light_reverse: THREE.MeshStandardMaterial
    exhaust_primary: THREE.MeshStandardMaterial
    exhaust_secondary: THREE.MeshStandardMaterial
    radiator_primary: THREE.MeshStandardMaterial
    radiator_secondary: THREE.MeshStandardMaterial
    ['bumper_f0.7']: THREE.MeshStandardMaterial
    light_fog: THREE.MeshStandardMaterial
    rear_light_4: THREE.MeshStandardMaterial
    rear_bumper_plastic_panel_primary: THREE.MeshStandardMaterial
    rear_bumper_plastic_panel_secondary: THREE.MeshStandardMaterial
    rear_light_turn: THREE.MeshStandardMaterial
    BrakeDisk_Mat: THREE.MeshStandardMaterial
    BrakeDisk_Mat2: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('3d/gltf/cars/audi_a8/audi_a8-transformed.glb') as GLTFResult

  React.useEffect(() => {
    materials.primary.color = new THREE.Color('#801616')
    materials.primary.roughness = 0.3
    materials.primary.clearcoat = 0.35
    materials.primary.clearcoatRoughness = 0.8
  }, [])

  return (
    <group {...props} dispose={null} rotation={[degToRad(0), degToRad(180 + 45), degToRad(0)]} position={[0, 1.09, 0]}>
      <group name='door_front_right' position={[1.021, -0.217, -1.041]}>
        <mesh name='door_front_right_1' castShadow receiveShadow geometry={nodes.door_front_right_1.geometry} material={materials.primary} />
        <mesh name='door_front_right_2' castShadow receiveShadow geometry={nodes.door_front_right_2.geometry} material={materials['door_rf.1']} />
        <mesh name='door_front_right_3' castShadow receiveShadow geometry={nodes.door_front_right_3.geometry} material={materials['door_rf.1']} />
        <mesh name='door_front_right_4' castShadow receiveShadow geometry={nodes.door_front_right_4.geometry} material={materials['door_rf.1']} />
        <mesh name='door_front_right_5' castShadow receiveShadow geometry={nodes.door_front_right_5.geometry} material={materials.secondary} />
        <mesh name='door_front_right_6' castShadow receiveShadow geometry={nodes.door_front_right_6.geometry} material={materials.front_light_turn} />
      </group>
      <group name='door_front_left' position={[-1.008, -0.222, -1.037]}>
        <mesh name='door_front_left_1' castShadow receiveShadow geometry={nodes.door_front_left_1.geometry} material={materials.primary} />
        <mesh name='door_front_left_2' castShadow receiveShadow geometry={nodes.door_front_left_2.geometry} material={materials['door_rf.1']} />
        <mesh name='door_front_left_3' castShadow receiveShadow geometry={nodes.door_front_left_3.geometry} material={materials['door_rf.1']} />
        <mesh name='door_front_left_4' castShadow receiveShadow geometry={nodes.door_front_left_4.geometry} material={materials['door_rf.1']} />
        <mesh name='door_front_left_5' castShadow receiveShadow geometry={nodes.door_front_left_5.geometry} material={materials.secondary} />
        <mesh name='door_front_left_6' castShadow receiveShadow geometry={nodes.door_front_left_6.geometry} material={materials.front_light_turn} />
      </group>
      <group name='door_rear_left' position={[-1.025, -0.145, 0.205]}>
        <mesh name='door_rear_left_1' castShadow receiveShadow geometry={nodes.door_rear_left_1.geometry} material={materials.primary} />
        <mesh name='door_rear_left_2' castShadow receiveShadow geometry={nodes.door_rear_left_2.geometry} material={materials['door_rf.1']} />
        <mesh name='door_rear_left_3' castShadow receiveShadow geometry={nodes.door_rear_left_3.geometry} material={materials['door_rf.1']} />
        <mesh name='door_rear_left_4' castShadow receiveShadow geometry={nodes.door_rear_left_4.geometry} material={materials['door_rf.1']} />
        <mesh name='door_rear_left_5' castShadow receiveShadow geometry={nodes.door_rear_left_5.geometry} material={materials.secondary} />
      </group>
      <group name='door_rear_right' position={[1.026, -0.097, 0.209]}>
        <mesh name='door_rear_right_1' castShadow receiveShadow geometry={nodes.door_rear_right_1.geometry} material={materials.primary} />
        <mesh name='door_rear_right_2' castShadow receiveShadow geometry={nodes.door_rear_right_2.geometry} material={materials['door_rf.1']} />
        <mesh name='door_rear_right_3' castShadow receiveShadow geometry={nodes.door_rear_right_3.geometry} material={materials['door_rf.1']} />
        <mesh name='door_rear_right_4' castShadow receiveShadow geometry={nodes.door_rear_right_4.geometry} material={materials['door_rf.1']} />
        <mesh name='door_rear_right_5' castShadow receiveShadow geometry={nodes.door_rear_right_5.geometry} material={materials.secondary} />
      </group>
      <group name='bodyshell' rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name='bodyshell_1' castShadow receiveShadow geometry={nodes.bodyshell_1.geometry} material={materials.primary} />
        <mesh name='bodyshell_2' castShadow receiveShadow geometry={nodes.bodyshell_2.geometry} material={materials['door_rf.1']} />
        <mesh name='bodyshell_3' castShadow receiveShadow geometry={nodes.bodyshell_3.geometry} material={materials['door_rf.1']} />
        <mesh name='bodyshell_4' castShadow receiveShadow geometry={nodes.bodyshell_4.geometry} material={materials['door_rf.1']} />
        <mesh name='bodyshell_5' castShadow receiveShadow geometry={nodes.bodyshell_5.geometry} material={materials['head_lights0.3']} />
        <mesh name='bodyshell_6' castShadow receiveShadow geometry={nodes.bodyshell_6.geometry} material={materials['bodyshell.5']} />
        <mesh name='bodyshell_7' castShadow receiveShadow geometry={nodes.bodyshell_7.geometry} material={materials['bodyshell.6']} />
      </group>
      <mesh name='shield_glass_rear' castShadow receiveShadow geometry={nodes.shield_glass_rear.geometry} material={materials.glass} rotation={[-Math.PI / 2, 0, 0]} />
      <group name='engine' rotation={[Math.PI, 0, 0]} scale={-1}>
        <mesh name='engine_1' castShadow receiveShadow geometry={nodes.engine_1.geometry} material={materials.light_far} />
        <mesh name='engine_2' castShadow receiveShadow geometry={nodes.engine_2.geometry} material={materials['Interior.5']} />
        <mesh name='engine_3' castShadow receiveShadow geometry={nodes.engine_3.geometry} material={materials['door_rf.1']} />
        <mesh name='engine_4' castShadow receiveShadow geometry={nodes.engine_4.geometry} material={materials['engine.3']} />
        <mesh name='engine_5' castShadow receiveShadow geometry={nodes.engine_5.geometry} material={materials['engine.4']} />
      </group>
      <mesh name='streering_wheel_1' castShadow receiveShadow geometry={nodes.streering_wheel_1.geometry} material={materials.wheel_1} />
      <mesh name='shield_glass_front' castShadow receiveShadow geometry={nodes.shield_glass_front.geometry} material={materials.glass} position={[0, 0.356, -0.83]} />
      <mesh name='wheel_tire_front_right' castShadow receiveShadow geometry={nodes.wheel_tire_front_right.geometry} material={materials.wheeL_tire} position={[0.904, -0.499, -1.662]} scale={1.05} />
      <mesh name='wheel_brake_disk_front_right' castShadow receiveShadow geometry={nodes.wheel_brake_disk_front_right.geometry} material={materials.BrakeDisk_Mat1} position={[0.904, -0.499, -1.662]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.014} />
      <group name='wheel_disk_front_right' position={[0.904, -0.499, -1.662]} scale={1.05}>
        <mesh name='wheel_disk_front_right_1' castShadow receiveShadow geometry={nodes.wheel_disk_front_right_1.geometry} material={materials.wheel_1} />
        <mesh name='wheel_disk_front_right_2' castShadow receiveShadow geometry={nodes.wheel_disk_front_right_2.geometry} material={materials.wheel_disk_primary} />
      </group>
      <group name='bumper_front_2' position={[0.006, -0.389, -2.579]}>
        <mesh name='bumper_front_2_1' castShadow receiveShadow geometry={nodes.bumper_front_2_1.geometry} material={materials.primary} />
        <mesh name='bumper_front_2_2' castShadow receiveShadow geometry={nodes.bumper_front_2_2.geometry} material={materials['door_rf.1']} />
        <mesh name='bumper_front_2_3' castShadow receiveShadow geometry={nodes.bumper_front_2_3.geometry} material={materials['door_rf.1']} />
        <mesh name='bumper_front_2_4' castShadow receiveShadow geometry={nodes.bumper_front_2_4.geometry} material={materials.light_far} />
        <mesh name='bumper_front_2_5' castShadow receiveShadow geometry={nodes.bumper_front_2_5.geometry} material={materials['head_lights1.7']} />
        <mesh name='bumper_front_2_6' castShadow receiveShadow geometry={nodes.bumper_front_2_6.geometry} material={materials['door_rf.1']} />
        <mesh name='bumper_front_2_7' castShadow receiveShadow geometry={nodes.bumper_front_2_7.geometry} material={materials['door_rf.1']} />
        <mesh name='bumper_front_2_8' castShadow receiveShadow geometry={nodes.bumper_front_2_8.geometry} material={materials['bumper_f1.11']} />
      </group>
      <group name='trunk_2' position={[0, 0.325, 2.054]}>
        <mesh name='trunk_2_1' castShadow receiveShadow geometry={nodes.trunk_2_1.geometry} material={materials.primary} />
        <mesh name='trunk_2_2' castShadow receiveShadow geometry={nodes.trunk_2_2.geometry} material={materials['door_rf.1']} />
        <mesh name='trunk_2_3' castShadow receiveShadow geometry={nodes.trunk_2_3.geometry} material={materials['door_rf.1']} />
        <mesh name='trunk_2_4' castShadow receiveShadow geometry={nodes.trunk_2_4.geometry} material={materials['door_rf.5']} />
        <mesh name='trunk_2_5' castShadow receiveShadow geometry={nodes.trunk_2_5.geometry} material={materials['door_rf.5']} />
        <mesh name='trunk_2_6' castShadow receiveShadow geometry={nodes.trunk_2_6.geometry} material={materials['secondary.001']} />
        <mesh name='trunk_2_7' castShadow receiveShadow geometry={nodes.trunk_2_7.geometry} material={materials.rear_light_dimensions} />
        <mesh name='trunk_2_8' castShadow receiveShadow geometry={nodes.trunk_2_8.geometry} material={materials.rear_light_dimensions} />
        <mesh name='trunk_2_9' castShadow receiveShadow geometry={nodes.trunk_2_9.geometry} material={materials.plastic_glass} />
        <mesh name='trunk_2_10' castShadow receiveShadow geometry={nodes.trunk_2_10.geometry} material={materials.rear_light_stop} />
      </group>
      <mesh name='bonnet_2' castShadow receiveShadow geometry={nodes.bonnet_2.geometry} material={materials.primary} position={[0, 0.193, -1.074]} />
      <group name='bumper_rear_2' position={[0.001, -0.377, 2.67]}>
        <mesh name='bumper_rear_2_1' castShadow receiveShadow geometry={nodes.bumper_rear_2_1.geometry} material={materials.primary} />
        <mesh name='bumper_rear_2_2' castShadow receiveShadow geometry={nodes.bumper_rear_2_2.geometry} material={materials['door_rf.1']} />
        <mesh name='bumper_rear_2_3' castShadow receiveShadow geometry={nodes.bumper_rear_2_3.geometry} material={materials['Interior.5']} />
        <mesh name='bumper_rear_2_4' castShadow receiveShadow geometry={nodes.bumper_rear_2_4.geometry} material={materials['door_rf.1']} />
      </group>
      <mesh name='wings_front_2' castShadow receiveShadow geometry={nodes.wings_front_2.geometry} material={materials.primary} position={[0, -0.149, -1.6]} rotation={[-Math.PI / 2, 0, 0]} />
      <group name='head_lights_2' position={[0, -0.142, -2.413]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name='head_lights_2_1' castShadow receiveShadow geometry={nodes.head_lights_2_1.geometry} material={materials['door_rf.1']} />
        <mesh name='head_lights_2_2' castShadow receiveShadow geometry={nodes.head_lights_2_2.geometry} material={materials['door_rf.1']} />
        <mesh name='head_lights_2_3' castShadow receiveShadow geometry={nodes.head_lights_2_3.geometry} material={materials['head_lights0.4']} />
        <mesh name='head_lights_2_4' castShadow receiveShadow geometry={nodes.head_lights_2_4.geometry} material={materials.light_far} />
        <mesh name='head_lights_2_5' castShadow receiveShadow geometry={nodes.head_lights_2_5.geometry} material={materials.light_far} />
        <mesh name='head_lights_2_6' castShadow receiveShadow geometry={nodes.head_lights_2_6.geometry} material={materials['glass.002']} />
        <mesh name='head_lights_2_7' castShadow receiveShadow geometry={nodes.head_lights_2_7.geometry} material={materials.light_far} />
        <mesh name='head_lights_2_8' castShadow receiveShadow geometry={nodes.head_lights_2_8.geometry} material={materials.front_light_turn} />
        <mesh name='head_lights_2_9' castShadow receiveShadow geometry={nodes.head_lights_2_9.geometry} material={materials.front_light_turn} />
        <mesh name='head_lights_2_10' castShadow receiveShadow geometry={nodes.head_lights_2_10.geometry} material={materials.plastic_glass} />
      </group>
      <group name='rear_ights_2' position={[0, 0.058, 2.607]}>
        <mesh name='tail_lights1' castShadow receiveShadow geometry={nodes.tail_lights1.geometry} material={materials['door_rf.1']} />
        <mesh name='tail_lights1_1' castShadow receiveShadow geometry={nodes.tail_lights1_1.geometry} material={materials['door_rf.5']} />
        <mesh name='tail_lights1_2' castShadow receiveShadow geometry={nodes.tail_lights1_2.geometry} material={materials['door_rf.5']} />
        <mesh name='tail_lights1_3' castShadow receiveShadow geometry={nodes.tail_lights1_3.geometry} material={materials.rear_light_dimensions} />
        <mesh name='tail_lights1_4' castShadow receiveShadow geometry={nodes.tail_lights1_4.geometry} material={materials.rear_light_dimensions} />
        <mesh name='tail_lights1_5' castShadow receiveShadow geometry={nodes.tail_lights1_5.geometry} material={materials.plastic_glass} />
        <mesh name='tail_lights1_6' castShadow receiveShadow geometry={nodes.tail_lights1_6.geometry} material={materials.rear_light_stop} />
        <mesh name='tail_lights1_7' castShadow receiveShadow geometry={nodes.tail_lights1_7.geometry} material={materials.rear_light_reverse} />
      </group>
      <group name='exhaust_2' position={[0.001, -0.377, 2.67]}>
        <mesh name='exhaust_2_1' castShadow receiveShadow geometry={nodes.exhaust_2_1.geometry} material={materials.exhaust_primary} />
        <mesh name='exhaust_2_2' castShadow receiveShadow geometry={nodes.exhaust_2_2.geometry} material={materials.exhaust_secondary} />
      </group>
      <group name='bumper_front_1' position={[0, -0.349, -2.566]} rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh name='bumper_front_1_1' castShadow receiveShadow geometry={nodes.bumper_front_1_1.geometry} material={materials.primary} />
        <mesh name='bumper_front_1_2' castShadow receiveShadow geometry={nodes.bumper_front_1_2.geometry} material={materials.radiator_primary} />
        <mesh name='bumper_front_1_3' castShadow receiveShadow geometry={nodes.bumper_front_1_3.geometry} material={materials.radiator_secondary} />
        <mesh name='bumper_front_1_4' castShadow receiveShadow geometry={nodes.bumper_front_1_4.geometry} material={materials.wheel_1} />
        <mesh name='bumper_front_1_5' castShadow receiveShadow geometry={nodes.bumper_front_1_5.geometry} material={materials.plastic_glass} />
        <mesh name='bumper_front_1_6' castShadow receiveShadow geometry={nodes.bumper_front_1_6.geometry} material={materials['door_rf.1']} />
        <mesh name='bumper_front_1_7' castShadow receiveShadow geometry={nodes.bumper_front_1_7.geometry} material={materials['bumper_f0.7']} />
        <mesh name='bumper_front_1_8' castShadow receiveShadow geometry={nodes.bumper_front_1_8.geometry} material={materials.light_fog} />
      </group>
      <group name='trunk_1' position={[0, 0.325, 2.054]}>
        <mesh name='trunk_1_1' castShadow receiveShadow geometry={nodes.trunk_1_1.geometry} material={materials.primary} />
        <mesh name='trunk_1_2' castShadow receiveShadow geometry={nodes.trunk_1_2.geometry} material={materials['door_rf.1']} />
        <mesh name='trunk_1_3' castShadow receiveShadow geometry={nodes.trunk_1_3.geometry} material={materials['door_rf.5']} />
        <mesh name='trunk_1_4' castShadow receiveShadow geometry={nodes.trunk_1_4.geometry} material={materials['door_rf.5']} />
        <mesh name='trunk_1_5' castShadow receiveShadow geometry={nodes.trunk_1_5.geometry} material={materials['secondary.001']} />
        <mesh name='trunk_1_6' castShadow receiveShadow geometry={nodes.trunk_1_6.geometry} material={materials.rear_light_dimensions} />
        <mesh name='trunk_1_7' castShadow receiveShadow geometry={nodes.trunk_1_7.geometry} material={materials.plastic_glass} />
        <mesh name='trunk_1_8' castShadow receiveShadow geometry={nodes.trunk_1_8.geometry} material={materials.plastic_glass} />
        <mesh name='trunk_1_9' castShadow receiveShadow geometry={nodes.trunk_1_9.geometry} material={materials.rear_light_stop} />
        <mesh name='trunk_1_10' castShadow receiveShadow geometry={nodes.trunk_1_10.geometry} material={materials['secondary.001']} />
        <mesh name='trunk_1_11' castShadow receiveShadow geometry={nodes.trunk_1_11.geometry} material={materials.rear_light_4} />
      </group>
      <mesh name='bonnet_1' castShadow receiveShadow geometry={nodes.bonnet_1.geometry} material={materials.primary} position={[0, 0.193, -1.074]} />
      <mesh name='wings_front_1' castShadow receiveShadow geometry={nodes.wings_front_1.geometry} material={materials.primary} position={[0.005, -0.147, -1.666]} />
      <group name='bumper_rear_1' position={[0, -0.449, 2.711]}>
        <mesh name='bumper_rear_1_1' castShadow receiveShadow geometry={nodes.bumper_rear_1_1.geometry} material={materials.primary} />
        <mesh name='bumper_rear_1_2' castShadow receiveShadow geometry={nodes.bumper_rear_1_2.geometry} material={materials.exhaust_secondary} />
        <mesh name='bumper_rear_1_3' castShadow receiveShadow geometry={nodes.bumper_rear_1_3.geometry} material={materials['Interior.5']} />
        <mesh name='bumper_rear_1_4' castShadow receiveShadow geometry={nodes.bumper_rear_1_4.geometry} material={materials.rear_bumper_plastic_panel_primary} />
        <mesh name='bumper_rear_1_5' castShadow receiveShadow geometry={nodes.bumper_rear_1_5.geometry} material={materials.rear_bumper_plastic_panel_secondary} />
      </group>
      <group name='rear_lights_1' position={[0, 0.075, 2.583]}>
        <mesh name='rear_lights_1_1' castShadow receiveShadow geometry={nodes.rear_lights_1_1.geometry} material={materials['door_rf.1']} />
        <mesh name='rear_lights_1_2' castShadow receiveShadow geometry={nodes.rear_lights_1_2.geometry} material={materials['door_rf.5']} />
        <mesh name='rear_lights_1_3' castShadow receiveShadow geometry={nodes.rear_lights_1_3.geometry} material={materials['door_rf.5']} />
        <mesh name='rear_lights_1_4' castShadow receiveShadow geometry={nodes.rear_lights_1_4.geometry} material={materials.rear_light_dimensions} />
        <mesh name='rear_lights_1_5' castShadow receiveShadow geometry={nodes.rear_lights_1_5.geometry} material={materials.plastic_glass} />
        <mesh name='rear_lights_1_6' castShadow receiveShadow geometry={nodes.rear_lights_1_6.geometry} material={materials.rear_light_stop} />
        <mesh name='rear_lights_1_7' castShadow receiveShadow geometry={nodes.rear_lights_1_7.geometry} material={materials.rear_light_4} />
        <mesh name='rear_lights_1_8' castShadow receiveShadow geometry={nodes.rear_lights_1_8.geometry} material={materials.rear_light_turn} />
      </group>
      <group name='head_lights_1' position={[0, -0.127, -2.431]}>
        <mesh name='head_lights_1_1' castShadow receiveShadow geometry={nodes.head_lights_1_1.geometry} material={materials['door_rf.1']} />
        <mesh name='head_lights_1_2' castShadow receiveShadow geometry={nodes.head_lights_1_2.geometry} material={materials['door_rf.1']} />
        <mesh name='head_lights_1_3' castShadow receiveShadow geometry={nodes.head_lights_1_3.geometry} material={materials.light_far} />
        <mesh name='head_lights_1_4' castShadow receiveShadow geometry={nodes.head_lights_1_4.geometry} material={materials.front_light_turn} />
        <mesh name='head_lights_1_5' castShadow receiveShadow geometry={nodes.head_lights_1_5.geometry} material={materials.front_light_turn} />
        <mesh name='head_lights_1_6' castShadow receiveShadow geometry={nodes.head_lights_1_6.geometry} material={materials.plastic_glass} />
        <mesh name='head_lights_1_7' castShadow receiveShadow geometry={nodes.head_lights_1_7.geometry} material={materials.light_far} />
        <mesh name='head_lights_1_8' castShadow receiveShadow geometry={nodes.head_lights_1_8.geometry} material={materials['head_lights1.7']} />
      </group>
      <group name='exhaust_1' position={[0, -0.449, 2.711]}>
        <mesh name='exhaust_1_1' castShadow receiveShadow geometry={nodes.exhaust_1_1.geometry} material={materials.exhaust_secondary} />
        <mesh name='exhaust_1_2' castShadow receiveShadow geometry={nodes.exhaust_1_2.geometry} material={materials.exhaust_primary} />
      </group>
      <mesh name='door_glass_front_right' castShadow receiveShadow geometry={nodes.door_glass_front_right.geometry} material={materials.glass} position={[1.021, -0.217, -1.041]} />
      <mesh name='door_glass_front_left' castShadow receiveShadow geometry={nodes.door_glass_front_left.geometry} material={materials.glass} position={[-1.008, -0.222, -1.037]} />
      <mesh name='door_glass_rear_left' castShadow receiveShadow geometry={nodes.door_glass_rear_left.geometry} material={materials.glass} position={[-1.025, -0.145, 0.205]} />
      <mesh name='door_glass_rear_right' castShadow receiveShadow geometry={nodes.door_glass_rear_right.geometry} material={materials.glass} position={[1.026, -0.097, 0.209]} />
      <mesh name='wheel_brake_body_front_right' castShadow receiveShadow geometry={nodes.wheel_brake_body_front_right.geometry} material={materials.BrakeDisk_Mat} position={[0.904, -0.499, -1.662]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.014} />
      <mesh name='wheel_brake_support_front_right' castShadow receiveShadow geometry={nodes.wheel_brake_support_front_right.geometry} material={materials.BrakeDisk_Mat} position={[0.904, -0.499, -1.662]} rotation={[-Math.PI, 0, Math.PI]} scale={0.014} />
      <mesh name='wheel_brake_support_nuts_front_right' castShadow receiveShadow geometry={nodes.wheel_brake_support_nuts_front_right.geometry} material={materials.BrakeDisk_Mat2} position={[0.904, -0.499, -1.662]} rotation={[-Math.PI, 0, Math.PI]} scale={0.014} />
      <mesh name='interior_1' castShadow receiveShadow geometry={nodes.interior_1.geometry} material={materials['door_rf.1']} />
      <mesh name='interior_2' castShadow receiveShadow geometry={nodes.interior_2.geometry} material={materials['door_rf.1']} />
      <mesh name='interior_3' castShadow receiveShadow geometry={nodes.interior_3.geometry} material={materials.wheel_1} />
      <mesh name='interior_4' castShadow receiveShadow geometry={nodes.interior_4.geometry} material={materials.secondary} />
      <mesh name='interior_5' castShadow receiveShadow geometry={nodes.interior_5.geometry} material={materials['secondary.001']} />
      <mesh name='interior_6' castShadow receiveShadow geometry={nodes.interior_6.geometry} material={materials['Interior.5']} />
      <mesh name='interior_7' castShadow receiveShadow geometry={nodes.interior_7.geometry} material={materials['secondary.002']} />
      <mesh name='interior_8' castShadow receiveShadow geometry={nodes.interior_8.geometry} material={materials['Interior.7']} />
      <mesh name='interior_9' castShadow receiveShadow geometry={nodes.interior_9.geometry} material={materials['secondary.003']} />
    </group>
  )
}

// useGLTF.preload('3d/gltf/cars/audi_a8/audi_a8-transformed.glb')
