/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./audi_r8.gltf --types --transform --shadows --keepnames --keepmaterials --keepmeshes 
Files: ./audi_r8.gltf [190.04KB] > audi_r8-transformed.glb [1.66MB] (-775%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { degToRad } from 'three/src/math/MathUtils'

type GLTFResult = GLTF & {
  nodes: {
    wheel_1: THREE.Mesh
    wheel_2: THREE.Mesh
    wheel_3: THREE.Mesh
    wheel_4: THREE.Mesh
    wheel_5: THREE.Mesh
    wheel_6: THREE.Mesh
    bodyshell_1: THREE.Mesh
    bodyshell_2: THREE.Mesh
    bodyshell_3: THREE.Mesh
    bodyshell_4: THREE.Mesh
    bodyshell_5: THREE.Mesh
    bodyshell_6: THREE.Mesh
    bodyshell_7: THREE.Mesh
    bodyshell_8: THREE.Mesh
    bodyshell_9: THREE.Mesh
    bodyshell_10: THREE.Mesh
    bodyshell_11: THREE.Mesh
    engine_1: THREE.Mesh
    engine_2: THREE.Mesh
    engine_3: THREE.Mesh
    engine_4: THREE.Mesh
    engine_5: THREE.Mesh
    engine_6: THREE.Mesh
    engine_7: THREE.Mesh
    engine_8: THREE.Mesh
    interior_1: THREE.Mesh
    interior_2: THREE.Mesh
    interior_3: THREE.Mesh
    interior_4: THREE.Mesh
    interior_5: THREE.Mesh
    interior_6: THREE.Mesh
    interior_7: THREE.Mesh
    underbody: THREE.Mesh
    number_plate_rear_1_1: THREE.Mesh
    number_plate_rear_1_2: THREE.Mesh
    number_plate_rear_1_3: THREE.Mesh
    number_plate_rear_1_4: THREE.Mesh
    door_glass_alternate_1: THREE.Mesh
    bonnet_1_1: THREE.Mesh
    bonnet_1_2: THREE.Mesh
    trunk_1_1: THREE.Mesh
    trunk_1_2: THREE.Mesh
    trunk_1_3: THREE.Mesh
    bump_front_1_1: THREE.Mesh
    bump_front_1_2: THREE.Mesh
    bump_front_1_3: THREE.Mesh
    bump_front_1_4: THREE.Mesh
    bump_front_1_5: THREE.Mesh
    bump_rear_1_1: THREE.Mesh
    bump_rear_1_2: THREE.Mesh
    bump_rear_1_3: THREE.Mesh
    bump_rear_1_4: THREE.Mesh
    bump_rear_1_5: THREE.Mesh
    bump_rear_1_6: THREE.Mesh
    bump_rear_1_7: THREE.Mesh
    door_front_right_1: THREE.Mesh
    door_front_right_2: THREE.Mesh
    door_front_right_3: THREE.Mesh
    door_front_right_4: THREE.Mesh
    door_front_right_5: THREE.Mesh
    door_front_right_6: THREE.Mesh
    door_front_right_7: THREE.Mesh
    door_front_right_8: THREE.Mesh
    door_front_left_1: THREE.Mesh
    door_front_left_2: THREE.Mesh
    door_front_left_3: THREE.Mesh
    door_front_left_4: THREE.Mesh
    door_front_left_5: THREE.Mesh
    door_front_left_6: THREE.Mesh
    door_front_left_7: THREE.Mesh
    door_front_left_8: THREE.Mesh
    shield_glass_front_1: THREE.Mesh
    shield_glass_front_2: THREE.Mesh
    shield_glass_front_3: THREE.Mesh
    misc_1_1: THREE.Mesh
    misc_1_2: THREE.Mesh
    emblems_1001: THREE.Mesh
    emblems_1001_1: THREE.Mesh
    wings_rear_1: THREE.Mesh
    skirts_1: THREE.Mesh
    splitter_1: THREE.Mesh
    diffuser_1: THREE.Mesh
    spoiler0: THREE.Mesh
    spoiler0_1: THREE.Mesh
    spoiler0_2: THREE.Mesh
    spoiler0_3: THREE.Mesh
    exhaust_1_1: THREE.Mesh
    exhaust_1_2: THREE.Mesh
    light_glass_front_left_1: THREE.Mesh
    light_glass_rear_left_1: THREE.Mesh
    shield_glass_rear_alternate_1: THREE.Mesh
    light_glass_rear_right_1: THREE.Mesh
    light_front_left_1_1: THREE.Mesh
    light_front_left_1_2: THREE.Mesh
    light_front_left_1_3: THREE.Mesh
    light_front_left_1_4: THREE.Mesh
    light_front_right_1_1: THREE.Mesh
    light_front_right_1_2: THREE.Mesh
    light_front_right_1_3: THREE.Mesh
    light_front_right_1_4: THREE.Mesh
    light_rear_right_1_1: THREE.Mesh
    light_rear_right_1_2: THREE.Mesh
    light_rear_right_1_3: THREE.Mesh
    light_rear_right_1_4: THREE.Mesh
    light_rear_right_1_5: THREE.Mesh
    light_rear_right_1_6: THREE.Mesh
    light_rear_left_1_1: THREE.Mesh
    light_rear_left_1_2: THREE.Mesh
    light_rear_left_1_3: THREE.Mesh
    light_rear_left_1_4: THREE.Mesh
    light_rear_left_1_5: THREE.Mesh
    light_rear_left_1_6: THREE.Mesh
    light_glass_front_right_1: THREE.Mesh
    spoiler1: THREE.Mesh
    spoiler1_1: THREE.Mesh
    spoiler1_2: THREE.Mesh
    spoiler1_3: THREE.Mesh
    spoiler1_4: THREE.Mesh
    wings_rear_2: THREE.Mesh
    skirts_2: THREE.Mesh
    splitter_2: THREE.Mesh
    diffuser_2: THREE.Mesh
    door_glass_front_right: THREE.Mesh
    door_mirror_right_1: THREE.Mesh
    door_mirror_right_2: THREE.Mesh
    door_glass_front_left: THREE.Mesh
    door_mirror_left_1: THREE.Mesh
    door_mirror_left_2: THREE.Mesh
  }
  materials: {
    ['wheel.0']: THREE.MeshStandardMaterial
    ['wheel.1']: THREE.MeshStandardMaterial
    ['wheel.2']: THREE.MeshStandardMaterial
    ['wheel.3']: THREE.MeshStandardMaterial
    ['wheel.4']: THREE.MeshStandardMaterial
    ['wheel.7']: THREE.MeshStandardMaterial
    plastic_dark: THREE.MeshStandardMaterial
    primary: THREE.MeshPhysicalMaterial
    ['bodyshell.2']: THREE.MeshStandardMaterial
    carbon: THREE.MeshPhysicalMaterial
    ['bodyshell.4']: THREE.MeshStandardMaterial
    interior: THREE.MeshStandardMaterial
    ['bodyshell.6']: THREE.MeshStandardMaterial
    ['bodyshell.8']: THREE.MeshStandardMaterial
    ['spoiler_base2.0']: THREE.MeshStandardMaterial
    ['spoiler_base2.1']: THREE.MeshStandardMaterial
    ['engine.5']: THREE.MeshPhysicalMaterial
    ['engine.6']: THREE.MeshStandardMaterial
    ['engine.7']: THREE.MeshStandardMaterial
    ['Interior.6']: THREE.MeshStandardMaterial
    ['interior.001']: THREE.MeshStandardMaterial
    ['chassis_vlo.0']: THREE.MeshStandardMaterial
    ['rear_plate.1']: THREE.MeshStandardMaterial
    ['rear_plate.3']: THREE.MeshStandardMaterial
    glass: THREE.MeshPhysicalMaterial
    ['bump_front_ok.2']: THREE.MeshStandardMaterial
    ['bump_front_ok.3']: THREE.MeshStandardMaterial
    ['bump_front_ok.4']: THREE.MeshStandardMaterial
    plastic_dark_mate: THREE.MeshStandardMaterial
    ['bump_rear_ok.6']: THREE.MeshStandardMaterial
    ['lights.4']: THREE.MeshStandardMaterial
    plastic_glossy: THREE.MeshStandardMaterial
    ['misc1.3']: THREE.MeshStandardMaterial
    exhaust_primary: THREE.MeshStandardMaterial
    exhaust_secondary: THREE.MeshStandardMaterial
    plastic_glass: THREE.MeshPhysicalMaterial
    ['lights.2']: THREE.MeshStandardMaterial
    ['right front light']: THREE.MeshStandardMaterial
    ['lights.0']: THREE.MeshStandardMaterial
    ['right rear light']: THREE.MeshStandardMaterial
    ['lights.6']: THREE.MeshStandardMaterial
    ['shader_rear.0']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('3d/gltf/cars/audi_r8/audi_r8-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null} rotation={[degToRad(0), degToRad(180 + 45), degToRad(0)]} position={[0, 0.946, 0]}>
      <group name='wheel' position={[0.899, -0.364, -1.46]}>
        <mesh name='wheel_1' castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name='wheel_2' castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name='wheel_3' castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name='wheel_4' castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.3']} />
        <mesh name='wheel_5' castShadow receiveShadow geometry={nodes.wheel_5.geometry} material={materials['wheel.4']} />
        <mesh name='wheel_6' castShadow receiveShadow geometry={nodes.wheel_6.geometry} material={materials['wheel.7']} />
      </group>
      <mesh name='underbody' castShadow receiveShadow geometry={nodes.underbody.geometry} material={materials.plastic_dark} />
      <group name='number_plate_rear_1' position={[0, -0.059, 2.296]}>
        <mesh name='number_plate_rear_1_1' castShadow receiveShadow geometry={nodes.number_plate_rear_1_1.geometry} material={materials['chassis_vlo.0']} />
        <mesh name='number_plate_rear_1_2' castShadow receiveShadow geometry={nodes.number_plate_rear_1_2.geometry} material={materials['rear_plate.1']} />
        <mesh name='number_plate_rear_1_3' castShadow receiveShadow geometry={nodes.number_plate_rear_1_3.geometry} material={materials['spoiler_base2.0']} />
        <mesh name='number_plate_rear_1_4' castShadow receiveShadow geometry={nodes.number_plate_rear_1_4.geometry} material={materials['rear_plate.3']} />
      </group>
      <mesh name='door_glass_alternate_1' castShadow receiveShadow geometry={nodes.door_glass_alternate_1.geometry} material={materials.glass} />
      <group name='bonnet_1' position={[0, 0.051, -1.118]}>
        <mesh name='bonnet_1_1' castShadow receiveShadow geometry={nodes.bonnet_1_1.geometry} material={materials['wheel.3']} />
        <mesh name='bonnet_1_2' castShadow receiveShadow geometry={nodes.bonnet_1_2.geometry} material={materials.primary} />
      </group>
      <group name='trunk_1' position={[0, 0.563, 0.7]}>
        <mesh name='trunk_1_1' castShadow receiveShadow geometry={nodes.trunk_1_1.geometry} material={materials.plastic_dark} />
        <mesh name='trunk_1_2' castShadow receiveShadow geometry={nodes.trunk_1_2.geometry} material={materials.plastic_dark} />
        <mesh name='trunk_1_3' castShadow receiveShadow geometry={nodes.trunk_1_3.geometry} material={materials.glass} />
      </group>
      <group name='bump_front_1' position={[0.004, -0.306, -2.447]}>
        <mesh name='bump_front_1_1' castShadow receiveShadow geometry={nodes.bump_front_1_1.geometry} material={materials.plastic_dark} />
        <mesh name='bump_front_1_2' castShadow receiveShadow geometry={nodes.bump_front_1_2.geometry} material={materials.primary} />
        <mesh name='bump_front_1_3' castShadow receiveShadow geometry={nodes.bump_front_1_3.geometry} material={materials['bump_front_ok.2']} />
        <mesh name='bump_front_1_4' castShadow receiveShadow geometry={nodes.bump_front_1_4.geometry} material={materials['bump_front_ok.3']} />
        <mesh name='bump_front_1_5' castShadow receiveShadow geometry={nodes.bump_front_1_5.geometry} material={materials['bump_front_ok.4']} />
      </group>
      <group name='bump_rear_1' position={[0, -0.133, 2.238]}>
        <mesh name='bump_rear_1_1' castShadow receiveShadow geometry={nodes.bump_rear_1_1.geometry} material={materials.plastic_dark} />
        <mesh name='bump_rear_1_2' castShadow receiveShadow geometry={nodes.bump_rear_1_2.geometry} material={materials.primary} />
        <mesh name='bump_rear_1_3' castShadow receiveShadow geometry={nodes.bump_rear_1_3.geometry} material={materials.interior} />
        <mesh name='bump_rear_1_4' castShadow receiveShadow geometry={nodes.bump_rear_1_4.geometry} material={materials['bodyshell.8']} />
        <mesh name='bump_rear_1_5' castShadow receiveShadow geometry={nodes.bump_rear_1_5.geometry} material={materials.plastic_dark_mate} />
        <mesh name='bump_rear_1_6' castShadow receiveShadow geometry={nodes.bump_rear_1_6.geometry} material={materials['bump_front_ok.3']} />
        <mesh name='bump_rear_1_7' castShadow receiveShadow geometry={nodes.bump_rear_1_7.geometry} material={materials['bump_rear_ok.6']} />
      </group>
      <group name='door_front_right' position={[0.971, -0.193, -0.948]}>
        <mesh name='door_front_right_1' castShadow receiveShadow geometry={nodes.door_front_right_1.geometry} material={materials.plastic_dark} />
        <mesh name='door_front_right_2' castShadow receiveShadow geometry={nodes.door_front_right_2.geometry} material={materials.primary} />
        <mesh name='door_front_right_3' castShadow receiveShadow geometry={nodes.door_front_right_3.geometry} material={materials.carbon} />
        <mesh name='door_front_right_4' castShadow receiveShadow geometry={nodes.door_front_right_4.geometry} material={materials.interior} />
        <mesh name='door_front_right_5' castShadow receiveShadow geometry={nodes.door_front_right_5.geometry} material={materials.plastic_dark} />
        <mesh name='door_front_right_6' castShadow receiveShadow geometry={nodes.door_front_right_6.geometry} material={materials['engine.7']} />
        <mesh name='door_front_right_7' castShadow receiveShadow geometry={nodes.door_front_right_7.geometry} material={materials.plastic_dark} />
        <mesh name='door_front_right_8' castShadow receiveShadow geometry={nodes.door_front_right_8.geometry} material={materials['lights.4']} />
      </group>
      <group name='door_front_left' position={[-0.971, -0.193, -0.945]}>
        <mesh name='door_front_left_1' castShadow receiveShadow geometry={nodes.door_front_left_1.geometry} material={materials['wheel.3']} />
        <mesh name='door_front_left_2' castShadow receiveShadow geometry={nodes.door_front_left_2.geometry} material={materials.primary} />
        <mesh name='door_front_left_3' castShadow receiveShadow geometry={nodes.door_front_left_3.geometry} material={materials.carbon} />
        <mesh name='door_front_left_4' castShadow receiveShadow geometry={nodes.door_front_left_4.geometry} material={materials.interior} />
        <mesh name='door_front_left_5' castShadow receiveShadow geometry={nodes.door_front_left_5.geometry} material={materials.plastic_dark} />
        <mesh name='door_front_left_6' castShadow receiveShadow geometry={nodes.door_front_left_6.geometry} material={materials['engine.7']} />
        <mesh name='door_front_left_7' castShadow receiveShadow geometry={nodes.door_front_left_7.geometry} material={materials.plastic_dark} />
        <mesh name='door_front_left_8' castShadow receiveShadow geometry={nodes.door_front_left_8.geometry} material={materials['lights.4']} />
      </group>
      <group name='shield_glass_front' position={[0, 0.354, -1.005]}>
        <mesh name='shield_glass_front_1' castShadow receiveShadow geometry={nodes.shield_glass_front_1.geometry} material={materials.plastic_dark} />
        <mesh name='shield_glass_front_2' castShadow receiveShadow geometry={nodes.shield_glass_front_2.geometry} material={materials.plastic_dark} />
        <mesh name='shield_glass_front_3' castShadow receiveShadow geometry={nodes.shield_glass_front_3.geometry} material={materials.glass} />
      </group>
      <mesh name='wings_rear_1' castShadow receiveShadow geometry={nodes.wings_rear_1.geometry} material={materials.carbon} position={[0.198, 0.131, 0.706]} />
      <mesh name='skirts_1' castShadow receiveShadow geometry={nodes.skirts_1.geometry} material={materials.carbon} position={[0, -0.557, 0.171]} />
      <mesh name='splitter_1' castShadow receiveShadow geometry={nodes.splitter_1.geometry} material={materials.carbon} position={[0, -0.538, -2.312]} />
      <mesh name='diffuser_1' castShadow receiveShadow geometry={nodes.diffuser_1.geometry} material={materials.carbon} position={[0, -0.416, 2.188]} />
      <group name='spoiler_1' position={[0, 0.207, 2.165]}>
        <mesh name='spoiler0' castShadow receiveShadow geometry={nodes.spoiler0.geometry} material={materials['spoiler_base2.0']} />
        <mesh name='spoiler0_1' castShadow receiveShadow geometry={nodes.spoiler0_1.geometry} material={materials.primary} />
        <mesh name='spoiler0_2' castShadow receiveShadow geometry={nodes.spoiler0_2.geometry} material={materials['bodyshell.2']} />
        <mesh name='spoiler0_3' castShadow receiveShadow geometry={nodes.spoiler0_3.geometry} material={materials.plastic_dark} />
      </group>
      <group name='exhaust_1' position={[0, -0.417, 2.232]}>
        <mesh name='exhaust_1_1' castShadow receiveShadow geometry={nodes.exhaust_1_1.geometry} material={materials.exhaust_primary} />
        <mesh name='exhaust_1_2' castShadow receiveShadow geometry={nodes.exhaust_1_2.geometry} material={materials.exhaust_secondary} />
      </group>
      <mesh name='light_glass_front_left_1' castShadow receiveShadow geometry={nodes.light_glass_front_left_1.geometry} material={materials.plastic_glass} position={[-0.719, -0.115, -2.208]} />
      <mesh name='light_glass_rear_left_1' castShadow receiveShadow geometry={nodes.light_glass_rear_left_1.geometry} material={materials.plastic_glass} position={[-0.679, 0.06, 2.184]} />
      <mesh name='shield_glass_rear_alternate_1' castShadow receiveShadow geometry={nodes.shield_glass_rear_alternate_1.geometry} material={materials.glass} />
      <mesh name='light_glass_rear_right_1' castShadow receiveShadow geometry={nodes.light_glass_rear_right_1.geometry} material={materials.plastic_glass} position={[0.683, 0.059, 2.183]} />
      <group name='light_front_left_1' position={[-0.715, -0.126, -2.162]}>
        <mesh name='light_front_left_1_1' castShadow receiveShadow geometry={nodes.light_front_left_1_1.geometry} material={materials['lights.2']} />
        <mesh name='light_front_left_1_2' castShadow receiveShadow geometry={nodes.light_front_left_1_2.geometry} material={materials['lights.4']} />
        <mesh name='light_front_left_1_3' castShadow receiveShadow geometry={nodes.light_front_left_1_3.geometry} material={materials['right front light']} />
        <mesh name='light_front_left_1_4' castShadow receiveShadow geometry={nodes.light_front_left_1_4.geometry} material={materials['chassis_vlo.0']} />
      </group>
      <group name='light_front_right_1' position={[0.715, -0.126, -2.162]}>
        <mesh name='light_front_right_1_1' castShadow receiveShadow geometry={nodes.light_front_right_1_1.geometry} material={materials['lights.2']} />
        <mesh name='light_front_right_1_2' castShadow receiveShadow geometry={nodes.light_front_right_1_2.geometry} material={materials['lights.4']} />
        <mesh name='light_front_right_1_3' castShadow receiveShadow geometry={nodes.light_front_right_1_3.geometry} material={materials['right front light']} />
        <mesh name='light_front_right_1_4' castShadow receiveShadow geometry={nodes.light_front_right_1_4.geometry} material={materials['chassis_vlo.0']} />
      </group>
      <group name='light_rear_right_1' position={[0.718, 0.079, 2.126]}>
        <mesh name='light_rear_right_1_1' castShadow receiveShadow geometry={nodes.light_rear_right_1_1.geometry} material={materials['lights.0']} />
        <mesh name='light_rear_right_1_2' castShadow receiveShadow geometry={nodes.light_rear_right_1_2.geometry} material={materials['right rear light']} />
        <mesh name='light_rear_right_1_3' castShadow receiveShadow geometry={nodes.light_rear_right_1_3.geometry} material={materials.plastic_dark} />
        <mesh name='light_rear_right_1_4' castShadow receiveShadow geometry={nodes.light_rear_right_1_4.geometry} material={materials['lights.4']} />
        <mesh name='light_rear_right_1_5' castShadow receiveShadow geometry={nodes.light_rear_right_1_5.geometry} material={materials['lights.6']} />
        <mesh name='light_rear_right_1_6' castShadow receiveShadow geometry={nodes.light_rear_right_1_6.geometry} material={materials['shader_rear.0']} />
      </group>
      <group name='light_rear_left_1' position={[-0.718, 0.079, 2.126]}>
        <mesh name='light_rear_left_1_1' castShadow receiveShadow geometry={nodes.light_rear_left_1_1.geometry} material={materials['lights.0']} />
        <mesh name='light_rear_left_1_2' castShadow receiveShadow geometry={nodes.light_rear_left_1_2.geometry} material={materials['right rear light']} />
        <mesh name='light_rear_left_1_3' castShadow receiveShadow geometry={nodes.light_rear_left_1_3.geometry} material={materials.plastic_dark} />
        <mesh name='light_rear_left_1_4' castShadow receiveShadow geometry={nodes.light_rear_left_1_4.geometry} material={materials['lights.4']} />
        <mesh name='light_rear_left_1_5' castShadow receiveShadow geometry={nodes.light_rear_left_1_5.geometry} material={materials['lights.6']} />
        <mesh name='light_rear_left_1_6' castShadow receiveShadow geometry={nodes.light_rear_left_1_6.geometry} material={materials['shader_rear.0']} />
      </group>
      <mesh name='light_glass_front_right_1' castShadow receiveShadow geometry={nodes.light_glass_front_right_1.geometry} material={materials.plastic_glass} position={[0.719, -0.115, -2.208]} />
      <group name='spoiler_2' position={[0, 0.249, 2.139]}>
        <mesh name='spoiler1' castShadow receiveShadow geometry={nodes.spoiler1.geometry} material={materials['spoiler_base2.0']} />
        <mesh name='spoiler1_1' castShadow receiveShadow geometry={nodes.spoiler1_1.geometry} material={materials.primary} />
        <mesh name='spoiler1_2' castShadow receiveShadow geometry={nodes.spoiler1_2.geometry} material={materials['bodyshell.2']} />
        <mesh name='spoiler1_3' castShadow receiveShadow geometry={nodes.spoiler1_3.geometry} material={materials.carbon} />
        <mesh name='spoiler1_4' castShadow receiveShadow geometry={nodes.spoiler1_4.geometry} material={materials.plastic_dark} />
      </group>
      <mesh name='wings_rear_2' castShadow receiveShadow geometry={nodes.wings_rear_2.geometry} material={materials.plastic_dark} position={[0.198, 0.131, 0.706]} />
      <mesh name='skirts_2' castShadow receiveShadow geometry={nodes.skirts_2.geometry} material={materials.plastic_dark} position={[0, -0.557, 0.171]} />
      <mesh name='splitter_2' castShadow receiveShadow geometry={nodes.splitter_2.geometry} material={materials.plastic_dark} position={[0, -0.538, -2.312]} />
      <mesh name='diffuser_2' castShadow receiveShadow geometry={nodes.diffuser_2.geometry} material={materials.plastic_dark} position={[0, -0.416, 2.188]} />
      <mesh name='door_glass_front_right' castShadow receiveShadow geometry={nodes.door_glass_front_right.geometry} material={materials.glass} position={[0.971, -0.193, -0.948]} />
      <mesh name='door_mirror_right_1' castShadow receiveShadow geometry={nodes.door_mirror_right_1.geometry} material={materials.carbon} position={[1.02, 0.264, -0.725]} />
      <mesh name='door_mirror_right_2' castShadow receiveShadow geometry={nodes.door_mirror_right_2.geometry} material={materials.plastic_dark} position={[1.02, 0.264, -0.725]} />
      <mesh name='door_glass_front_left' castShadow receiveShadow geometry={nodes.door_glass_front_left.geometry} material={materials.glass} position={[-0.971, -0.193, -0.945]} />
      <mesh name='door_mirror_left_1' castShadow receiveShadow geometry={nodes.door_mirror_left_1.geometry} material={materials.plastic_dark} position={[-1.009, 0.264, -0.743]} />
      <mesh name='door_mirror_left_2' castShadow receiveShadow geometry={nodes.door_mirror_left_2.geometry} material={materials.carbon} position={[-1.009, 0.264, -0.743]} />
      <mesh name='bodyshell_1' castShadow receiveShadow geometry={nodes.bodyshell_1.geometry} material={materials.plastic_dark} />
      <mesh name='bodyshell_2' castShadow receiveShadow geometry={nodes.bodyshell_2.geometry} material={materials.primary} />
      <mesh name='bodyshell_3' castShadow receiveShadow geometry={nodes.bodyshell_3.geometry} material={materials['bodyshell.2']} />
      <mesh name='bodyshell_4' castShadow receiveShadow geometry={nodes.bodyshell_4.geometry} material={materials.carbon} />
      <mesh name='bodyshell_5' castShadow receiveShadow geometry={nodes.bodyshell_5.geometry} material={materials['bodyshell.4']} />
      <mesh name='bodyshell_6' castShadow receiveShadow geometry={nodes.bodyshell_6.geometry} material={materials.interior} />
      <mesh name='bodyshell_7' castShadow receiveShadow geometry={nodes.bodyshell_7.geometry} material={materials['bodyshell.6']} />
      <mesh name='bodyshell_8' castShadow receiveShadow geometry={nodes.bodyshell_8.geometry} material={materials.plastic_dark} />
      <mesh name='bodyshell_9' castShadow receiveShadow geometry={nodes.bodyshell_9.geometry} material={materials['bodyshell.8']} />
      <mesh name='bodyshell_10' castShadow receiveShadow geometry={nodes.bodyshell_10.geometry} material={materials['spoiler_base2.0']} />
      <mesh name='bodyshell_11' castShadow receiveShadow geometry={nodes.bodyshell_11.geometry} material={materials['spoiler_base2.1']} />
      <mesh name='engine_1' castShadow receiveShadow geometry={nodes.engine_1.geometry} material={materials.plastic_dark} />
      <mesh name='engine_2' castShadow receiveShadow geometry={nodes.engine_2.geometry} material={materials['bodyshell.2']} />
      <mesh name='engine_3' castShadow receiveShadow geometry={nodes.engine_3.geometry} material={materials.carbon} />
      <mesh name='engine_4' castShadow receiveShadow geometry={nodes.engine_4.geometry} material={materials.interior} />
      <mesh name='engine_5' castShadow receiveShadow geometry={nodes.engine_5.geometry} material={materials['bodyshell.6']} />
      <mesh name='engine_6' castShadow receiveShadow geometry={nodes.engine_6.geometry} material={materials['engine.5']} />
      <mesh name='engine_7' castShadow receiveShadow geometry={nodes.engine_7.geometry} material={materials['engine.6']} />
      <mesh name='engine_8' castShadow receiveShadow geometry={nodes.engine_8.geometry} material={materials['engine.7']} />
      <mesh name='interior_1' castShadow receiveShadow geometry={nodes.interior_1.geometry} material={materials['wheel.3']} />
      <mesh name='interior_2' castShadow receiveShadow geometry={nodes.interior_2.geometry} material={materials['bodyshell.2']} />
      <mesh name='interior_3' castShadow receiveShadow geometry={nodes.interior_3.geometry} material={materials.carbon} />
      <mesh name='interior_4' castShadow receiveShadow geometry={nodes.interior_4.geometry} material={materials.interior} />
      <mesh name='interior_5' castShadow receiveShadow geometry={nodes.interior_5.geometry} material={materials['bodyshell.6']} />
      <mesh name='interior_6' castShadow receiveShadow geometry={nodes.interior_6.geometry} material={materials['Interior.6']} />
      <mesh name='interior_7' castShadow receiveShadow geometry={nodes.interior_7.geometry} material={materials['interior.001']} />
      <mesh name='misc_1_1' castShadow receiveShadow geometry={nodes.misc_1_1.geometry} material={materials.plastic_dark} />
      <mesh name='misc_1_2' castShadow receiveShadow geometry={nodes.misc_1_2.geometry} material={materials['bodyshell.2']} />
      <mesh name='emblems_1001' castShadow receiveShadow geometry={nodes.emblems_1001.geometry} material={materials.plastic_glossy} />
      <mesh name='emblems_1001_1' castShadow receiveShadow geometry={nodes.emblems_1001_1.geometry} material={materials['misc1.3']} />
    </group>
  )
}

// useGLTF.preload('3d/gltf/cars/audi_r8/audi_r8-transformed.glb')
