/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./mitsubishi_evo_9.gltf --types --shadows --keepmaterials --keepmeshes --keepnames 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    wheel_1: THREE.Mesh
    wheel_2: THREE.Mesh
    wheel_3: THREE.Mesh
    wheel_4: THREE.Mesh
    door_front_left_1: THREE.Mesh
    door_front_left_2: THREE.Mesh
    door_front_left_3: THREE.Mesh
    door_front_left_4: THREE.Mesh
    door_front_left_5: THREE.Mesh
    door_front_left_6: THREE.Mesh
    door_front_left_7: THREE.Mesh
    door_front_left_8: THREE.Mesh
    door_front_left_9: THREE.Mesh
    door_front_right_1: THREE.Mesh
    door_front_right_2: THREE.Mesh
    door_front_right_3: THREE.Mesh
    door_front_right_4: THREE.Mesh
    door_front_right_5: THREE.Mesh
    door_front_right_6: THREE.Mesh
    door_front_right_7: THREE.Mesh
    door_front_right_8: THREE.Mesh
    door_front_right_9: THREE.Mesh
    door_rear_right_1: THREE.Mesh
    door_rear_right_2: THREE.Mesh
    door_rear_right_3: THREE.Mesh
    door_rear_right_4: THREE.Mesh
    door_rear_right_5: THREE.Mesh
    door_rear_right_6: THREE.Mesh
    door_rear_left_1: THREE.Mesh
    door_rear_left_2: THREE.Mesh
    door_rear_left_3: THREE.Mesh
    door_rear_left_4: THREE.Mesh
    door_rear_left_5: THREE.Mesh
    door_rear_left_6: THREE.Mesh
    interior_1: THREE.Mesh
    interior_2: THREE.Mesh
    interior_3: THREE.Mesh
    interior_4: THREE.Mesh
    interior_5: THREE.Mesh
    interior_6: THREE.Mesh
    interior_7: THREE.Mesh
    interior_8: THREE.Mesh
    interior_9: THREE.Mesh
    interior_10: THREE.Mesh
    interior_11: THREE.Mesh
    interior_12: THREE.Mesh
    interior_13: THREE.Mesh
    interior_14: THREE.Mesh
    interior_15: THREE.Mesh
    interior_16: THREE.Mesh
    interior_17: THREE.Mesh
    interior_18: THREE.Mesh
    interior_19: THREE.Mesh
    interior_20: THREE.Mesh
    interior_21: THREE.Mesh
    interior_22: THREE.Mesh
    interior_23: THREE.Mesh
    engine_with_suspension_1: THREE.Mesh
    engine_with_suspension_2: THREE.Mesh
    engine_with_suspension_3: THREE.Mesh
    engine_with_suspension_4: THREE.Mesh
    engine_with_suspension_5: THREE.Mesh
    engine_with_suspension_6: THREE.Mesh
    steeringwheel_1: THREE.Mesh
    steeringwheel_2: THREE.Mesh
    steeringwheel_3: THREE.Mesh
    bodyshell_1: THREE.Mesh
    bodyshell_2: THREE.Mesh
    bodyshell_3: THREE.Mesh
    bodyshell_4: THREE.Mesh
    bodyshell_5: THREE.Mesh
    bodyshell_6: THREE.Mesh
    bodyshell_7: THREE.Mesh
    bodyshell_8: THREE.Mesh
    bodyshell_9: THREE.Mesh
    exhaust_1_1: THREE.Mesh
    exhaust_1_2: THREE.Mesh
    trunk_1_1: THREE.Mesh
    trunk_1_2: THREE.Mesh
    trunk_1_3: THREE.Mesh
    trunk_1_4: THREE.Mesh
    trunk_1_5: THREE.Mesh
    glass_front: THREE.Mesh
    bonnet_1_1: THREE.Mesh
    bonnet_1_2: THREE.Mesh
    bonnet_1_3: THREE.Mesh
    bonnet_1_4: THREE.Mesh
    bonnet_2_1: THREE.Mesh
    bonnet_2_2: THREE.Mesh
    bonnet_2_3: THREE.Mesh
    bonnet_2_4: THREE.Mesh
    bonnet_2_5: THREE.Mesh
    bonnet_3_1: THREE.Mesh
    bonnet_3_2: THREE.Mesh
    bonnet_3_3: THREE.Mesh
    bumper_front_1_1: THREE.Mesh
    bumper_front_1_2: THREE.Mesh
    bumper_front_1_3: THREE.Mesh
    bumper_front_1_4: THREE.Mesh
    bumper_front_1_5: THREE.Mesh
    bumper_front_1_6: THREE.Mesh
    bumper_front_1_7: THREE.Mesh
    bumper_front_1_8: THREE.Mesh
    bumper_front_1_9: THREE.Mesh
    bumper_front_2_1: THREE.Mesh
    bumper_front_2_2: THREE.Mesh
    bumper_front_2_3: THREE.Mesh
    bumper_front_3_1: THREE.Mesh
    bumper_front_3_2: THREE.Mesh
    bumper_front_3_3: THREE.Mesh
    bumper_front_3_4: THREE.Mesh
    bumper_front_3_5: THREE.Mesh
    bumper_front_3_6: THREE.Mesh
    bumper_front_3_7: THREE.Mesh
    bumper_front_3_8: THREE.Mesh
    bumper_front_4_1: THREE.Mesh
    bumper_front_4_2: THREE.Mesh
    bumper_front_4_3: THREE.Mesh
    bumper_front_4_4: THREE.Mesh
    bumper_front_5_1: THREE.Mesh
    bumper_front_5_2: THREE.Mesh
    bumper_front_5_3: THREE.Mesh
    bumper_front_5_4: THREE.Mesh
    bumper_front_5_5: THREE.Mesh
    bumper_front_5_6: THREE.Mesh
    bumper_front_6_1: THREE.Mesh
    bumper_front_6_2: THREE.Mesh
    bumper_front_6_3: THREE.Mesh
    bumper_front_6_4: THREE.Mesh
    bumper_front_6_5: THREE.Mesh
    bumper_front_6_6: THREE.Mesh
    bumper_front_6_7: THREE.Mesh
    bumper_front_6_8: THREE.Mesh
    bumper_front_6_9: THREE.Mesh
    bumper_front_6_10: THREE.Mesh
    bumper_front_7_1: THREE.Mesh
    bumper_front_7_2: THREE.Mesh
    bumper_front_7_3: THREE.Mesh
    bumper_front_7_4: THREE.Mesh
    bumper_front_7_5: THREE.Mesh
    bumper_front_7_6: THREE.Mesh
    bumper_front_7_7: THREE.Mesh
    bumper_front_7_8: THREE.Mesh
    bumper_rear_1_1: THREE.Mesh
    bumper_rear_1_2: THREE.Mesh
    bumper_rear_2: THREE.Mesh
    bumper_rear_3_1: THREE.Mesh
    bumper_rear_3_2: THREE.Mesh
    bumper_rear_4_1: THREE.Mesh
    bumper_rear_4_2: THREE.Mesh
    bumper_rear_4_3: THREE.Mesh
    bumper_rear_5_1: THREE.Mesh
    bumper_rear_5_2: THREE.Mesh
    bumper_rear_5_3: THREE.Mesh
    bumper_rear_6_1: THREE.Mesh
    bumper_rear_6_2: THREE.Mesh
    bumper_rear_6_3: THREE.Mesh
    bumper_rear_7_1: THREE.Mesh
    bumper_rear_7_2: THREE.Mesh
    bumper_rear_7_3: THREE.Mesh
    skirts_1: THREE.Mesh
    skirts_2_1: THREE.Mesh
    skirts_2_2: THREE.Mesh
    skirts_3_1: THREE.Mesh
    skirts_3_2: THREE.Mesh
    skirts_3_3: THREE.Mesh
    skirts_4_1: THREE.Mesh
    skirts_4_2: THREE.Mesh
    spoiler_1_1: THREE.Mesh
    spoiler_1_2: THREE.Mesh
    spoiler_2: THREE.Mesh
    spoiler_3_1: THREE.Mesh
    spoiler_3_2: THREE.Mesh
    spoiler_4_1: THREE.Mesh
    spoiler_4_2: THREE.Mesh
    spoiler_4_3: THREE.Mesh
    spoiler_5_1: THREE.Mesh
    spoiler_5_2: THREE.Mesh
    wings_front_1_1: THREE.Mesh
    wings_front_1_2: THREE.Mesh
    wings_front_1_3: THREE.Mesh
    wings_front_1_4: THREE.Mesh
    wings_front_2_1: THREE.Mesh
    wings_front_2_2: THREE.Mesh
    wings_front_2_3: THREE.Mesh
    wings_rear_1: THREE.Mesh
    wings_rear_1_1: THREE.Mesh
    tail_lights_1_1: THREE.Mesh
    tail_lights_1_2: THREE.Mesh
    tail_lights_1_3: THREE.Mesh
    tail_lights_1_4: THREE.Mesh
    tail_lights_1_5: THREE.Mesh
    tail_lights_1_6: THREE.Mesh
    tail_lights_2_1: THREE.Mesh
    tail_lights_2_2: THREE.Mesh
    tail_lights_2_3: THREE.Mesh
    tail_lights_2_4: THREE.Mesh
    tail_lights_2_5: THREE.Mesh
    tail_lights_2_6: THREE.Mesh
    tail_lights_2_7: THREE.Mesh
    head_lights_1_1: THREE.Mesh
    head_lights_1_2: THREE.Mesh
    head_lights_1_3: THREE.Mesh
    head_lights_1_4: THREE.Mesh
    head_lights_glass: THREE.Mesh
    tail_lights_glass: THREE.Mesh
    dummy_bonnet: THREE.Mesh
    dummy_bumper_front: THREE.Mesh
    dummy_head_lights: THREE.Mesh
    dummy_wings_front: THREE.Mesh
    dummy_door_front_right: THREE.Mesh
    dummy_door_front_left: THREE.Mesh
    dummy_door_rear_left: THREE.Mesh
    dummy_door_rear_right: THREE.Mesh
    dummy_fenders_rear: THREE.Mesh
    dummy_trunk: THREE.Mesh
    dummy_tail_lights: THREE.Mesh
    dummy_bumper_rear: THREE.Mesh
    dummy_skirts: THREE.Mesh
    dummy_wheel_front_right: THREE.Mesh
    dummy_wheel_rear_right: THREE.Mesh
    dummy_wheel_rear_left: THREE.Mesh
    dummy_wheel_front_left: THREE.Mesh
  }
  materials: {
    ['wheel.0']: THREE.MeshStandardMaterial
    ['wheel.1']: THREE.MeshStandardMaterial
    ['wheel.2']: THREE.MeshStandardMaterial
    disk_primary: THREE.MeshStandardMaterial
    ['door_dside_f0.0']: THREE.MeshStandardMaterial
    ['door_dside_f0.1']: THREE.MeshStandardMaterial
    ['door_dside_f0.2']: THREE.MeshPhysicalMaterial
    ['door_dside_f0.3']: THREE.MeshStandardMaterial
    ['door_dside_f0.4']: THREE.MeshStandardMaterial
    ['door_dside_f0.5']: THREE.MeshStandardMaterial
    ['door_dside_f0.6']: THREE.MeshStandardMaterial
    primary: THREE.MeshStandardMaterial
    glass: THREE.MeshPhysicalMaterial
    ['chassis.1']: THREE.MeshStandardMaterial
    ['chassis.3']: THREE.MeshStandardMaterial
    ['chassis.6']: THREE.MeshStandardMaterial
    carbon: THREE.MeshStandardMaterial
    ['chassis.9']: THREE.MeshStandardMaterial
    ['chassis.11']: THREE.MeshStandardMaterial
    ['chassis.12']: THREE.MeshStandardMaterial
    ['chassis.13']: THREE.MeshStandardMaterial
    ['chassis.14']: THREE.MeshStandardMaterial
    ['chassis.15']: THREE.MeshStandardMaterial
    ['chassis.16']: THREE.MeshStandardMaterial
    ['chassis.17']: THREE.MeshStandardMaterial
    ['chassis.19']: THREE.MeshStandardMaterial
    ['chassis.22']: THREE.MeshStandardMaterial
    ['chassis.23']: THREE.MeshStandardMaterial
    ['block.2']: THREE.MeshStandardMaterial
    ['block.5']: THREE.MeshStandardMaterial
    plastic: THREE.MeshStandardMaterial
    ['bodyshell.4']: THREE.MeshStandardMaterial
    ['bodyshell.5']: THREE.MeshStandardMaterial
    ['primary.001']: THREE.MeshStandardMaterial
    exhaust: THREE.MeshStandardMaterial
    ['bonnet0.3']: THREE.MeshStandardMaterial
    ['right front light']: THREE.MeshStandardMaterial
    ['bumper_f0.6']: THREE.MeshStandardMaterial
    ['bumper_f0.7']: THREE.MeshStandardMaterial
    ['bumper_f0.8']: THREE.MeshStandardMaterial
    ['fenders_f0.2']: THREE.MeshStandardMaterial
    ['fenders_f0.3']: THREE.MeshStandardMaterial
    ['tail_lights0.0']: THREE.MeshStandardMaterial
    ['tail_lights0.1']: THREE.MeshStandardMaterial
    ['right rear light']: THREE.MeshStandardMaterial
    ['tail_lights0.5']: THREE.MeshStandardMaterial
    ['glass.005']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('3d/gltf/cars/MitsubishiEvo9/mitsubishi_evo_9.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} position={[0, .636, 0]}>

      {/* wheels */}
      <group name="wheel_front_right" position={[0.819, -0.07, -1.445]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials.disk_primary} />
      </group>
      <group name="wheel_front_left" position={[-0.819, -0.07, -1.445]} rotation={[0, Math.PI, 0]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials.disk_primary} />
      </group>
      <group name="wheel_rear_right" position={[0.819, -0.07, 1.4]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials.disk_primary} />
      </group>
      <group name="wheel_rear_left" position={[-0.819, -0.07, 1.4]} rotation={[0, Math.PI, 0]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials.disk_primary} />
      </group>

      <group name="door_front_left" position={[-0.937, 0.355, -0.955]}>
        <mesh name="door_front_left_1" castShadow receiveShadow geometry={nodes.door_front_left_1.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="door_front_left_2" castShadow receiveShadow geometry={nodes.door_front_left_2.geometry} material={materials['door_dside_f0.1']} />
        <mesh name="door_front_left_3" castShadow receiveShadow geometry={nodes.door_front_left_3.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="door_front_left_4" castShadow receiveShadow geometry={nodes.door_front_left_4.geometry} material={materials['door_dside_f0.3']} />
        <mesh name="door_front_left_5" castShadow receiveShadow geometry={nodes.door_front_left_5.geometry} material={materials['door_dside_f0.4']} />
        <mesh name="door_front_left_6" castShadow receiveShadow geometry={nodes.door_front_left_6.geometry} material={materials['door_dside_f0.5']} />
        <mesh name="door_front_left_7" castShadow receiveShadow geometry={nodes.door_front_left_7.geometry} material={materials['door_dside_f0.6']} />
        <mesh name="door_front_left_8" castShadow receiveShadow geometry={nodes.door_front_left_8.geometry} material={materials.primary} />
        <mesh name="door_front_left_9" castShadow receiveShadow geometry={nodes.door_front_left_9.geometry} material={materials.glass} />
      </group>
      <group name="door_front_right" position={[0.937, 0.355, -0.955]}>
        <mesh name="door_front_right_1" castShadow receiveShadow geometry={nodes.door_front_right_1.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="door_front_right_2" castShadow receiveShadow geometry={nodes.door_front_right_2.geometry} material={materials['door_dside_f0.1']} />
        <mesh name="door_front_right_3" castShadow receiveShadow geometry={nodes.door_front_right_3.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="door_front_right_4" castShadow receiveShadow geometry={nodes.door_front_right_4.geometry} material={materials['door_dside_f0.3']} />
        <mesh name="door_front_right_5" castShadow receiveShadow geometry={nodes.door_front_right_5.geometry} material={materials['door_dside_f0.4']} />
        <mesh name="door_front_right_6" castShadow receiveShadow geometry={nodes.door_front_right_6.geometry} material={materials['door_dside_f0.5']} />
        <mesh name="door_front_right_7" castShadow receiveShadow geometry={nodes.door_front_right_7.geometry} material={materials['door_dside_f0.6']} />
        <mesh name="door_front_right_8" castShadow receiveShadow geometry={nodes.door_front_right_8.geometry} material={materials.primary} />
        <mesh name="door_front_right_9" castShadow receiveShadow geometry={nodes.door_front_right_9.geometry} material={materials.glass} />
      </group>
      <group name="door_rear_right" position={[0.932, 0.345, 0.225]}>
        <mesh name="door_rear_right_1" castShadow receiveShadow geometry={nodes.door_rear_right_1.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="door_rear_right_2" castShadow receiveShadow geometry={nodes.door_rear_right_2.geometry} material={materials['door_dside_f0.1']} />
        <mesh name="door_rear_right_3" castShadow receiveShadow geometry={nodes.door_rear_right_3.geometry} material={materials['door_dside_f0.3']} />
        <mesh name="door_rear_right_4" castShadow receiveShadow geometry={nodes.door_rear_right_4.geometry} material={materials['door_dside_f0.4']} />
        <mesh name="door_rear_right_5" castShadow receiveShadow geometry={nodes.door_rear_right_5.geometry} material={materials.primary} />
        <mesh name="door_rear_right_6" castShadow receiveShadow geometry={nodes.door_rear_right_6.geometry} material={materials.glass} />
      </group>
      <group name="door_rear_left" position={[-0.933, 0.345, 0.225]}>
        <mesh name="door_rear_left_1" castShadow receiveShadow geometry={nodes.door_rear_left_1.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="door_rear_left_2" castShadow receiveShadow geometry={nodes.door_rear_left_2.geometry} material={materials['door_dside_f0.1']} />
        <mesh name="door_rear_left_3" castShadow receiveShadow geometry={nodes.door_rear_left_3.geometry} material={materials['door_dside_f0.3']} />
        <mesh name="door_rear_left_4" castShadow receiveShadow geometry={nodes.door_rear_left_4.geometry} material={materials['door_dside_f0.4']} />
        <mesh name="door_rear_left_5" castShadow receiveShadow geometry={nodes.door_rear_left_5.geometry} material={materials.primary} />
        <mesh name="door_rear_left_6" castShadow receiveShadow geometry={nodes.door_rear_left_6.geometry} material={materials.glass} />
      </group>
      <group name="trunk_1" position={[0, 0.715, 1.736]}>
        <mesh name="trunk_1_1" castShadow receiveShadow geometry={nodes.trunk_1_1.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="trunk_1_2" castShadow receiveShadow geometry={nodes.trunk_1_2.geometry} material={materials.plastic} />
        <mesh name="trunk_1_3" castShadow receiveShadow geometry={nodes.trunk_1_3.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="trunk_1_4" castShadow receiveShadow geometry={nodes.trunk_1_4.geometry} material={materials['block.5']} />
        <mesh name="trunk_1_5" castShadow receiveShadow geometry={nodes.trunk_1_5.geometry} material={materials.primary} />
      </group>
      <mesh name="glass_front" castShadow receiveShadow geometry={nodes.glass_front.geometry} material={materials.glass} position={[0, 0.85, -0.756]} />
      <group name="bonnet_1" position={[0, 0.578, -1.132]}>
        <mesh name="bonnet_1_1" castShadow receiveShadow geometry={nodes.bonnet_1_1.geometry} material={materials.primary} />
        <mesh name="bonnet_1_2" castShadow receiveShadow geometry={nodes.bonnet_1_2.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="bonnet_1_3" castShadow receiveShadow geometry={nodes.bonnet_1_3.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="bonnet_1_4" castShadow receiveShadow geometry={nodes.bonnet_1_4.geometry} material={materials['bonnet0.3']} />
      </group>
      <group name="bonnet_2" position={[0, -2.522, -1.132]}>
        <mesh name="bonnet_2_1" castShadow receiveShadow geometry={nodes.bonnet_2_1.geometry} material={materials.primary} />
        <mesh name="bonnet_2_2" castShadow receiveShadow geometry={nodes.bonnet_2_2.geometry} material={materials.plastic} />
        <mesh name="bonnet_2_3" castShadow receiveShadow geometry={nodes.bonnet_2_3.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="bonnet_2_4" castShadow receiveShadow geometry={nodes.bonnet_2_4.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="bonnet_2_5" castShadow receiveShadow geometry={nodes.bonnet_2_5.geometry} material={materials['bonnet0.3']} />
      </group>
      <group name="bonnet_3" position={[0, -1.422, -1.132]}>
        <mesh name="bonnet_3_1" castShadow receiveShadow geometry={nodes.bonnet_3_1.geometry} material={materials.plastic} />
        <mesh name="bonnet_3_2" castShadow receiveShadow geometry={nodes.bonnet_3_2.geometry} material={materials.primary} />
        <mesh name="bonnet_3_3" castShadow receiveShadow geometry={nodes.bonnet_3_3.geometry} material={materials['bonnet0.3']} />
      </group>
      <group name="bumper_front_1" position={[0, 0.14, -2.42]}>
        <mesh name="bumper_front_1_1" castShadow receiveShadow geometry={nodes.bumper_front_1_1.geometry} material={materials['chassis.1']} />
        <mesh name="bumper_front_1_2" castShadow receiveShadow geometry={nodes.bumper_front_1_2.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="bumper_front_1_3" castShadow receiveShadow geometry={nodes.bumper_front_1_3.geometry} material={materials['bonnet0.3']} />
        <mesh name="bumper_front_1_4" castShadow receiveShadow geometry={nodes.bumper_front_1_4.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="bumper_front_1_5" castShadow receiveShadow geometry={nodes.bumper_front_1_5.geometry} material={materials.primary} />
        <mesh name="bumper_front_1_6" castShadow receiveShadow geometry={nodes.bumper_front_1_6.geometry} material={materials['right front light']} />
        <mesh name="bumper_front_1_7" castShadow receiveShadow geometry={nodes.bumper_front_1_7.geometry} material={materials['bumper_f0.6']} />
        <mesh name="bumper_front_1_8" castShadow receiveShadow geometry={nodes.bumper_front_1_8.geometry} material={materials['bumper_f0.7']} />
        <mesh name="bumper_front_1_9" castShadow receiveShadow geometry={nodes.bumper_front_1_9.geometry} material={materials['bumper_f0.8']} />
      </group>
      <group name="bumper_front_2" position={[0, -5.86, -2.42]}>
        <mesh name="bumper_front_2_1" castShadow receiveShadow geometry={nodes.bumper_front_2_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_2_2" castShadow receiveShadow geometry={nodes.bumper_front_2_2.geometry} material={materials['bonnet0.3']} />
        <mesh name="bumper_front_2_3" castShadow receiveShadow geometry={nodes.bumper_front_2_3.geometry} material={materials['door_dside_f0.2']} />
      </group>
      <group name="bumper_front_3" position={[0, -6.86, -2.42]}>
        <mesh name="bumper_front_3_1" castShadow receiveShadow geometry={nodes.bumper_front_3_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_3_2" castShadow receiveShadow geometry={nodes.bumper_front_3_2.geometry} material={materials['bonnet0.3']} />
        <mesh name="bumper_front_3_3" castShadow receiveShadow geometry={nodes.bumper_front_3_3.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="bumper_front_3_4" castShadow receiveShadow geometry={nodes.bumper_front_3_4.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="bumper_front_3_5" castShadow receiveShadow geometry={nodes.bumper_front_3_5.geometry} material={materials['right front light']} />
        <mesh name="bumper_front_3_6" castShadow receiveShadow geometry={nodes.bumper_front_3_6.geometry} material={materials['bumper_f0.6']} />
        <mesh name="bumper_front_3_7" castShadow receiveShadow geometry={nodes.bumper_front_3_7.geometry} material={materials['bumper_f0.7']} />
        <mesh name="bumper_front_3_8" castShadow receiveShadow geometry={nodes.bumper_front_3_8.geometry} material={materials['bumper_f0.8']} />
      </group>
      <group name="bumper_front_4" position={[0, -7.86, -2.42]}>
        <mesh name="bumper_front_4_1" castShadow receiveShadow geometry={nodes.bumper_front_4_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_4_2" castShadow receiveShadow geometry={nodes.bumper_front_4_2.geometry} material={materials.carbon} />
        <mesh name="bumper_front_4_3" castShadow receiveShadow geometry={nodes.bumper_front_4_3.geometry} material={materials['bonnet0.3']} />
        <mesh name="bumper_front_4_4" castShadow receiveShadow geometry={nodes.bumper_front_4_4.geometry} material={materials['door_dside_f0.2']} />
      </group>
      <group name="bumper_front_5" position={[0, -8.86, -2.42]}>
        <mesh name="bumper_front_5_1" castShadow receiveShadow geometry={nodes.bumper_front_5_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_5_2" castShadow receiveShadow geometry={nodes.bumper_front_5_2.geometry} material={materials['bonnet0.3']} />
        <mesh name="bumper_front_5_3" castShadow receiveShadow geometry={nodes.bumper_front_5_3.geometry} material={materials['right front light']} />
        <mesh name="bumper_front_5_4" castShadow receiveShadow geometry={nodes.bumper_front_5_4.geometry} material={materials['bumper_f0.6']} />
        <mesh name="bumper_front_5_5" castShadow receiveShadow geometry={nodes.bumper_front_5_5.geometry} material={materials['bumper_f0.7']} />
        <mesh name="bumper_front_5_6" castShadow receiveShadow geometry={nodes.bumper_front_5_6.geometry} material={materials['bumper_f0.8']} />
      </group>
      <group name="bumper_front_6" position={[0, -9.86, -2.42]}>
        <mesh name="bumper_front_6_1" castShadow receiveShadow geometry={nodes.bumper_front_6_1.geometry} material={materials['chassis.1']} />
        <mesh name="bumper_front_6_2" castShadow receiveShadow geometry={nodes.bumper_front_6_2.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="bumper_front_6_3" castShadow receiveShadow geometry={nodes.bumper_front_6_3.geometry} material={materials['bonnet0.3']} />
        <mesh name="bumper_front_6_4" castShadow receiveShadow geometry={nodes.bumper_front_6_4.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="bumper_front_6_5" castShadow receiveShadow geometry={nodes.bumper_front_6_5.geometry} material={materials.primary} />
        <mesh name="bumper_front_6_6" castShadow receiveShadow geometry={nodes.bumper_front_6_6.geometry} material={materials.carbon} />
        <mesh name="bumper_front_6_7" castShadow receiveShadow geometry={nodes.bumper_front_6_7.geometry} material={materials['right front light']} />
        <mesh name="bumper_front_6_8" castShadow receiveShadow geometry={nodes.bumper_front_6_8.geometry} material={materials['bumper_f0.6']} />
        <mesh name="bumper_front_6_9" castShadow receiveShadow geometry={nodes.bumper_front_6_9.geometry} material={materials['bumper_f0.7']} />
        <mesh name="bumper_front_6_10" castShadow receiveShadow geometry={nodes.bumper_front_6_10.geometry} material={materials['bumper_f0.8']} />
      </group>
      <group name="bumper_front_7" position={[0, -10.86, -2.42]}>
        <mesh name="bumper_front_7_1" castShadow receiveShadow geometry={nodes.bumper_front_7_1.geometry} material={materials['bonnet0.3']} />
        <mesh name="bumper_front_7_2" castShadow receiveShadow geometry={nodes.bumper_front_7_2.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="bumper_front_7_3" castShadow receiveShadow geometry={nodes.bumper_front_7_3.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="bumper_front_7_4" castShadow receiveShadow geometry={nodes.bumper_front_7_4.geometry} material={materials.primary} />
        <mesh name="bumper_front_7_5" castShadow receiveShadow geometry={nodes.bumper_front_7_5.geometry} material={materials['right front light']} />
        <mesh name="bumper_front_7_6" castShadow receiveShadow geometry={nodes.bumper_front_7_6.geometry} material={materials['bumper_f0.6']} />
        <mesh name="bumper_front_7_7" castShadow receiveShadow geometry={nodes.bumper_front_7_7.geometry} material={materials['bumper_f0.7']} />
        <mesh name="bumper_front_7_8" castShadow receiveShadow geometry={nodes.bumper_front_7_8.geometry} material={materials['bumper_f0.8']} />
      </group>
      <mesh name="bumper_rear_2" castShadow receiveShadow geometry={nodes.bumper_rear_2.geometry} material={materials.primary} position={[0, -6, 0]} />
      <group name="bumper_rear_3" position={[0, -7, 0]}>
        <mesh name="bumper_rear_3_1" castShadow receiveShadow geometry={nodes.bumper_rear_3_1.geometry} material={materials.primary} />
        <mesh name="bumper_rear_3_2" castShadow receiveShadow geometry={nodes.bumper_rear_3_2.geometry} material={materials['chassis.1']} />
      </group>
      <group name="bumper_rear_4" position={[0, -8, 0]}>
        <mesh name="bumper_rear_4_1" castShadow receiveShadow geometry={nodes.bumper_rear_4_1.geometry} material={materials.plastic} />
        <mesh name="bumper_rear_4_2" castShadow receiveShadow geometry={nodes.bumper_rear_4_2.geometry} material={materials.primary} />
        <mesh name="bumper_rear_4_3" castShadow receiveShadow geometry={nodes.bumper_rear_4_3.geometry} material={materials.carbon} />
      </group>
      <group name="bumper_rear_5" position={[0, -9, 0]}>
        <mesh name="bumper_rear_5_1" castShadow receiveShadow geometry={nodes.bumper_rear_5_1.geometry} material={materials.primary} />
        <mesh name="bumper_rear_5_2" castShadow receiveShadow geometry={nodes.bumper_rear_5_2.geometry} material={materials.carbon} />
        <mesh name="bumper_rear_5_3" castShadow receiveShadow geometry={nodes.bumper_rear_5_3.geometry} material={materials['bonnet0.3']} />
      </group>
      <group name="bumper_rear_6" position={[0, -10, 0]}>
        <mesh name="bumper_rear_6_1" castShadow receiveShadow geometry={nodes.bumper_rear_6_1.geometry} material={materials.plastic} />
        <mesh name="bumper_rear_6_2" castShadow receiveShadow geometry={nodes.bumper_rear_6_2.geometry} material={materials.primary} />
        <mesh name="bumper_rear_6_3" castShadow receiveShadow geometry={nodes.bumper_rear_6_3.geometry} material={materials.carbon} />
      </group>
      <group name="bumper_rear_7" position={[0, -11, 0]}>
        <mesh name="bumper_rear_7_1" castShadow receiveShadow geometry={nodes.bumper_rear_7_1.geometry} material={materials.primary} />
        <mesh name="bumper_rear_7_2" castShadow receiveShadow geometry={nodes.bumper_rear_7_2.geometry} material={materials.carbon} />
        <mesh name="bumper_rear_7_3" castShadow receiveShadow geometry={nodes.bumper_rear_7_3.geometry} material={materials['door_dside_f0.2']} />
      </group>
      <mesh name="skirts_1" castShadow receiveShadow geometry={nodes.skirts_1.geometry} material={materials.primary} position={[0, -0.158, -0.051]} />
      <group name="skirts_2" position={[0, -6, 0]}>
        <mesh name="skirts_2_1" castShadow receiveShadow geometry={nodes.skirts_2_1.geometry} material={materials.primary} />
        <mesh name="skirts_2_2" castShadow receiveShadow geometry={nodes.skirts_2_2.geometry} material={materials['bonnet0.3']} />
      </group>
      <group name="skirts_3" position={[0, -7, 0]}>
        <mesh name="skirts_3_1" castShadow receiveShadow geometry={nodes.skirts_3_1.geometry} material={materials.primary} />
        <mesh name="skirts_3_2" castShadow receiveShadow geometry={nodes.skirts_3_2.geometry} material={materials['bonnet0.3']} />
        <mesh name="skirts_3_3" castShadow receiveShadow geometry={nodes.skirts_3_3.geometry} material={materials['door_dside_f0.0']} />
      </group>
      <group name="skirts_4" position={[0, -8, 0]}>
        <mesh name="skirts_4_1" castShadow receiveShadow geometry={nodes.skirts_4_1.geometry} material={materials.primary} />
        <mesh name="skirts_4_2" castShadow receiveShadow geometry={nodes.skirts_4_2.geometry} material={materials.carbon} />
      </group>
      <group name="spoiler_1" position={[0, 0.715, 1.736]}>
        <mesh name="spoiler_1_1" castShadow receiveShadow geometry={nodes.spoiler_1_1.geometry} material={materials.carbon} />
        <mesh name="spoiler_1_2" castShadow receiveShadow geometry={nodes.spoiler_1_2.geometry} material={materials.primary} />
      </group>
      <mesh name="spoiler_2" castShadow receiveShadow geometry={nodes.spoiler_2.geometry} material={materials.primary} position={[0, -1.285, 1.736]} />
      <group name="spoiler_3" position={[0, -2.285, 1.736]}>
        <mesh name="spoiler_3_1" castShadow receiveShadow geometry={nodes.spoiler_3_1.geometry} material={materials.carbon} />
        <mesh name="spoiler_3_2" castShadow receiveShadow geometry={nodes.spoiler_3_2.geometry} material={materials['door_dside_f0.2']} />
      </group>
      <group name="spoiler_4" position={[0, -3.285, 1.736]}>
        <mesh name="spoiler_4_1" castShadow receiveShadow geometry={nodes.spoiler_4_1.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="spoiler_4_2" castShadow receiveShadow geometry={nodes.spoiler_4_2.geometry} material={materials.carbon} />
        <mesh name="spoiler_4_3" castShadow receiveShadow geometry={nodes.spoiler_4_3.geometry} material={materials['chassis.1']} />
      </group>
      <group name="spoiler_5" position={[0, -4.285, 1.736]}>
        <mesh name="spoiler_5_1" castShadow receiveShadow geometry={nodes.spoiler_5_1.geometry} material={materials.carbon} />
        <mesh name="spoiler_5_2" castShadow receiveShadow geometry={nodes.spoiler_5_2.geometry} material={materials.primary} />
      </group>
      <group name="wings_front_1" position={[0, 0.539, -1.644]}>
        <mesh name="wings_front_1_1" castShadow receiveShadow geometry={nodes.wings_front_1_1.geometry} material={materials.plastic} />
        <mesh name="wings_front_1_2" castShadow receiveShadow geometry={nodes.wings_front_1_2.geometry} material={materials.primary} />
        <mesh name="wings_front_1_3" castShadow receiveShadow geometry={nodes.wings_front_1_3.geometry} material={materials['fenders_f0.2']} />
        <mesh name="wings_front_1_4" castShadow receiveShadow geometry={nodes.wings_front_1_4.geometry} material={materials['fenders_f0.3']} />
      </group>
      <group name="wings_front_2" position={[0, -12.461, -1.644]}>
        <mesh name="wings_front_2_1" castShadow receiveShadow geometry={nodes.wings_front_2_1.geometry} material={materials.primary} />
        <mesh name="wings_front_2_2" castShadow receiveShadow geometry={nodes.wings_front_2_2.geometry} material={materials['door_dside_f0.0']} />
        <mesh name="wings_front_2_3" castShadow receiveShadow geometry={nodes.wings_front_2_3.geometry} material={materials['bonnet0.3']} />
      </group>
      <group name="fenders_rear_1" position={[0, -12.062, 1.525]}>
        <mesh name="wings_rear_1" castShadow receiveShadow geometry={nodes.wings_rear_1.geometry} material={materials.primary} />
        <mesh name="wings_rear_1_1" castShadow receiveShadow geometry={nodes.wings_rear_1_1.geometry} material={materials['bonnet0.3']} />
      </group>
      <group name="tail_lights_1" position={[0, 0.482, 2.373]}>
        <mesh name="tail_lights_1_1" castShadow receiveShadow geometry={nodes.tail_lights_1_1.geometry} material={materials['tail_lights0.0']} />
        <mesh name="tail_lights_1_2" castShadow receiveShadow geometry={nodes.tail_lights_1_2.geometry} material={materials['tail_lights0.1']} />
        <mesh name="tail_lights_1_3" castShadow receiveShadow geometry={nodes.tail_lights_1_3.geometry} material={materials['right rear light']} />
        <mesh name="tail_lights_1_4" castShadow receiveShadow geometry={nodes.tail_lights_1_4.geometry} material={materials['fenders_f0.3']} />
        <mesh name="tail_lights_1_5" castShadow receiveShadow geometry={nodes.tail_lights_1_5.geometry} material={materials['fenders_f0.2']} />
        <mesh name="tail_lights_1_6" castShadow receiveShadow geometry={nodes.tail_lights_1_6.geometry} material={materials['tail_lights0.5']} />
      </group>
      <group name="tail_lights_2" position={[0, -12, 0]}>
        <mesh name="tail_lights_2_1" castShadow receiveShadow geometry={nodes.tail_lights_2_1.geometry} material={materials['tail_lights0.1']} />
        <mesh name="tail_lights_2_2" castShadow receiveShadow geometry={nodes.tail_lights_2_2.geometry} material={materials['right rear light']} />
        <mesh name="tail_lights_2_3" castShadow receiveShadow geometry={nodes.tail_lights_2_3.geometry} material={materials['tail_lights0.0']} />
        <mesh name="tail_lights_2_4" castShadow receiveShadow geometry={nodes.tail_lights_2_4.geometry} material={materials['door_dside_f0.2']} />
        <mesh name="tail_lights_2_5" castShadow receiveShadow geometry={nodes.tail_lights_2_5.geometry} material={materials['tail_lights0.5']} />
        <mesh name="tail_lights_2_6" castShadow receiveShadow geometry={nodes.tail_lights_2_6.geometry} material={materials['fenders_f0.3']} />
        <mesh name="tail_lights_2_7" castShadow receiveShadow geometry={nodes.tail_lights_2_7.geometry} material={materials['fenders_f0.2']} />
      </group>
      <group name="head_lights_1" position={[0, 0.293, -2.329]}>
        <mesh name="head_lights_1_1" castShadow receiveShadow geometry={nodes.head_lights_1_1.geometry} material={materials['tail_lights0.0']} />
        <mesh name="head_lights_1_2" castShadow receiveShadow geometry={nodes.head_lights_1_2.geometry} material={materials['tail_lights0.1']} />
        <mesh name="head_lights_1_3" castShadow receiveShadow geometry={nodes.head_lights_1_3.geometry} material={materials['fenders_f0.2']} />
        <mesh name="head_lights_1_4" castShadow receiveShadow geometry={nodes.head_lights_1_4.geometry} material={materials['fenders_f0.3']} />
      </group>
      <mesh name="head_lights_glass" castShadow receiveShadow geometry={nodes.head_lights_glass.geometry} material={materials['glass.005']} position={[0, 0.293, -2.329]} />
      <mesh name="tail_lights_glass" castShadow receiveShadow geometry={nodes.tail_lights_glass.geometry} material={materials['glass.005']} position={[0, 0.482, 2.373]} />
      <mesh name="interior_1" castShadow receiveShadow geometry={nodes.interior_1.geometry} material={materials.primary} />
      <mesh name="interior_2" castShadow receiveShadow geometry={nodes.interior_2.geometry} material={materials['chassis.1']} />
      <mesh name="interior_3" castShadow receiveShadow geometry={nodes.interior_3.geometry} material={materials['door_dside_f0.0']} />
      <mesh name="interior_4" castShadow receiveShadow geometry={nodes.interior_4.geometry} material={materials['chassis.3']} />
      <mesh name="interior_5" castShadow receiveShadow geometry={nodes.interior_5.geometry} material={materials['door_dside_f0.2']} />
      <mesh name="interior_6" castShadow receiveShadow geometry={nodes.interior_6.geometry} material={materials['door_dside_f0.3']} />
      <mesh name="interior_7" castShadow receiveShadow geometry={nodes.interior_7.geometry} material={materials['chassis.6']} />
      <mesh name="interior_8" castShadow receiveShadow geometry={nodes.interior_8.geometry} material={materials.carbon} />
      <mesh name="interior_9" castShadow receiveShadow geometry={nodes.interior_9.geometry} material={materials['door_dside_f0.4']} />
      <mesh name="interior_10" castShadow receiveShadow geometry={nodes.interior_10.geometry} material={materials['chassis.9']} />
      <mesh name="interior_11" castShadow receiveShadow geometry={nodes.interior_11.geometry} material={materials['door_dside_f0.5']} />
      <mesh name="interior_12" castShadow receiveShadow geometry={nodes.interior_12.geometry} material={materials['chassis.11']} />
      <mesh name="interior_13" castShadow receiveShadow geometry={nodes.interior_13.geometry} material={materials['chassis.12']} />
      <mesh name="interior_14" castShadow receiveShadow geometry={nodes.interior_14.geometry} material={materials['chassis.13']} />
      <mesh name="interior_15" castShadow receiveShadow geometry={nodes.interior_15.geometry} material={materials['chassis.14']} />
      <mesh name="interior_16" castShadow receiveShadow geometry={nodes.interior_16.geometry} material={materials['chassis.15']} />
      <mesh name="interior_17" castShadow receiveShadow geometry={nodes.interior_17.geometry} material={materials['chassis.16']} />
      <mesh name="interior_18" castShadow receiveShadow geometry={nodes.interior_18.geometry} material={materials['chassis.17']} />
      <mesh name="interior_19" castShadow receiveShadow geometry={nodes.interior_19.geometry} material={materials['door_dside_f0.6']} />
      <mesh name="interior_20" castShadow receiveShadow geometry={nodes.interior_20.geometry} material={materials['chassis.19']} />
      <mesh name="interior_21" castShadow receiveShadow geometry={nodes.interior_21.geometry} material={materials.glass} />
      <mesh name="interior_22" castShadow receiveShadow geometry={nodes.interior_22.geometry} material={materials['chassis.22']} />
      <mesh name="interior_23" castShadow receiveShadow geometry={nodes.interior_23.geometry} material={materials['chassis.23']} />
      <mesh name="engine_with_suspension_1" castShadow receiveShadow geometry={nodes.engine_with_suspension_1.geometry} material={materials['chassis.1']} />
      <mesh name="engine_with_suspension_2" castShadow receiveShadow geometry={nodes.engine_with_suspension_2.geometry} material={materials['door_dside_f0.1']} />
      <mesh name="engine_with_suspension_3" castShadow receiveShadow geometry={nodes.engine_with_suspension_3.geometry} material={materials['block.2']} />
      <mesh name="engine_with_suspension_4" castShadow receiveShadow geometry={nodes.engine_with_suspension_4.geometry} material={materials['door_dside_f0.2']} />
      <mesh name="engine_with_suspension_5" castShadow receiveShadow geometry={nodes.engine_with_suspension_5.geometry} material={materials.disk_primary} />
      <mesh name="engine_with_suspension_6" castShadow receiveShadow geometry={nodes.engine_with_suspension_6.geometry} material={materials['block.5']} />
      <mesh name="steeringwheel_1" castShadow receiveShadow geometry={nodes.steeringwheel_1.geometry} material={materials['chassis.9']} />
      <mesh name="steeringwheel_2" castShadow receiveShadow geometry={nodes.steeringwheel_2.geometry} material={materials['chassis.11']} />
      <mesh name="steeringwheel_3" castShadow receiveShadow geometry={nodes.steeringwheel_3.geometry} material={materials['door_dside_f0.6']} />
      <mesh name="bodyshell_1" castShadow receiveShadow geometry={nodes.bodyshell_1.geometry} material={materials['chassis.1']} />
      <mesh name="bodyshell_2" castShadow receiveShadow geometry={nodes.bodyshell_2.geometry} material={materials.plastic} />
      <mesh name="bodyshell_3" castShadow receiveShadow geometry={nodes.bodyshell_3.geometry} material={materials['door_dside_f0.1']} />
      <mesh name="bodyshell_4" castShadow receiveShadow geometry={nodes.bodyshell_4.geometry} material={materials['door_dside_f0.2']} />
      <mesh name="bodyshell_5" castShadow receiveShadow geometry={nodes.bodyshell_5.geometry} material={materials['bodyshell.4']} />
      <mesh name="bodyshell_6" castShadow receiveShadow geometry={nodes.bodyshell_6.geometry} material={materials['bodyshell.5']} />
      <mesh name="bodyshell_7" castShadow receiveShadow geometry={nodes.bodyshell_7.geometry} material={materials['primary.001']} />
      <mesh name="bodyshell_8" castShadow receiveShadow geometry={nodes.bodyshell_8.geometry} material={materials['block.5']} />
      <mesh name="bodyshell_9" castShadow receiveShadow geometry={nodes.bodyshell_9.geometry} material={materials.primary} />
      <mesh name="exhaust_1_1" castShadow receiveShadow geometry={nodes.exhaust_1_1.geometry} material={materials['door_dside_f0.1']} />
      <mesh name="exhaust_1_2" castShadow receiveShadow geometry={nodes.exhaust_1_2.geometry} material={materials.exhaust} />
      <mesh name="bumper_rear_1_1" castShadow receiveShadow geometry={nodes.bumper_rear_1_1.geometry} material={materials.plastic} />
      <mesh name="bumper_rear_1_2" castShadow receiveShadow geometry={nodes.bumper_rear_1_2.geometry} material={materials.primary} />
      {/* <mesh name="dummy_bonnet" castShadow receiveShadow geometry={nodes.dummy_bonnet.geometry} material={nodes.dummy_bonnet.material} position={[0, 0.578, -1.132]} scale={0.1} />
      <mesh name="dummy_bumper_front" castShadow receiveShadow geometry={nodes.dummy_bumper_front.geometry} material={nodes.dummy_bumper_front.material} position={[0, 0.14, -2.42]} scale={0.03} />
      <mesh name="dummy_head_lights" castShadow receiveShadow geometry={nodes.dummy_head_lights.geometry} material={nodes.dummy_head_lights.material} position={[0, 0.293, -2.329]} scale={0.05} />
      <mesh name="dummy_wings_front" castShadow receiveShadow geometry={nodes.dummy_wings_front.geometry} material={nodes.dummy_wings_front.material} position={[0, 0.539, -1.644]} scale={0.05} />
      <mesh name="dummy_door_front_right" castShadow receiveShadow geometry={nodes.dummy_door_front_right.geometry} material={nodes.dummy_door_front_right.material} position={[0.937, 0.355, -0.955]} scale={0.1} />
      <mesh name="dummy_door_front_left" castShadow receiveShadow geometry={nodes.dummy_door_front_left.geometry} material={nodes.dummy_door_front_left.material} position={[-0.937, 0.355, -0.955]} scale={0.1} />
      <mesh name="dummy_door_rear_left" castShadow receiveShadow geometry={nodes.dummy_door_rear_left.geometry} material={nodes.dummy_door_rear_left.material} position={[-0.933, 0.345, 0.225]} scale={0.1} />
      <mesh name="dummy_door_rear_right" castShadow receiveShadow geometry={nodes.dummy_door_rear_right.geometry} material={nodes.dummy_door_rear_right.material} position={[0.932, 0.345, 0.225]} scale={0.1} />
      <mesh name="dummy_fenders_rear" castShadow receiveShadow geometry={nodes.dummy_fenders_rear.geometry} material={nodes.dummy_fenders_rear.material} position={[0, 0.938, 1.525]} scale={0.05} />
      <mesh name="dummy_trunk" castShadow receiveShadow geometry={nodes.dummy_trunk.geometry} material={nodes.dummy_trunk.material} position={[0, 0.715, 1.736]} scale={0.1} />
      <mesh name="dummy_tail_lights" castShadow receiveShadow geometry={nodes.dummy_tail_lights.geometry} material={nodes.dummy_tail_lights.material} position={[0, 0.482, 2.373]} scale={0.05} />
      <mesh name="dummy_bumper_rear" castShadow receiveShadow geometry={nodes.dummy_bumper_rear.geometry} material={nodes.dummy_bumper_rear.material} position={[0, 0.252, 2.447]} scale={0.05} />
      <mesh name="dummy_skirts" castShadow receiveShadow geometry={nodes.dummy_skirts.geometry} material={nodes.dummy_skirts.material} position={[0, -0.158, -0.051]} scale={0.2} />
      <mesh name="dummy_wheel_front_right" castShadow receiveShadow geometry={nodes.dummy_wheel_front_right.geometry} material={nodes.dummy_wheel_front_right.material} position={[0.819, -0.07, -1.445]} scale={0.1} />
      <mesh name="dummy_wheel_rear_right" castShadow receiveShadow geometry={nodes.dummy_wheel_rear_right.geometry} material={nodes.dummy_wheel_rear_right.material} position={[0.819, -0.07, 1.405]} scale={0.1} />
      <mesh name="dummy_wheel_rear_left" castShadow receiveShadow geometry={nodes.dummy_wheel_rear_left.geometry} material={nodes.dummy_wheel_rear_left.material} position={[-0.811, -0.07, 1.405]} scale={0.1} />
      <mesh name="dummy_wheel_front_left" castShadow receiveShadow geometry={nodes.dummy_wheel_front_left.geometry} material={nodes.dummy_wheel_front_left.material} position={[-0.811, -0.07, -1.445]} scale={0.1} /> */}
    </group>
  )
}

// useGLTF.preload('3d/gltf/cars/MitsubishiEvo9/mitsubishi_evo_9.gltf')
