/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./nissan_skyline_gt_r34.gltf --types --shadows --keepmaterials --keepmeshes --keepnames 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { degToRad } from 'three/src/math/MathUtils'

type GLTFResult = GLTF & {
  nodes: {
    wheel_1: THREE.Mesh
    wheel_2: THREE.Mesh
    wheel_3: THREE.Mesh
    wheel_4: THREE.Mesh
    steeringwheel_ok_1: THREE.Mesh
    steeringwheel_ok_2: THREE.Mesh
    steeringwheel_ok_3: THREE.Mesh
    steeringwheel_ok_4: THREE.Mesh
    steeringwheel_ok_5: THREE.Mesh
    steeringwheel_ok_6: THREE.Mesh
    steeringwheel_ok_7: THREE.Mesh
    trunk_1_1: THREE.Mesh
    trunk_1_2: THREE.Mesh
    trunk_1_3: THREE.Mesh
    bodyshell_1: THREE.Mesh
    bodyshell_2: THREE.Mesh
    bodyshell_3: THREE.Mesh
    bodyshell_4: THREE.Mesh
    bodyshell_5: THREE.Mesh
    bodyshell_6: THREE.Mesh
    bodyshell_7: THREE.Mesh
    bodyshell_8: THREE.Mesh
    bodyshell_9: THREE.Mesh
    bodyshell_10: THREE.Mesh
    bodyshell_11: THREE.Mesh
    bodyshell_12: THREE.Mesh
    bodyshell_13: THREE.Mesh
    bodyshell_14: THREE.Mesh
    bodyshell_15: THREE.Mesh
    bodyshell_16: THREE.Mesh
    bodyshell_17: THREE.Mesh
    bodyshell_18: THREE.Mesh
    bodyshell_19: THREE.Mesh
    bodyshell_20: THREE.Mesh
    bodyshell_21: THREE.Mesh
    bodyshell_22: THREE.Mesh
    bodyshell_23: THREE.Mesh
    bodyshell_24: THREE.Mesh
    bodyshell_25: THREE.Mesh
    bodyshell_26: THREE.Mesh
    bodyshell_27: THREE.Mesh
    bodyshell_28: THREE.Mesh
    door_front_right_1: THREE.Mesh
    door_front_right_2: THREE.Mesh
    door_front_right_3: THREE.Mesh
    door_front_right_4: THREE.Mesh
    door_front_right_5: THREE.Mesh
    door_front_right_6: THREE.Mesh
    door_front_right_7: THREE.Mesh
    door_front_right_8: THREE.Mesh
    door_front_right_9: THREE.Mesh
    door_front_right_10: THREE.Mesh
    door_front_right_11: THREE.Mesh
    door_front_right_12: THREE.Mesh
    door_front_right_13: THREE.Mesh
    door_front_right_14: THREE.Mesh
    door_front_left_1: THREE.Mesh
    door_front_left_2: THREE.Mesh
    door_front_left_3: THREE.Mesh
    door_front_left_4: THREE.Mesh
    door_front_left_5: THREE.Mesh
    door_front_left_6: THREE.Mesh
    door_front_left_7: THREE.Mesh
    door_front_left_8: THREE.Mesh
    door_front_left_9: THREE.Mesh
    door_front_left_10: THREE.Mesh
    door_front_left_11: THREE.Mesh
    door_front_left_12: THREE.Mesh
    door_front_left_13: THREE.Mesh
    trunk_badge0_1: THREE.Mesh
    trunk_badge0_2: THREE.Mesh
    spoiler_1_1: THREE.Mesh
    spoiler_1_2: THREE.Mesh
    spoiler_1_3: THREE.Mesh
    spoiler_1_4: THREE.Mesh
    spoiler_3_1: THREE.Mesh
    spoiler_3_2: THREE.Mesh
    spoiler_3_3: THREE.Mesh
    spoiler2: THREE.Mesh
    spoiler_2_1: THREE.Mesh
    spoiler_2_2: THREE.Mesh
    spoiler_2_3: THREE.Mesh
    spoiler_5_1: THREE.Mesh
    spoiler_5_2: THREE.Mesh
    spoiler_5_3: THREE.Mesh
    spoiler_4_1: THREE.Mesh
    spoiler_4_2: THREE.Mesh
    spoiler_4_3: THREE.Mesh
    spoiler_4_4: THREE.Mesh
    spoiler_6_1: THREE.Mesh
    spoiler_6_2: THREE.Mesh
    head_lights_1_1: THREE.Mesh
    head_lights_1_2: THREE.Mesh
    head_lights_2_1: THREE.Mesh
    head_lights_2_2: THREE.Mesh
    head_lights_2_3: THREE.Mesh
    head_lights_2_4: THREE.Mesh
    head_lights_2_5: THREE.Mesh
    skirts_1: THREE.Mesh
    skirts_5: THREE.Mesh
    skirts_4: THREE.Mesh
    skirts_3: THREE.Mesh
    bodykit_1_1: THREE.Mesh
    bodykit_1_2: THREE.Mesh
    bodykit_1_3: THREE.Mesh
    bodykit_1_4: THREE.Mesh
    skirts_2: THREE.Mesh
    diffuser_1: THREE.Mesh
    wings_rear_1: THREE.Mesh
    wings_rear_2: THREE.Mesh
    wings_front_1_1: THREE.Mesh
    wings_front_1_2: THREE.Mesh
    wings_front_1_3: THREE.Mesh
    wings_front_1_4: THREE.Mesh
    wings_front_1_5: THREE.Mesh
    wings_front_1_6: THREE.Mesh
    wings_front_2_1: THREE.Mesh
    wings_front_2_2: THREE.Mesh
    wings_front_2_3: THREE.Mesh
    wings_front_2_4: THREE.Mesh
    wings_front_2_5: THREE.Mesh
    wings_front_2_6: THREE.Mesh
    wings_front_3: THREE.Mesh
    tail_lights_1_1: THREE.Mesh
    tail_lights_1_2: THREE.Mesh
    tail_lights_1_3: THREE.Mesh
    tail_lights_1_4: THREE.Mesh
    tail_lights_1_5: THREE.Mesh
    tail_lights_1_6: THREE.Mesh
    tail_lights_1_7: THREE.Mesh
    bonnet_1_1: THREE.Mesh
    bonnet_1_2: THREE.Mesh
    bonnet_5_1: THREE.Mesh
    bonnet_5_2: THREE.Mesh
    bonnet_5_3: THREE.Mesh
    bonnet_4_1: THREE.Mesh
    bonnet_4_2: THREE.Mesh
    bonnet_4_3: THREE.Mesh
    bonnet_4_4: THREE.Mesh
    bonnet_3_1: THREE.Mesh
    bonnet_3_2: THREE.Mesh
    bonnet_3_3: THREE.Mesh
    bonnet_2_1: THREE.Mesh
    bonnet_2_2: THREE.Mesh
    bumper_front_2_1: THREE.Mesh
    bumper_front_2_2: THREE.Mesh
    bumper_front_2_3: THREE.Mesh
    bumper_front_2_4: THREE.Mesh
    bumper_front_2_5: THREE.Mesh
    bumper_front_2_6: THREE.Mesh
    bumper_front_2_7: THREE.Mesh
    bumper_front_2_8: THREE.Mesh
    bumper_front_6_1: THREE.Mesh
    bumper_front_6_2: THREE.Mesh
    bumper_front_6_3: THREE.Mesh
    bumper_front_6_4: THREE.Mesh
    bumper_front_6_5: THREE.Mesh
    bumper_front_6_6: THREE.Mesh
    bumper_front_6_7: THREE.Mesh
    bumper_front_1_1: THREE.Mesh
    bumper_front_1_2: THREE.Mesh
    bumper_front_1_3: THREE.Mesh
    bumper_front_1_4: THREE.Mesh
    bumper_front_1_5: THREE.Mesh
    bumper_front_1_6: THREE.Mesh
    bumper_front_1_7: THREE.Mesh
    bumper_front_7_1: THREE.Mesh
    bumper_front_7_2: THREE.Mesh
    bumper_front_7_3: THREE.Mesh
    bumper_front_7_4: THREE.Mesh
    bumper_front_7_5: THREE.Mesh
    bumper_front_8_1: THREE.Mesh
    bumper_front_8_2: THREE.Mesh
    bumper_front_8_3: THREE.Mesh
    bumper_front_8_4: THREE.Mesh
    bumper_front_8_5: THREE.Mesh
    bumper_front_8_6: THREE.Mesh
    bumper_front_8_7: THREE.Mesh
    bumper_front_8_8: THREE.Mesh
    bumper_front_8_9: THREE.Mesh
    bumper_front_4_1: THREE.Mesh
    bumper_front_4_2: THREE.Mesh
    bumper_front_4_3: THREE.Mesh
    bumper_front_4_4: THREE.Mesh
    bumper_front_4_5: THREE.Mesh
    bumper_front_4_6: THREE.Mesh
    bumper_front_3_1: THREE.Mesh
    bumper_front_3_2: THREE.Mesh
    bumper_front_3_3: THREE.Mesh
    bumper_front_3_4: THREE.Mesh
    bumper_front_3_5: THREE.Mesh
    bumper_front_3_6: THREE.Mesh
    bumper_front_5_1: THREE.Mesh
    bumper_front_5_2: THREE.Mesh
    bumper_front_5_3: THREE.Mesh
    bumper_front_5_4: THREE.Mesh
    bumper_front_5_5: THREE.Mesh
    bumper_front_5_6: THREE.Mesh
    bumper_rear_1_1: THREE.Mesh
    bumper_rear_1_2: THREE.Mesh
    bumper_rear_1_3: THREE.Mesh
    bumper_rear_1_4: THREE.Mesh
    bumper_rear_1_5: THREE.Mesh
    bumper_rear_1_6: THREE.Mesh
    bumper_rear_4_1: THREE.Mesh
    bumper_rear_4_2: THREE.Mesh
    bumper_rear_4_3: THREE.Mesh
    bumper_rear_4_4: THREE.Mesh
    bumper_rear_4_5: THREE.Mesh
    bumper_rear_4_6: THREE.Mesh
    bumper_rear_4_7: THREE.Mesh
    bumper_rear_2_1: THREE.Mesh
    bumper_rear_2_2: THREE.Mesh
    bumper_rear_2_3: THREE.Mesh
    bumper_rear_2_4: THREE.Mesh
    bumper_rear_2_5: THREE.Mesh
    bumper_rear_2_6: THREE.Mesh
    bumper_rear_6_1: THREE.Mesh
    bumper_rear_6_2: THREE.Mesh
    bumper_rear_6_3: THREE.Mesh
    bumper_rear_6_4: THREE.Mesh
    bumper_rear_6_5: THREE.Mesh
    bumper_rear_6_6: THREE.Mesh
    bumper_rear_5_1: THREE.Mesh
    bumper_rear_5_2: THREE.Mesh
    bumper_rear_5_3: THREE.Mesh
    bumper_rear_5_4: THREE.Mesh
    bumper_rear_5_5: THREE.Mesh
    bumper_rear_5_6: THREE.Mesh
    bumper_rear_5_7: THREE.Mesh
    bumper_rear_5_8: THREE.Mesh
    bumper_rear_3_1: THREE.Mesh
    bumper_rear_3_2: THREE.Mesh
    bumper_rear_3_3: THREE.Mesh
    bumper_rear_3_4: THREE.Mesh
    rear_glass: THREE.Mesh
    front_glass: THREE.Mesh
    head_lights_glass: THREE.Mesh
    dummy_bonnet: THREE.Mesh
    dummy_bumper_front: THREE.Mesh
    dummy_bumper_rear: THREE.Mesh
    dummu_diffuser: THREE.Mesh
    dummy_wings_front: THREE.Mesh
    dummy_trunk: THREE.Mesh
    dummy_skirts: THREE.Mesh
    dummy_head_lights: THREE.Mesh
    dummy_wings_rear: THREE.Mesh
    dummy_wheel_front_right: THREE.Mesh
    dummy_wheel_rear_right001: THREE.Mesh
    dummy_wheel_front_left: THREE.Mesh
    dummy_wheel_rear_left: THREE.Mesh
    dummy_door_front_right: THREE.Mesh
    dummy_door_front_left: THREE.Mesh
  }
  materials: {
    ['wheel.0']: THREE.MeshStandardMaterial
    ['wheel.1']: THREE.MeshStandardMaterial
    ['wheel.2']: THREE.MeshStandardMaterial
    ['wheel.3']: THREE.MeshStandardMaterial
    ['steeringwheel_ok.0']: THREE.MeshStandardMaterial
    ['steeringwheel_ok.1']: THREE.MeshStandardMaterial
    ['chassis_vlo.0']: THREE.MeshStandardMaterial
    ['steeringwheel_ok.3']: THREE.MeshStandardMaterial
    ['steeringwheel_ok.5']: THREE.MeshStandardMaterial
    ['steeringwheel_ok.6']: THREE.MeshStandardMaterial
    ['boot_ok.0']: THREE.MeshStandardMaterial
    ['boot_ok.1']: THREE.MeshStandardMaterial
    primary: THREE.MeshStandardMaterial
    ['main.3']: THREE.MeshStandardMaterial
    ['main.4']: THREE.MeshStandardMaterial
    ['main.5']: THREE.MeshStandardMaterial
    ['main.6']: THREE.MeshStandardMaterial
    ['main.7']: THREE.MeshStandardMaterial
    ['main.9']: THREE.MeshStandardMaterial
    ['chassis_vlo.1']: THREE.MeshStandardMaterial
    ['main.14']: THREE.MeshStandardMaterial
    ['main.16']: THREE.MeshStandardMaterial
    interior: THREE.MeshStandardMaterial
    ['main.19']: THREE.MeshStandardMaterial
    ['main.20']: THREE.MeshStandardMaterial
    ['main.21']: THREE.MeshStandardMaterial
    ['main.22']: THREE.MeshStandardMaterial
    ['main.23']: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    ['glass.002']: THREE.MeshStandardMaterial
    ['glass.005']: THREE.MeshStandardMaterial
    ['door_rf.10']: THREE.MeshStandardMaterial
    ['spoiler0.1']: THREE.MeshStandardMaterial
    ['spoiler5.1']: THREE.MeshStandardMaterial
    ['skirts4.3']: THREE.MeshStandardMaterial
    ['fenders_f0.4']: THREE.MeshStandardMaterial
    ['fenders_f0.5']: THREE.MeshStandardMaterial
    ['left rear light']: THREE.MeshStandardMaterial
    ['tail_lights1.1']: THREE.MeshStandardMaterial
    ['tail_lights0.3']: THREE.MeshStandardMaterial
    ['bumper_f4.4']: THREE.MeshStandardMaterial
    ['bumper_r0.1']: THREE.MeshStandardMaterial
    ['bumper_r0.3']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('3d/gltf/cars/NissanSkylineGTRR34/nissan_skyline_gt_r34.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} position={[0, .1105, 0]}>

      {/* wheels */}
      <group name="wheel_front_right" position={[0.844, 0.45, -1.37]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.3']} />
      </group>
      <group name="wheel_front_left" position={[-0.844, 0.45, -1.37]} rotation={[0, Math.PI, 0]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.3']} />
      </group>
      <group name="wheel_rear_right" position={[0.844, 0.45, 1.56]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.3']} />
      </group>
      <group name="wheel_rear_left" position={[-0.844, 0.45, 1.56]} rotation={[0, Math.PI, 0]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.3']} />
      </group>
      
      <group name="steeringwheel_ok" position={[0.393, 0.971, -0.289]} rotation={[-0.338, 0, 0]}>
        <mesh name="steeringwheel_ok_1" castShadow receiveShadow geometry={nodes.steeringwheel_ok_1.geometry} material={materials['steeringwheel_ok.0']} />
        <mesh name="steeringwheel_ok_2" castShadow receiveShadow geometry={nodes.steeringwheel_ok_2.geometry} material={materials['steeringwheel_ok.1']} />
        <mesh name="steeringwheel_ok_3" castShadow receiveShadow geometry={nodes.steeringwheel_ok_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="steeringwheel_ok_4" castShadow receiveShadow geometry={nodes.steeringwheel_ok_4.geometry} material={materials['steeringwheel_ok.3']} />
        <mesh name="steeringwheel_ok_5" castShadow receiveShadow geometry={nodes.steeringwheel_ok_5.geometry} material={materials['wheel.1']} />
        <mesh name="steeringwheel_ok_6" castShadow receiveShadow geometry={nodes.steeringwheel_ok_6.geometry} material={materials['steeringwheel_ok.5']} />
        <mesh name="steeringwheel_ok_7" castShadow receiveShadow geometry={nodes.steeringwheel_ok_7.geometry} material={materials['steeringwheel_ok.6']} />
      </group>
      <group name="trunk_1" position={[0, 1.203, 1.761]}>
        <mesh name="trunk_1_1" castShadow receiveShadow geometry={nodes.trunk_1_1.geometry} material={materials['boot_ok.0']} />
        <mesh name="trunk_1_2" castShadow receiveShadow geometry={nodes.trunk_1_2.geometry} material={materials['boot_ok.1']} />
        <mesh name="trunk_1_3" castShadow receiveShadow geometry={nodes.trunk_1_3.geometry} material={materials.primary} />
      </group>
      <group name="bodyshell" position={[-0.24, 0.9, 0]}>
        <mesh name="bodyshell_1" castShadow receiveShadow geometry={nodes.bodyshell_1.geometry} material={materials['steeringwheel_ok.1']} />
        <mesh name="bodyshell_2" castShadow receiveShadow geometry={nodes.bodyshell_2.geometry} material={materials['steeringwheel_ok.6']} />
        <mesh name="bodyshell_3" castShadow receiveShadow geometry={nodes.bodyshell_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bodyshell_4" castShadow receiveShadow geometry={nodes.bodyshell_4.geometry} material={materials['main.3']} />
        <mesh name="bodyshell_5" castShadow receiveShadow geometry={nodes.bodyshell_5.geometry} material={materials['main.4']} />
        <mesh name="bodyshell_6" castShadow receiveShadow geometry={nodes.bodyshell_6.geometry} material={materials['main.5']} />
        <mesh name="bodyshell_7" castShadow receiveShadow geometry={nodes.bodyshell_7.geometry} material={materials['main.6']} />
        <mesh name="bodyshell_8" castShadow receiveShadow geometry={nodes.bodyshell_8.geometry} material={materials['main.7']} />
        <mesh name="bodyshell_9" castShadow receiveShadow geometry={nodes.bodyshell_9.geometry} material={materials.primary} />
        <mesh name="bodyshell_10" castShadow receiveShadow geometry={nodes.bodyshell_10.geometry} material={materials['main.9']} />
        <mesh name="bodyshell_11" castShadow receiveShadow geometry={nodes.bodyshell_11.geometry} material={materials['chassis_vlo.1']} />
        <mesh name="bodyshell_12" castShadow receiveShadow geometry={nodes.bodyshell_12.geometry} material={materials['wheel.1']} />
        <mesh name="bodyshell_13" castShadow receiveShadow geometry={nodes.bodyshell_13.geometry} material={materials['steeringwheel_ok.0']} />
        <mesh name="bodyshell_14" castShadow receiveShadow geometry={nodes.bodyshell_14.geometry} material={materials['boot_ok.0']} />
        <mesh name="bodyshell_15" castShadow receiveShadow geometry={nodes.bodyshell_15.geometry} material={materials['main.14']} />
        <mesh name="bodyshell_16" castShadow receiveShadow geometry={nodes.bodyshell_16.geometry} material={materials['steeringwheel_ok.3']} />
        <mesh name="bodyshell_17" castShadow receiveShadow geometry={nodes.bodyshell_17.geometry} material={materials['main.16']} />
        <mesh name="bodyshell_18" castShadow receiveShadow geometry={nodes.bodyshell_18.geometry} material={materials.interior} />
        <mesh name="bodyshell_19" castShadow receiveShadow geometry={nodes.bodyshell_19.geometry} material={materials['steeringwheel_ok.5']} />
        <mesh name="bodyshell_20" castShadow receiveShadow geometry={nodes.bodyshell_20.geometry} material={materials['main.19']} />
        <mesh name="bodyshell_21" castShadow receiveShadow geometry={nodes.bodyshell_21.geometry} material={materials['main.20']} />
        <mesh name="bodyshell_22" castShadow receiveShadow geometry={nodes.bodyshell_22.geometry} material={materials['main.21']} />
        <mesh name="bodyshell_23" castShadow receiveShadow geometry={nodes.bodyshell_23.geometry} material={materials['main.22']} />
        <mesh name="bodyshell_24" castShadow receiveShadow geometry={nodes.bodyshell_24.geometry} material={materials['main.23']} />
        <mesh name="bodyshell_25" castShadow receiveShadow geometry={nodes.bodyshell_25.geometry} material={materials.glass} />
        <mesh name="bodyshell_26" castShadow receiveShadow geometry={nodes.bodyshell_26.geometry} material={materials['boot_ok.1']} />
        <mesh name="bodyshell_27" castShadow receiveShadow geometry={nodes.bodyshell_27.geometry} material={materials['glass.002']} />
        <mesh name="bodyshell_28" castShadow receiveShadow geometry={nodes.bodyshell_28.geometry} material={materials['glass.005']} />
      </group>
      <group name="door_front_right" position={[0.942, 0.781, -0.739]}>
        <mesh name="door_front_right_1" castShadow receiveShadow geometry={nodes.door_front_right_1.geometry} material={materials['main.7']} />
        <mesh name="door_front_right_2" castShadow receiveShadow geometry={nodes.door_front_right_2.geometry} material={materials['main.4']} />
        <mesh name="door_front_right_3" castShadow receiveShadow geometry={nodes.door_front_right_3.geometry} material={materials['chassis_vlo.1']} />
        <mesh name="door_front_right_4" castShadow receiveShadow geometry={nodes.door_front_right_4.geometry} material={materials.primary} />
        <mesh name="door_front_right_5" castShadow receiveShadow geometry={nodes.door_front_right_5.geometry} material={materials['steeringwheel_ok.6']} />
        <mesh name="door_front_right_6" castShadow receiveShadow geometry={nodes.door_front_right_6.geometry} material={materials['main.14']} />
        <mesh name="door_front_right_7" castShadow receiveShadow geometry={nodes.door_front_right_7.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="door_front_right_8" castShadow receiveShadow geometry={nodes.door_front_right_8.geometry} material={materials['main.21']} />
        <mesh name="door_front_right_9" castShadow receiveShadow geometry={nodes.door_front_right_9.geometry} material={materials['main.23']} />
        <mesh name="door_front_right_10" castShadow receiveShadow geometry={nodes.door_front_right_10.geometry} material={materials['main.22']} />
        <mesh name="door_front_right_11" castShadow receiveShadow geometry={nodes.door_front_right_11.geometry} material={materials['door_rf.10']} />
        <mesh name="door_front_right_12" castShadow receiveShadow geometry={nodes.door_front_right_12.geometry} material={materials['steeringwheel_ok.1']} />
        <mesh name="door_front_right_13" castShadow receiveShadow geometry={nodes.door_front_right_13.geometry} material={materials['boot_ok.1']} />
        <mesh name="door_front_right_14" castShadow receiveShadow geometry={nodes.door_front_right_14.geometry} material={materials['glass.005']} />
      </group>
      <group name="door_front_left" position={[-0.944, 0.781, -0.739]}>
        <mesh name="door_front_left_1" castShadow receiveShadow geometry={nodes.door_front_left_1.geometry} material={materials['main.7']} />
        <mesh name="door_front_left_2" castShadow receiveShadow geometry={nodes.door_front_left_2.geometry} material={materials['main.4']} />
        <mesh name="door_front_left_3" castShadow receiveShadow geometry={nodes.door_front_left_3.geometry} material={materials['chassis_vlo.1']} />
        <mesh name="door_front_left_4" castShadow receiveShadow geometry={nodes.door_front_left_4.geometry} material={materials.primary} />
        <mesh name="door_front_left_5" castShadow receiveShadow geometry={nodes.door_front_left_5.geometry} material={materials['steeringwheel_ok.6']} />
        <mesh name="door_front_left_6" castShadow receiveShadow geometry={nodes.door_front_left_6.geometry} material={materials['steeringwheel_ok.1']} />
        <mesh name="door_front_left_7" castShadow receiveShadow geometry={nodes.door_front_left_7.geometry} material={materials['main.21']} />
        <mesh name="door_front_left_8" castShadow receiveShadow geometry={nodes.door_front_left_8.geometry} material={materials['main.23']} />
        <mesh name="door_front_left_9" castShadow receiveShadow geometry={nodes.door_front_left_9.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="door_front_left_10" castShadow receiveShadow geometry={nodes.door_front_left_10.geometry} material={materials['door_rf.10']} />
        <mesh name="door_front_left_11" castShadow receiveShadow geometry={nodes.door_front_left_11.geometry} material={materials['main.22']} />
        <mesh name="door_front_left_12" castShadow receiveShadow geometry={nodes.door_front_left_12.geometry} material={materials['boot_ok.1']} />
        <mesh name="door_front_left_13" castShadow receiveShadow geometry={nodes.door_front_left_13.geometry} material={materials['glass.005']} />
      </group>
      <group name="trunk_badge0" position={[0, 1.203, 1.761]}>
        <mesh name="trunk_badge0_1" castShadow receiveShadow geometry={nodes.trunk_badge0_1.geometry} material={materials['boot_ok.1']} />
        <mesh name="trunk_badge0_2" castShadow receiveShadow geometry={nodes.trunk_badge0_2.geometry} material={materials['chassis_vlo.0']} />
      </group>
      <group name="spoiler_1" position={[0, 1.203, 1.761]}>
        <mesh name="spoiler_1_1" castShadow receiveShadow geometry={nodes.spoiler_1_1.geometry} material={materials.primary} />
        <mesh name="spoiler_1_2" castShadow receiveShadow geometry={nodes.spoiler_1_2.geometry} material={materials['spoiler0.1']} />
        <mesh name="spoiler_1_3" castShadow receiveShadow geometry={nodes.spoiler_1_3.geometry} material={materials['main.7']} />
        <mesh name="spoiler_1_4" castShadow receiveShadow geometry={nodes.spoiler_1_4.geometry} material={materials['chassis_vlo.1']} />
      </group>
      <group name="spoiler_3" position={[0, -11.797, 1.761]}>
        <mesh name="spoiler_3_1" castShadow receiveShadow geometry={nodes.spoiler_3_1.geometry} material={materials['main.9']} />
        <mesh name="spoiler_3_2" castShadow receiveShadow geometry={nodes.spoiler_3_2.geometry} material={materials.primary} />
        <mesh name="spoiler_3_3" castShadow receiveShadow geometry={nodes.spoiler_3_3.geometry} material={materials['spoiler0.1']} />
      </group>
      <mesh name="spoiler2" castShadow receiveShadow geometry={nodes.spoiler2.geometry} material={materials.primary} position={[0, 1.203, 1.761]} />
      <group name="spoiler_2" position={[0, -10.797, 1.761]}>
        <mesh name="spoiler_2_1" castShadow receiveShadow geometry={nodes.spoiler_2_1.geometry} material={materials['chassis_vlo.1']} />
        <mesh name="spoiler_2_2" castShadow receiveShadow geometry={nodes.spoiler_2_2.geometry} material={materials.primary} />
        <mesh name="spoiler_2_3" castShadow receiveShadow geometry={nodes.spoiler_2_3.geometry} material={materials['main.9']} />
      </group>
      <group name="spoiler_5" position={[0, -13.797, 1.761]}>
        <mesh name="spoiler_5_1" castShadow receiveShadow geometry={nodes.spoiler_5_1.geometry} material={materials['spoiler0.1']} />
        <mesh name="spoiler_5_2" castShadow receiveShadow geometry={nodes.spoiler_5_2.geometry} material={materials.primary} />
        <mesh name="spoiler_5_3" castShadow receiveShadow geometry={nodes.spoiler_5_3.geometry} material={materials['main.9']} />
      </group>
      <group name="spoiler_4" position={[0, -12.797, 1.761]}>
        <mesh name="spoiler_4_1" castShadow receiveShadow geometry={nodes.spoiler_4_1.geometry} material={materials['main.7']} />
        <mesh name="spoiler_4_2" castShadow receiveShadow geometry={nodes.spoiler_4_2.geometry} material={materials['spoiler5.1']} />
        <mesh name="spoiler_4_3" castShadow receiveShadow geometry={nodes.spoiler_4_3.geometry} material={materials['spoiler0.1']} />
        <mesh name="spoiler_4_4" castShadow receiveShadow geometry={nodes.spoiler_4_4.geometry} material={materials.primary} />
      </group>
      <group name="spoiler_6" position={[0, -14.797, 1.761]}>
        <mesh name="spoiler_6_1" castShadow receiveShadow geometry={nodes.spoiler_6_1.geometry} material={materials['chassis_vlo.1']} />
        <mesh name="spoiler_6_2" castShadow receiveShadow geometry={nodes.spoiler_6_2.geometry} material={materials['spoiler0.1']} />
      </group>
      <group name="head_lights_1" position={[0, 1.04, -1.82]}>
        <mesh name="head_lights_1_1" castShadow receiveShadow geometry={nodes.head_lights_1_1.geometry} material={materials['main.23']} />
        <mesh name="head_lights_1_2" castShadow receiveShadow geometry={nodes.head_lights_1_2.geometry} material={materials['glass.005']} />
      </group>
      <group name="head_lights_2" position={[0, -14.96, -1.82]}>
        <mesh name="head_lights_2_1" castShadow receiveShadow geometry={nodes.head_lights_2_1.geometry} material={materials.primary} />
        <mesh name="head_lights_2_2" castShadow receiveShadow geometry={nodes.head_lights_2_2.geometry} material={materials['spoiler0.1']} />
        <mesh name="head_lights_2_3" castShadow receiveShadow geometry={nodes.head_lights_2_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="head_lights_2_4" castShadow receiveShadow geometry={nodes.head_lights_2_4.geometry} material={materials['main.23']} />
        <mesh name="head_lights_2_5" castShadow receiveShadow geometry={nodes.head_lights_2_5.geometry} material={materials['glass.005']} />
      </group>
      <mesh name="skirts_1" castShadow receiveShadow geometry={nodes.skirts_1.geometry} material={materials.primary} position={[0.003, 0.405, -0.022]} />
      <mesh name="skirts_5" castShadow receiveShadow geometry={nodes.skirts_5.geometry} material={materials.primary} position={[0.003, -8.595, -0.022]} />
      <mesh name="skirts_4" castShadow receiveShadow geometry={nodes.skirts_4.geometry} material={materials.primary} position={[0.003, -7.595, -0.022]} />
      <mesh name="skirts_3" castShadow receiveShadow geometry={nodes.skirts_3.geometry} material={materials.primary} position={[0.003, -6.595, -0.022]} />
      <group name="bodykit_1" position={[0, -17.4, 0]}>
        <mesh name="bodykit_1_1" castShadow receiveShadow geometry={nodes.bodykit_1_1.geometry} material={materials.primary} />
        <mesh name="bodykit_1_2" castShadow receiveShadow geometry={nodes.bodykit_1_2.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bodykit_1_3" castShadow receiveShadow geometry={nodes.bodykit_1_3.geometry} material={materials['boot_ok.1']} />
        <mesh name="bodykit_1_4" castShadow receiveShadow geometry={nodes.bodykit_1_4.geometry} material={materials['skirts4.3']} />
      </group>
      <mesh name="skirts_2" castShadow receiveShadow geometry={nodes.skirts_2.geometry} material={materials.primary} position={[0.003, -5.595, -0.022]} />
      <mesh name="diffuser_1" castShadow receiveShadow geometry={nodes.diffuser_1.geometry} material={materials['spoiler0.1']} position={[0, 0.391, 2.641]} />
      <mesh name="wings_rear_1" castShadow receiveShadow geometry={nodes.wings_rear_1.geometry} material={materials.primary} position={[0, 1.567, 0.907]} />
      <mesh name="wings_rear_2" castShadow receiveShadow geometry={nodes.wings_rear_2.geometry} material={materials.primary} position={[0, -15.433, 0.907]} />
      <group name="wings_front_1" position={[0, 1.108, -1.364]}>
        <mesh name="wings_front_1_1" castShadow receiveShadow geometry={nodes.wings_front_1_1.geometry} material={materials.primary} />
        <mesh name="wings_front_1_2" castShadow receiveShadow geometry={nodes.wings_front_1_2.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="wings_front_1_3" castShadow receiveShadow geometry={nodes.wings_front_1_3.geometry} material={materials['boot_ok.1']} />
        <mesh name="wings_front_1_4" castShadow receiveShadow geometry={nodes.wings_front_1_4.geometry} material={materials['main.7']} />
        <mesh name="wings_front_1_5" castShadow receiveShadow geometry={nodes.wings_front_1_5.geometry} material={materials['fenders_f0.4']} />
        <mesh name="wings_front_1_6" castShadow receiveShadow geometry={nodes.wings_front_1_6.geometry} material={materials['fenders_f0.5']} />
      </group>
      <group name="wings_front_2" position={[0, -12.892, -1.364]}>
        <mesh name="wings_front_2_1" castShadow receiveShadow geometry={nodes.wings_front_2_1.geometry} material={materials.primary} />
        <mesh name="wings_front_2_2" castShadow receiveShadow geometry={nodes.wings_front_2_2.geometry} material={materials['boot_ok.1']} />
        <mesh name="wings_front_2_3" castShadow receiveShadow geometry={nodes.wings_front_2_3.geometry} material={materials['fenders_f0.4']} />
        <mesh name="wings_front_2_4" castShadow receiveShadow geometry={nodes.wings_front_2_4.geometry} material={materials['main.7']} />
        <mesh name="wings_front_2_5" castShadow receiveShadow geometry={nodes.wings_front_2_5.geometry} material={materials['fenders_f0.5']} />
        <mesh name="wings_front_2_6" castShadow receiveShadow geometry={nodes.wings_front_2_6.geometry} material={materials['chassis_vlo.0']} />
      </group>
      <mesh name="wings_front_3" castShadow receiveShadow geometry={nodes.wings_front_3.geometry} material={materials.primary} position={[0, -13.892, -1.364]} />
      <group name="tail_lights_1" position={[-0.24, 0.9, 0]}>
        <mesh name="tail_lights_1_1" castShadow receiveShadow geometry={nodes.tail_lights_1_1.geometry} material={materials['left rear light']} />
        <mesh name="tail_lights_1_2" castShadow receiveShadow geometry={nodes.tail_lights_1_2.geometry} material={materials['tail_lights1.1']} />
        <mesh name="tail_lights_1_3" castShadow receiveShadow geometry={nodes.tail_lights_1_3.geometry} material={materials['boot_ok.0']} />
        <mesh name="tail_lights_1_4" castShadow receiveShadow geometry={nodes.tail_lights_1_4.geometry} material={materials['main.7']} />
        <mesh name="tail_lights_1_5" castShadow receiveShadow geometry={nodes.tail_lights_1_5.geometry} material={materials['tail_lights0.3']} />
        <mesh name="tail_lights_1_6" castShadow receiveShadow geometry={nodes.tail_lights_1_6.geometry} material={materials['fenders_f0.5']} />
        <mesh name="tail_lights_1_7" castShadow receiveShadow geometry={nodes.tail_lights_1_7.geometry} material={materials['fenders_f0.4']} />
      </group>
      <group name="bonnet_1" position={[0, 1.111, -0.769]}>
        <mesh name="bonnet_1_1" castShadow receiveShadow geometry={nodes.bonnet_1_1.geometry} material={materials.primary} />
        <mesh name="bonnet_1_2" castShadow receiveShadow geometry={nodes.bonnet_1_2.geometry} material={materials['main.7']} />
      </group>
      <group name="bonnet_5" position={[0, -3.889, -0.769]}>
        <mesh name="bonnet_5_1" castShadow receiveShadow geometry={nodes.bonnet_5_1.geometry} material={materials.primary} />
        <mesh name="bonnet_5_2" castShadow receiveShadow geometry={nodes.bonnet_5_2.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bonnet_5_3" castShadow receiveShadow geometry={nodes.bonnet_5_3.geometry} material={materials['main.7']} />
      </group>
      <group name="bonnet_4" position={[0, -2.889, -0.769]}>
        <mesh name="bonnet_4_1" castShadow receiveShadow geometry={nodes.bonnet_4_1.geometry} material={materials.primary} />
        <mesh name="bonnet_4_2" castShadow receiveShadow geometry={nodes.bonnet_4_2.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bonnet_4_3" castShadow receiveShadow geometry={nodes.bonnet_4_3.geometry} material={materials['main.7']} />
        <mesh name="bonnet_4_4" castShadow receiveShadow geometry={nodes.bonnet_4_4.geometry} material={materials['main.6']} />
      </group>
      <group name="bonnet_3" position={[0, -1.889, -0.769]}>
        <mesh name="bonnet_3_1" castShadow receiveShadow geometry={nodes.bonnet_3_1.geometry} material={materials.primary} />
        <mesh name="bonnet_3_2" castShadow receiveShadow geometry={nodes.bonnet_3_2.geometry} material={materials['main.9']} />
        <mesh name="bonnet_3_3" castShadow receiveShadow geometry={nodes.bonnet_3_3.geometry} material={materials['main.7']} />
      </group>
      <group name="bonnet_2" position={[0, -0.889, -0.769]}>
        <mesh name="bonnet_2_1" castShadow receiveShadow geometry={nodes.bonnet_2_1.geometry} material={materials.primary} />
        <mesh name="bonnet_2_2" castShadow receiveShadow geometry={nodes.bonnet_2_2.geometry} material={materials['chassis_vlo.0']} />
      </group>
      <group name="bumper_front_2" position={[0, -5.11, -2.338]}>
        <mesh name="bumper_front_2_1" castShadow receiveShadow geometry={nodes.bumper_front_2_1.geometry} material={materials['main.4']} />
        <mesh name="bumper_front_2_2" castShadow receiveShadow geometry={nodes.bumper_front_2_2.geometry} material={materials['spoiler5.1']} />
        <mesh name="bumper_front_2_3" castShadow receiveShadow geometry={nodes.bumper_front_2_3.geometry} material={materials['main.7']} />
        <mesh name="bumper_front_2_4" castShadow receiveShadow geometry={nodes.bumper_front_2_4.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bumper_front_2_5" castShadow receiveShadow geometry={nodes.bumper_front_2_5.geometry} material={materials['fenders_f0.4']} />
        <mesh name="bumper_front_2_6" castShadow receiveShadow geometry={nodes.bumper_front_2_6.geometry} material={materials['fenders_f0.5']} />
        <mesh name="bumper_front_2_7" castShadow receiveShadow geometry={nodes.bumper_front_2_7.geometry} material={materials['boot_ok.1']} />
        <mesh name="bumper_front_2_8" castShadow receiveShadow geometry={nodes.bumper_front_2_8.geometry} material={materials.primary} />
      </group>
      <group name="bumper_front_6" position={[0, -9.11, -2.338]}>
        <mesh name="bumper_front_6_1" castShadow receiveShadow geometry={nodes.bumper_front_6_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_6_2" castShadow receiveShadow geometry={nodes.bumper_front_6_2.geometry} material={materials['main.4']} />
        <mesh name="bumper_front_6_3" castShadow receiveShadow geometry={nodes.bumper_front_6_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bumper_front_6_4" castShadow receiveShadow geometry={nodes.bumper_front_6_4.geometry} material={materials['spoiler5.1']} />
        <mesh name="bumper_front_6_5" castShadow receiveShadow geometry={nodes.bumper_front_6_5.geometry} material={materials['fenders_f0.5']} />
        <mesh name="bumper_front_6_6" castShadow receiveShadow geometry={nodes.bumper_front_6_6.geometry} material={materials['fenders_f0.4']} />
        <mesh name="bumper_front_6_7" castShadow receiveShadow geometry={nodes.bumper_front_6_7.geometry} material={materials['boot_ok.1']} />
      </group>
      <group name="bumper_front_1" position={[0, 0.89, -2.338]}>
        <mesh name="bumper_front_1_1" castShadow receiveShadow geometry={nodes.bumper_front_1_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_1_2" castShadow receiveShadow geometry={nodes.bumper_front_1_2.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bumper_front_1_3" castShadow receiveShadow geometry={nodes.bumper_front_1_3.geometry} material={materials['boot_ok.1']} />
        <mesh name="bumper_front_1_4" castShadow receiveShadow geometry={nodes.bumper_front_1_4.geometry} material={materials['fenders_f0.4']} />
        <mesh name="bumper_front_1_5" castShadow receiveShadow geometry={nodes.bumper_front_1_5.geometry} material={materials['spoiler5.1']} />
        <mesh name="bumper_front_1_6" castShadow receiveShadow geometry={nodes.bumper_front_1_6.geometry} material={materials['fenders_f0.5']} />
        <mesh name="bumper_front_1_7" castShadow receiveShadow geometry={nodes.bumper_front_1_7.geometry} material={materials['spoiler0.1']} />
      </group>
      <group name="bumper_front_7" position={[0, -10.11, -2.338]}>
        <mesh name="bumper_front_7_1" castShadow receiveShadow geometry={nodes.bumper_front_7_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_7_2" castShadow receiveShadow geometry={nodes.bumper_front_7_2.geometry} material={materials['spoiler0.1']} />
        <mesh name="bumper_front_7_3" castShadow receiveShadow geometry={nodes.bumper_front_7_3.geometry} material={materials['spoiler5.1']} />
        <mesh name="bumper_front_7_4" castShadow receiveShadow geometry={nodes.bumper_front_7_4.geometry} material={materials['boot_ok.1']} />
        <mesh name="bumper_front_7_5" castShadow receiveShadow geometry={nodes.bumper_front_7_5.geometry} material={materials['chassis_vlo.0']} />
      </group>
      <group name="bumper_front_8" position={[0, -11.11, -2.338]}>
        <mesh name="bumper_front_8_1" castShadow receiveShadow geometry={nodes.bumper_front_8_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_8_2" castShadow receiveShadow geometry={nodes.bumper_front_8_2.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bumper_front_8_3" castShadow receiveShadow geometry={nodes.bumper_front_8_3.geometry} material={materials['spoiler0.1']} />
        <mesh name="bumper_front_8_4" castShadow receiveShadow geometry={nodes.bumper_front_8_4.geometry} material={materials['spoiler5.1']} />
        <mesh name="bumper_front_8_5" castShadow receiveShadow geometry={nodes.bumper_front_8_5.geometry} material={materials['bumper_f4.4']} />
        <mesh name="bumper_front_8_6" castShadow receiveShadow geometry={nodes.bumper_front_8_6.geometry} material={materials['main.23']} />
        <mesh name="bumper_front_8_7" castShadow receiveShadow geometry={nodes.bumper_front_8_7.geometry} material={materials['fenders_f0.4']} />
        <mesh name="bumper_front_8_8" castShadow receiveShadow geometry={nodes.bumper_front_8_8.geometry} material={materials['fenders_f0.5']} />
        <mesh name="bumper_front_8_9" castShadow receiveShadow geometry={nodes.bumper_front_8_9.geometry} material={materials['boot_ok.1']} />
      </group>
      <group name="bumper_front_4" position={[0, -7.11, -2.338]}>
        <mesh name="bumper_front_4_1" castShadow receiveShadow geometry={nodes.bumper_front_4_1.geometry} material={materials['spoiler5.1']} />
        <mesh name="bumper_front_4_2" castShadow receiveShadow geometry={nodes.bumper_front_4_2.geometry} material={materials['fenders_f0.5']} />
        <mesh name="bumper_front_4_3" castShadow receiveShadow geometry={nodes.bumper_front_4_3.geometry} material={materials['fenders_f0.4']} />
        <mesh name="bumper_front_4_4" castShadow receiveShadow geometry={nodes.bumper_front_4_4.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bumper_front_4_5" castShadow receiveShadow geometry={nodes.bumper_front_4_5.geometry} material={materials['boot_ok.1']} />
        <mesh name="bumper_front_4_6" castShadow receiveShadow geometry={nodes.bumper_front_4_6.geometry} material={materials.primary} />
      </group>
      <group name="bumper_front_3" position={[0, -6.11, -2.338]}>
        <mesh name="bumper_front_3_1" castShadow receiveShadow geometry={nodes.bumper_front_3_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_3_2" castShadow receiveShadow geometry={nodes.bumper_front_3_2.geometry} material={materials['skirts4.3']} />
        <mesh name="bumper_front_3_3" castShadow receiveShadow geometry={nodes.bumper_front_3_3.geometry} material={materials['spoiler5.1']} />
        <mesh name="bumper_front_3_4" castShadow receiveShadow geometry={nodes.bumper_front_3_4.geometry} material={materials['fenders_f0.4']} />
        <mesh name="bumper_front_3_5" castShadow receiveShadow geometry={nodes.bumper_front_3_5.geometry} material={materials['fenders_f0.5']} />
        <mesh name="bumper_front_3_6" castShadow receiveShadow geometry={nodes.bumper_front_3_6.geometry} material={materials['boot_ok.1']} />
      </group>
      <group name="bumper_front_5" position={[0, -8.11, -2.338]}>
        <mesh name="bumper_front_5_1" castShadow receiveShadow geometry={nodes.bumper_front_5_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_5_2" castShadow receiveShadow geometry={nodes.bumper_front_5_2.geometry} material={materials['main.4']} />
        <mesh name="bumper_front_5_3" castShadow receiveShadow geometry={nodes.bumper_front_5_3.geometry} material={materials['skirts4.3']} />
        <mesh name="bumper_front_5_4" castShadow receiveShadow geometry={nodes.bumper_front_5_4.geometry} material={materials['spoiler5.1']} />
        <mesh name="bumper_front_5_5" castShadow receiveShadow geometry={nodes.bumper_front_5_5.geometry} material={materials['fenders_f0.5']} />
        <mesh name="bumper_front_5_6" castShadow receiveShadow geometry={nodes.bumper_front_5_6.geometry} material={materials['fenders_f0.4']} />
      </group>
      <group name="bumper_rear_1" position={[0, 0.897, 2.563]}>
        <mesh name="bumper_rear_1_1" castShadow receiveShadow geometry={nodes.bumper_rear_1_1.geometry} material={materials.primary} />
        <mesh name="bumper_rear_1_2" castShadow receiveShadow geometry={nodes.bumper_rear_1_2.geometry} material={materials['bumper_r0.1']} />
        <mesh name="bumper_rear_1_3" castShadow receiveShadow geometry={nodes.bumper_rear_1_3.geometry} material={materials['boot_ok.1']} />
        <mesh name="bumper_rear_1_4" castShadow receiveShadow geometry={nodes.bumper_rear_1_4.geometry} material={materials['bumper_r0.3']} />
        <mesh name="bumper_rear_1_5" castShadow receiveShadow geometry={nodes.bumper_rear_1_5.geometry} material={materials['chassis_vlo.1']} />
        <mesh name="bumper_rear_1_6" castShadow receiveShadow geometry={nodes.bumper_rear_1_6.geometry} material={materials['chassis_vlo.0']} />
      </group>
      <group name="bumper_rear_4" position={[0, -7.103, 2.563]}>
        <mesh name="bumper_rear_4_1" castShadow receiveShadow geometry={nodes.bumper_rear_4_1.geometry} material={materials.primary} />
        <mesh name="bumper_rear_4_2" castShadow receiveShadow geometry={nodes.bumper_rear_4_2.geometry} material={materials['boot_ok.1']} />
        <mesh name="bumper_rear_4_3" castShadow receiveShadow geometry={nodes.bumper_rear_4_3.geometry} material={materials['wheel.0']} />
        <mesh name="bumper_rear_4_4" castShadow receiveShadow geometry={nodes.bumper_rear_4_4.geometry} material={materials['chassis_vlo.1']} />
        <mesh name="bumper_rear_4_5" castShadow receiveShadow geometry={nodes.bumper_rear_4_5.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bumper_rear_4_6" castShadow receiveShadow geometry={nodes.bumper_rear_4_6.geometry} material={materials['bumper_r0.3']} />
        <mesh name="bumper_rear_4_7" castShadow receiveShadow geometry={nodes.bumper_rear_4_7.geometry} material={materials['bumper_r0.1']} />
      </group>
      <group name="bumper_rear_2" position={[0, -5.103, 2.563]}>
        <mesh name="bumper_rear_2_1" castShadow receiveShadow geometry={nodes.bumper_rear_2_1.geometry} material={materials['boot_ok.1']} />
        <mesh name="bumper_rear_2_2" castShadow receiveShadow geometry={nodes.bumper_rear_2_2.geometry} material={materials['chassis_vlo.1']} />
        <mesh name="bumper_rear_2_3" castShadow receiveShadow geometry={nodes.bumper_rear_2_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bumper_rear_2_4" castShadow receiveShadow geometry={nodes.bumper_rear_2_4.geometry} material={materials.primary} />
        <mesh name="bumper_rear_2_5" castShadow receiveShadow geometry={nodes.bumper_rear_2_5.geometry} material={materials['bumper_r0.3']} />
        <mesh name="bumper_rear_2_6" castShadow receiveShadow geometry={nodes.bumper_rear_2_6.geometry} material={materials['bumper_r0.1']} />
      </group>
      <group name="bumper_rear_6" position={[0, -9.103, 2.563]}>
        <mesh name="bumper_rear_6_1" castShadow receiveShadow geometry={nodes.bumper_rear_6_1.geometry} material={materials['boot_ok.1']} />
        <mesh name="bumper_rear_6_2" castShadow receiveShadow geometry={nodes.bumper_rear_6_2.geometry} material={materials['chassis_vlo.1']} />
        <mesh name="bumper_rear_6_3" castShadow receiveShadow geometry={nodes.bumper_rear_6_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bumper_rear_6_4" castShadow receiveShadow geometry={nodes.bumper_rear_6_4.geometry} material={materials.primary} />
        <mesh name="bumper_rear_6_5" castShadow receiveShadow geometry={nodes.bumper_rear_6_5.geometry} material={materials['bumper_r0.3']} />
        <mesh name="bumper_rear_6_6" castShadow receiveShadow geometry={nodes.bumper_rear_6_6.geometry} material={materials['bumper_r0.1']} />
      </group>
      <group name="bumper_rear_5" position={[0, -8.103, 2.563]}>
        <mesh name="bumper_rear_5_1" castShadow receiveShadow geometry={nodes.bumper_rear_5_1.geometry} material={materials.primary} />
        <mesh name="bumper_rear_5_2" castShadow receiveShadow geometry={nodes.bumper_rear_5_2.geometry} material={materials['skirts4.3']} />
        <mesh name="bumper_rear_5_3" castShadow receiveShadow geometry={nodes.bumper_rear_5_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name="bumper_rear_5_4" castShadow receiveShadow geometry={nodes.bumper_rear_5_4.geometry} material={materials['main.22']} />
        <mesh name="bumper_rear_5_5" castShadow receiveShadow geometry={nodes.bumper_rear_5_5.geometry} material={materials['boot_ok.1']} />
        <mesh name="bumper_rear_5_6" castShadow receiveShadow geometry={nodes.bumper_rear_5_6.geometry} material={materials['chassis_vlo.1']} />
        <mesh name="bumper_rear_5_7" castShadow receiveShadow geometry={nodes.bumper_rear_5_7.geometry} material={materials['bumper_r0.3']} />
        <mesh name="bumper_rear_5_8" castShadow receiveShadow geometry={nodes.bumper_rear_5_8.geometry} material={materials['bumper_r0.1']} />
      </group>
      <group name="bumper_rear_3" position={[0, -6.103, 2.563]}>
        <mesh name="bumper_rear_3_1" castShadow receiveShadow geometry={nodes.bumper_rear_3_1.geometry} material={materials.primary} />
        <mesh name="bumper_rear_3_2" castShadow receiveShadow geometry={nodes.bumper_rear_3_2.geometry} material={materials['main.4']} />
        <mesh name="bumper_rear_3_3" castShadow receiveShadow geometry={nodes.bumper_rear_3_3.geometry} material={materials['main.9']} />
        <mesh name="bumper_rear_3_4" castShadow receiveShadow geometry={nodes.bumper_rear_3_4.geometry} material={materials['chassis_vlo.0']} />
      </group>
      <mesh name="rear_glass" castShadow receiveShadow geometry={nodes.rear_glass.geometry} material={materials['glass.005']} position={[0, 1.355, -0.464]} />
      <mesh name="front_glass" castShadow receiveShadow geometry={nodes.front_glass.geometry} material={materials['glass.005']} position={[0, 1.355, -0.464]} />
      <mesh name="head_lights_glass" castShadow receiveShadow geometry={nodes.head_lights_glass.geometry} material={materials['glass.005']} position={[0, 1.04, -1.82]} />
      {/* <mesh name="dummy_bonnet" castShadow receiveShadow geometry={nodes.dummy_bonnet.geometry} material={nodes.dummy_bonnet.material} position={[0, 1.111, -0.769]} scale={0.1} />
      <mesh name="dummy_bumper_front" castShadow receiveShadow geometry={nodes.dummy_bumper_front.geometry} material={nodes.dummy_bumper_front.material} position={[0, 0.89, -2.338]} scale={0.1} />
      <mesh name="dummy_bumper_rear" castShadow receiveShadow geometry={nodes.dummy_bumper_rear.geometry} material={nodes.dummy_bumper_rear.material} position={[0, 0.897, 2.563]} scale={0.05} />
      <mesh name="dummu_diffuser" castShadow receiveShadow geometry={nodes.dummu_diffuser.geometry} material={nodes.dummu_diffuser.material} position={[0, 0.391, 2.641]} scale={0.05} />
      <mesh name="dummy_wings_front" castShadow receiveShadow geometry={nodes.dummy_wings_front.geometry} material={nodes.dummy_wings_front.material} position={[0, 1.108, -1.364]} scale={0.1} />
      <mesh name="dummy_trunk" castShadow receiveShadow geometry={nodes.dummy_trunk.geometry} material={nodes.dummy_trunk.material} position={[0, 1.203, 1.761]} scale={0.1} />
      <mesh name="dummy_skirts" castShadow receiveShadow geometry={nodes.dummy_skirts.geometry} material={nodes.dummy_skirts.material} position={[0.003, 0.405, -0.022]} scale={0.2} />
      <mesh name="dummy_head_lights" castShadow receiveShadow geometry={nodes.dummy_head_lights.geometry} material={nodes.dummy_head_lights.material} position={[0, 1.04, -1.82]} scale={0.1} />
      <mesh name="dummy_wings_rear" castShadow receiveShadow geometry={nodes.dummy_wings_rear.geometry} material={nodes.dummy_wings_rear.material} position={[0, 1.567, 0.906]} scale={0.1} />
      <mesh name="dummy_wheel_front_right" castShadow receiveShadow geometry={nodes.dummy_wheel_front_right.geometry} material={nodes.dummy_wheel_front_right.material} position={[0.844, 0.45, -1.37]} scale={0.1} />
      <mesh name="dummy_wheel_rear_right001" castShadow receiveShadow geometry={nodes.dummy_wheel_rear_right001.geometry} material={nodes.dummy_wheel_rear_right001.material} position={[0.844, 0.45, 1.561]} scale={0.1} />
      <mesh name="dummy_wheel_front_left" castShadow receiveShadow geometry={nodes.dummy_wheel_front_left.geometry} material={nodes.dummy_wheel_front_left.material} position={[-0.846, 0.45, -1.37]} scale={0.1} />
      <mesh name="dummy_wheel_rear_left" castShadow receiveShadow geometry={nodes.dummy_wheel_rear_left.geometry} material={nodes.dummy_wheel_rear_left.material} position={[-0.846, 0.45, 1.561]} scale={0.1} />
      <mesh name="dummy_door_front_right" castShadow receiveShadow geometry={nodes.dummy_door_front_right.geometry} material={nodes.dummy_door_front_right.material} position={[0.942, 0.781, -0.739]} scale={0.1} />
      <mesh name="dummy_door_front_left" castShadow receiveShadow geometry={nodes.dummy_door_front_left.geometry} material={nodes.dummy_door_front_left.material} position={[-0.944, 0.781, -0.739]} scale={0.1} /> */}
    </group>
  )
}

// useGLTF.preload('3d/gltf/cars/NissanSkylineGTRR34/nissan_skyline_gt_r34.gltf')
