/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./toyota_supra.gltf --types --shadows --keepmaterials --keepmeshes --keepnames 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    dummy_bumper_front: THREE.Mesh
    dummy_trunk: THREE.Mesh
    dummy_skirts: THREE.Mesh
    dummy_bonnet: THREE.Mesh
    dummy_head_lights: THREE.Mesh
    dummy_bumper_rear: THREE.Mesh
    dummy_tail_lights: THREE.Mesh
    dummy_door_front_right: THREE.Mesh
    dummy_door_front_left: THREE.Mesh
    dummy_wheel_front_right: THREE.Mesh
    dummy_wheel_rear_right: THREE.Mesh
    dummy_wheel_front_left: THREE.Mesh
    dummy_wheel_rear_left: THREE.Mesh
    wheel_1: THREE.Mesh
    wheel_2: THREE.Mesh
    wheel_3: THREE.Mesh
    wheel_4: THREE.Mesh
    tail_lights_2_1: THREE.Mesh
    tail_lights_2_2: THREE.Mesh
    tail_lights_2_3: THREE.Mesh
    tail_lights_2_4: THREE.Mesh
    tail_lights_2_5: THREE.Mesh
    tail_lights_2_6: THREE.Mesh
    tail_lights_2_7: THREE.Mesh
    tail_lights_1_1: THREE.Mesh
    tail_lights_1_2: THREE.Mesh
    tail_lights_1_3: THREE.Mesh
    tail_lights_1_4: THREE.Mesh
    tail_lights_1_5: THREE.Mesh
    spoiler_1: THREE.Mesh
    spoiler_2_1: THREE.Mesh
    spoiler_2_2: THREE.Mesh
    spoiler_3: THREE.Mesh
    skirts_3_1: THREE.Mesh
    skirts_3_2: THREE.Mesh
    skirts_2_1: THREE.Mesh
    skirts_2_2: THREE.Mesh
    skirts_1_1: THREE.Mesh
    skirts_1_2: THREE.Mesh
    bumper_rear_1_1: THREE.Mesh
    bumper_rear_1_2: THREE.Mesh
    bumper_rear_1_3: THREE.Mesh
    bumper_rear_2_1: THREE.Mesh
    bumper_rear_2_2: THREE.Mesh
    bumper_rear_2_3: THREE.Mesh
    bumper_rear_3_1: THREE.Mesh
    bumper_rear_3_2: THREE.Mesh
    bumper_rear_3_3: THREE.Mesh
    bumper_front_1_1: THREE.Mesh
    bumper_front_1_2: THREE.Mesh
    bumper_front_1_3: THREE.Mesh
    bumper_front_1_4: THREE.Mesh
    bumper_front_1_5: THREE.Mesh
    bumper_front_1_6: THREE.Mesh
    bumper_front_1_7: THREE.Mesh
    bumper_front_1_8: THREE.Mesh
    bumper_front_1_9: THREE.Mesh
    bumper_front_2_1: THREE.Mesh
    bumper_front_2_2: THREE.Mesh
    bumper_front_2_3: THREE.Mesh
    bumper_front_2_4: THREE.Mesh
    bumper_front_2_5: THREE.Mesh
    bumper_front_2_6: THREE.Mesh
    bumper_front_2_7: THREE.Mesh
    bumper_front_2_8: THREE.Mesh
    bumper_front_3_1: THREE.Mesh
    bumper_front_3_2: THREE.Mesh
    bumper_front_3_3: THREE.Mesh
    bumper_front_4_1: THREE.Mesh
    bumper_front_4_2: THREE.Mesh
    bumper_front_4_3: THREE.Mesh
    bonnet_1_1: THREE.Mesh
    bonnet_1_2: THREE.Mesh
    bonnet_1_3: THREE.Mesh
    chassis_1: THREE.Mesh
    chassis_2: THREE.Mesh
    chassis_3: THREE.Mesh
    chassis_4: THREE.Mesh
    chassis_5: THREE.Mesh
    chassis_6: THREE.Mesh
    chassis_7: THREE.Mesh
    chassis_8: THREE.Mesh
    alternate_tail_lights_1: THREE.Mesh
    interior_1: THREE.Mesh
    interior_2: THREE.Mesh
    interior_3: THREE.Mesh
    interior_4: THREE.Mesh
    interior_5: THREE.Mesh
    interior_6: THREE.Mesh
    interior_7: THREE.Mesh
    interior_8: THREE.Mesh
    interior_9: THREE.Mesh
    interior_10: THREE.Mesh
    interior_11: THREE.Mesh
    interior_12: THREE.Mesh
    seats: THREE.Mesh
    interior_gauges_1: THREE.Mesh
    interior_gauges_2: THREE.Mesh
    door_front_left_1: THREE.Mesh
    door_front_left_2: THREE.Mesh
    door_front_left_3: THREE.Mesh
    door_front_left_4: THREE.Mesh
    door_front_left_5: THREE.Mesh
    door_front_left_6: THREE.Mesh
    door_front_left_7: THREE.Mesh
    door_front_left_8: THREE.Mesh
    door_front_left_9: THREE.Mesh
    door_front_left_10: THREE.Mesh
    door_front_left_11: THREE.Mesh
    door_front_left_12: THREE.Mesh
    door_front_right_1: THREE.Mesh
    door_front_right_2: THREE.Mesh
    door_front_right_3: THREE.Mesh
    door_front_right_4: THREE.Mesh
    door_front_right_5: THREE.Mesh
    door_front_right_6: THREE.Mesh
    door_front_right_7: THREE.Mesh
    door_front_right_8: THREE.Mesh
    door_front_right_9: THREE.Mesh
    door_front_right_10: THREE.Mesh
    door_front_right_11: THREE.Mesh
    steeringwheel_1: THREE.Mesh
    steeringwheel_2: THREE.Mesh
    steeringwheel_3: THREE.Mesh
    windscreen: THREE.Mesh
    dashboard_values_1: THREE.Mesh
    dashboard_values_2: THREE.Mesh
    trunk_1: THREE.Mesh
    trunk_2: THREE.Mesh
    trunk_3: THREE.Mesh
    trunk_4: THREE.Mesh
    trunk_5: THREE.Mesh
    trunk_6: THREE.Mesh
    trunk_7: THREE.Mesh
    alternate_glass_1: THREE.Mesh
    head_lights_1_1: THREE.Mesh
    head_lights_1_2: THREE.Mesh
    head_lights_1_3: THREE.Mesh
    head_lights_glass: THREE.Mesh
    tail_lights_glass: THREE.Mesh
  }
  materials: {
    ['wheel.0']: THREE.MeshStandardMaterial
    ['wheel.1']: THREE.MeshStandardMaterial
    ['wheel.2']: THREE.MeshStandardMaterial
    ['wheel.3']: THREE.MeshStandardMaterial
    ['tail_lights1.0']: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    ['tail_lights1.2']: THREE.MeshStandardMaterial
    ['tail_lights1.3']: THREE.MeshStandardMaterial
    ['tail_lights1.4']: THREE.MeshStandardMaterial
    ['tail_lights1.5']: THREE.MeshStandardMaterial
    ['tail_lights1.6']: THREE.MeshStandardMaterial
    ['tail_lights0.4']: THREE.MeshStandardMaterial
    primary: THREE.MeshStandardMaterial
    ['spoiler2.0']: THREE.MeshStandardMaterial
    ['spoiler2.1']: THREE.MeshStandardMaterial
    ['skirts2.1']: THREE.MeshStandardMaterial
    ['bumper_r0.2']: THREE.MeshStandardMaterial
    ['bumper_f0.10']: THREE.MeshStandardMaterial
    ['bumper_f1.10']: THREE.MeshStandardMaterial
    ['primary.001']: THREE.MeshStandardMaterial
    ['chassis.5']: THREE.MeshStandardMaterial
    ['chassis.6']: THREE.MeshStandardMaterial
    ['chassis.7']: THREE.MeshStandardMaterial
    ['supra92_interior.5']: THREE.MeshStandardMaterial
    interior: THREE.MeshStandardMaterial
    ['supra92_interior.7']: THREE.MeshStandardMaterial
    ['supra92_interior.8']: THREE.MeshStandardMaterial
    ['supra92_interior.9']: THREE.MeshStandardMaterial
    ['supra92_interior.10']: THREE.MeshStandardMaterial
    ['supra92_interior.11']: THREE.MeshStandardMaterial
    ['supra92_seats.0']: THREE.MeshStandardMaterial
    ['door_lf_ok.9']: THREE.MeshStandardMaterial
    window_glass: THREE.MeshPhysicalMaterial
    ['glass.002']: THREE.MeshStandardMaterial
    ['odometr6.0']: THREE.MeshStandardMaterial
    ['bot.5']: THREE.MeshStandardMaterial
    ['right front light']: THREE.MeshStandardMaterial
    ['supra92_lights.5']: THREE.MeshStandardMaterial
    lights_glass: THREE.MeshPhysicalMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d/gltf/cars/ToyotaSupraMK4/toyota_supra.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} position={[0, .921, 0]}>

      {/* wheels */}
      <group name="wheel_front_right" position={[0.88, -0.326, -1.663]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.3']} />
      </group>
      <group name="wheel_front_left" position={[-0.88, -0.326, -1.663]} rotation={[0, Math.PI, 0]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.3']} />
      </group>
      <group name="wheel_rear_right" position={[0.88, -0.326, 1.26]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.3']} />
      </group>
      <group name="wheel_rear_left" position={[-0.88, -0.326, 1.26]} rotation={[0, Math.PI, 0]}>
        <mesh name="wheel_1" castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name="wheel_2" castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.1']} />
        <mesh name="wheel_3" castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials['wheel.2']} />
        <mesh name="wheel_4" castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.3']} />
      </group>

      <group name="tail_lights_2" position={[0, -5.729, 2.288]}>
        <mesh name="tail_lights_2_1" castShadow receiveShadow geometry={nodes.tail_lights_2_1.geometry} material={materials['tail_lights1.0']} />
        <mesh name="tail_lights_2_2" castShadow receiveShadow geometry={nodes.tail_lights_2_2.geometry} material={materials.glass} />
        <mesh name="tail_lights_2_3" castShadow receiveShadow geometry={nodes.tail_lights_2_3.geometry} material={materials['tail_lights1.2']} />
        <mesh name="tail_lights_2_4" castShadow receiveShadow geometry={nodes.tail_lights_2_4.geometry} material={materials['tail_lights1.3']} />
        <mesh name="tail_lights_2_5" castShadow receiveShadow geometry={nodes.tail_lights_2_5.geometry} material={materials['tail_lights1.4']} />
        <mesh name="tail_lights_2_6" castShadow receiveShadow geometry={nodes.tail_lights_2_6.geometry} material={materials['tail_lights1.5']} />
        <mesh name="tail_lights_2_7" castShadow receiveShadow geometry={nodes.tail_lights_2_7.geometry} material={materials['tail_lights1.6']} />
      </group>
      <group name="tail_lights_1" position={[0, 0.271, 2.288]}>
        <mesh name="tail_lights_1_1" castShadow receiveShadow geometry={nodes.tail_lights_1_1.geometry} material={materials['tail_lights1.3']} />
        <mesh name="tail_lights_1_2" castShadow receiveShadow geometry={nodes.tail_lights_1_2.geometry} material={materials['tail_lights1.4']} />
        <mesh name="tail_lights_1_3" castShadow receiveShadow geometry={nodes.tail_lights_1_3.geometry} material={materials['tail_lights1.5']} />
        <mesh name="tail_lights_1_4" castShadow receiveShadow geometry={nodes.tail_lights_1_4.geometry} material={materials['tail_lights1.6']} />
        <mesh name="tail_lights_1_5" castShadow receiveShadow geometry={nodes.tail_lights_1_5.geometry} material={materials['tail_lights0.4']} />
      </group>
      <mesh name="spoiler_1" castShadow receiveShadow geometry={nodes.spoiler_1.geometry} material={materials.primary} position={[0, 0.73, 0.759]} />
      <group name="spoiler_2" position={[0, -1.27, 0.759]}>
        <mesh name="spoiler_2_1" castShadow receiveShadow geometry={nodes.spoiler_2_1.geometry} material={materials['spoiler2.0']} />
        <mesh name="spoiler_2_2" castShadow receiveShadow geometry={nodes.spoiler_2_2.geometry} material={materials['spoiler2.1']} />
      </group>
      <mesh name="spoiler_3" castShadow receiveShadow geometry={nodes.spoiler_3.geometry} material={materials['spoiler2.1']} position={[0, -2.27, 0.759]} />
      <group name="skirts_3" position={[0, -5.301, 0.463]}>
        <mesh name="skirts_3_1" castShadow receiveShadow geometry={nodes.skirts_3_1.geometry} material={materials.primary} />
        <mesh name="skirts_3_2" castShadow receiveShadow geometry={nodes.skirts_3_2.geometry} material={materials['skirts2.1']} />
      </group>
      <group name="skirts_2" position={[0, -4.301, 0.463]}>
        <mesh name="skirts_2_1" castShadow receiveShadow geometry={nodes.skirts_2_1.geometry} material={materials.primary} />
        <mesh name="skirts_2_2" castShadow receiveShadow geometry={nodes.skirts_2_2.geometry} material={materials['skirts2.1']} />
      </group>
      <group name="skirts_1" position={[0, -0.301, 0.463]}>
        <mesh name="skirts_1_1" castShadow receiveShadow geometry={nodes.skirts_1_1.geometry} material={materials.primary} />
        <mesh name="skirts_1_2" castShadow receiveShadow geometry={nodes.skirts_1_2.geometry} material={materials['skirts2.1']} />
      </group>
      <group name="bumper_rear_1" position={[0, -0.033, 2.242]}>
        <mesh name="bumper_rear_1_1" castShadow receiveShadow geometry={nodes.bumper_rear_1_1.geometry} material={materials.primary} />
        <mesh name="bumper_rear_1_2" castShadow receiveShadow geometry={nodes.bumper_rear_1_2.geometry} material={materials['spoiler2.1']} />
        <mesh name="bumper_rear_1_3" castShadow receiveShadow geometry={nodes.bumper_rear_1_3.geometry} material={materials['bumper_r0.2']} />
      </group>
      <group name="bumper_rear_2" position={[0, -3.803, 2.338]}>
        <mesh name="bumper_rear_2_1" castShadow receiveShadow geometry={nodes.bumper_rear_2_1.geometry} material={materials.primary} />
        <mesh name="bumper_rear_2_2" castShadow receiveShadow geometry={nodes.bumper_rear_2_2.geometry} material={materials['spoiler2.1']} />
        <mesh name="bumper_rear_2_3" castShadow receiveShadow geometry={nodes.bumper_rear_2_3.geometry} material={materials['bumper_r0.2']} />
      </group>
      <group name="bumper_rear_3" position={[0, -4.803, 2.338]}>
        <mesh name="bumper_rear_3_1" castShadow receiveShadow geometry={nodes.bumper_rear_3_1.geometry} material={materials.primary} />
        <mesh name="bumper_rear_3_2" castShadow receiveShadow geometry={nodes.bumper_rear_3_2.geometry} material={materials['spoiler2.1']} />
        <mesh name="bumper_rear_3_3" castShadow receiveShadow geometry={nodes.bumper_rear_3_3.geometry} material={materials['bumper_r0.2']} />
      </group>
      <group name="bumper_front_1" position={[-0.007, -0.092, -2.742]}>
        <mesh name="bumper_front_1_1" castShadow receiveShadow geometry={nodes.bumper_front_1_1.geometry} material={materials['tail_lights1.2']} />
        <mesh name="bumper_front_1_2" castShadow receiveShadow geometry={nodes.bumper_front_1_2.geometry} material={materials['tail_lights1.5']} />
        <mesh name="bumper_front_1_3" castShadow receiveShadow geometry={nodes.bumper_front_1_3.geometry} material={materials['tail_lights1.6']} />
        <mesh name="bumper_front_1_4" castShadow receiveShadow geometry={nodes.bumper_front_1_4.geometry} material={materials.primary} />
        <mesh name="bumper_front_1_5" castShadow receiveShadow geometry={nodes.bumper_front_1_5.geometry} material={materials['spoiler2.0']} />
        <mesh name="bumper_front_1_6" castShadow receiveShadow geometry={nodes.bumper_front_1_6.geometry} material={materials['spoiler2.1']} />
        <mesh name="bumper_front_1_7" castShadow receiveShadow geometry={nodes.bumper_front_1_7.geometry} material={materials['skirts2.1']} />
        <mesh name="bumper_front_1_8" castShadow receiveShadow geometry={nodes.bumper_front_1_8.geometry} material={materials['bumper_r0.2']} />
        <mesh name="bumper_front_1_9" castShadow receiveShadow geometry={nodes.bumper_front_1_9.geometry} material={materials['bumper_f0.10']} />
      </group>
      <group name="bumper_front_2" position={[-0.007, -4.092, -2.742]}>
        <mesh name="bumper_front_2_1" castShadow receiveShadow geometry={nodes.bumper_front_2_1.geometry} material={materials['tail_lights1.5']} />
        <mesh name="bumper_front_2_2" castShadow receiveShadow geometry={nodes.bumper_front_2_2.geometry} material={materials['tail_lights1.6']} />
        <mesh name="bumper_front_2_3" castShadow receiveShadow geometry={nodes.bumper_front_2_3.geometry} material={materials['tail_lights0.4']} />
        <mesh name="bumper_front_2_4" castShadow receiveShadow geometry={nodes.bumper_front_2_4.geometry} material={materials.primary} />
        <mesh name="bumper_front_2_5" castShadow receiveShadow geometry={nodes.bumper_front_2_5.geometry} material={materials['spoiler2.1']} />
        <mesh name="bumper_front_2_6" castShadow receiveShadow geometry={nodes.bumper_front_2_6.geometry} material={materials['skirts2.1']} />
        <mesh name="bumper_front_2_7" castShadow receiveShadow geometry={nodes.bumper_front_2_7.geometry} material={materials['bumper_f0.10']} />
        <mesh name="bumper_front_2_8" castShadow receiveShadow geometry={nodes.bumper_front_2_8.geometry} material={materials['bumper_f1.10']} />
      </group>
      <group name="bumper_front_3" position={[-0.007, -5.092, -2.742]}>
        <mesh name="bumper_front_3_1" castShadow receiveShadow geometry={nodes.bumper_front_3_1.geometry} material={materials.primary} />
        <mesh name="bumper_front_3_2" castShadow receiveShadow geometry={nodes.bumper_front_3_2.geometry} material={materials['spoiler2.1']} />
        <mesh name="bumper_front_3_3" castShadow receiveShadow geometry={nodes.bumper_front_3_3.geometry} material={materials['bumper_f1.10']} />
      </group>
      <group name="bumper_front_4" position={[-0.007, -6.092, -2.742]}>
        <mesh name="bumper_front_4_1" castShadow receiveShadow geometry={nodes.bumper_front_4_1.geometry} material={materials['tail_lights1.5']} />
        <mesh name="bumper_front_4_2" castShadow receiveShadow geometry={nodes.bumper_front_4_2.geometry} material={materials['tail_lights1.6']} />
        <mesh name="bumper_front_4_3" castShadow receiveShadow geometry={nodes.bumper_front_4_3.geometry} material={materials.primary} />
      </group>
      <group name="bonnet_1" position={[0, 0.321, -0.888]}>
        <mesh name="bonnet_1_1" castShadow receiveShadow geometry={nodes.bonnet_1_1.geometry} material={materials.primary} />
        <mesh name="bonnet_1_2" castShadow receiveShadow geometry={nodes.bonnet_1_2.geometry} material={materials['bumper_f0.10']} />
        <mesh name="bonnet_1_3" castShadow receiveShadow geometry={nodes.bonnet_1_3.geometry} material={materials['primary.001']} />
      </group>
      <mesh name="alternate_tail_lights_1" castShadow receiveShadow geometry={nodes.alternate_tail_lights_1.geometry} material={materials['tail_lights1.5']} />
      <mesh name="seats" castShadow receiveShadow geometry={nodes.seats.geometry} material={materials['supra92_seats.0']} />
      <group name="door_front_left" position={[-1.018, 0.004, -0.905]}>
        <mesh name="door_front_left_1" castShadow receiveShadow geometry={nodes.door_front_left_1.geometry} material={materials.primary} />
        <mesh name="door_front_left_2" castShadow receiveShadow geometry={nodes.door_front_left_2.geometry} material={materials['spoiler2.0']} />
        <mesh name="door_front_left_3" castShadow receiveShadow geometry={nodes.door_front_left_3.geometry} material={materials['skirts2.1']} />
        <mesh name="door_front_left_4" castShadow receiveShadow geometry={nodes.door_front_left_4.geometry} material={materials['bumper_f0.10']} />
        <mesh name="door_front_left_5" castShadow receiveShadow geometry={nodes.door_front_left_5.geometry} material={materials['bumper_f1.10']} />
        <mesh name="door_front_left_6" castShadow receiveShadow geometry={nodes.door_front_left_6.geometry} material={materials.interior} />
        <mesh name="door_front_left_7" castShadow receiveShadow geometry={nodes.door_front_left_7.geometry} material={materials['supra92_interior.7']} />
        <mesh name="door_front_left_8" castShadow receiveShadow geometry={nodes.door_front_left_8.geometry} material={materials['supra92_interior.8']} />
        <mesh name="door_front_left_9" castShadow receiveShadow geometry={nodes.door_front_left_9.geometry} material={materials['supra92_interior.10']} />
        <mesh name="door_front_left_10" castShadow receiveShadow geometry={nodes.door_front_left_10.geometry} material={materials['door_lf_ok.9']} />
        <mesh name="door_front_left_11" castShadow receiveShadow geometry={nodes.door_front_left_11.geometry} material={materials.window_glass} />
        <mesh name="door_front_left_12" castShadow receiveShadow geometry={nodes.door_front_left_12.geometry} material={materials['glass.002']} />
      </group>
      <group name="door_front_right" position={[1.018, 0.004, -0.905]}>
        <mesh name="door_front_right_1" castShadow receiveShadow geometry={nodes.door_front_right_1.geometry} material={materials.primary} />
        <mesh name="door_front_right_2" castShadow receiveShadow geometry={nodes.door_front_right_2.geometry} material={materials['spoiler2.0']} />
        <mesh name="door_front_right_3" castShadow receiveShadow geometry={nodes.door_front_right_3.geometry} material={materials['skirts2.1']} />
        <mesh name="door_front_right_4" castShadow receiveShadow geometry={nodes.door_front_right_4.geometry} material={materials['bumper_f0.10']} />
        <mesh name="door_front_right_5" castShadow receiveShadow geometry={nodes.door_front_right_5.geometry} material={materials['bumper_f1.10']} />
        <mesh name="door_front_right_6" castShadow receiveShadow geometry={nodes.door_front_right_6.geometry} material={materials.interior} />
        <mesh name="door_front_right_7" castShadow receiveShadow geometry={nodes.door_front_right_7.geometry} material={materials['supra92_interior.7']} />
        <mesh name="door_front_right_8" castShadow receiveShadow geometry={nodes.door_front_right_8.geometry} material={materials['supra92_interior.8']} />
        <mesh name="door_front_right_9" castShadow receiveShadow geometry={nodes.door_front_right_9.geometry} material={materials['door_lf_ok.9']} />
        <mesh name="door_front_right_10" castShadow receiveShadow geometry={nodes.door_front_right_10.geometry} material={materials.window_glass} />
        <mesh name="door_front_right_11" castShadow receiveShadow geometry={nodes.door_front_right_11.geometry} material={materials['glass.002']} />
      </group>
      <group name="steeringwheel" position={[-0.388, 0.185, -0.428]} rotation={[-0.32, 0, 0]}>
        <mesh name="steeringwheel_1" castShadow receiveShadow geometry={nodes.steeringwheel_1.geometry} material={materials['spoiler2.0']} />
        <mesh name="steeringwheel_2" castShadow receiveShadow geometry={nodes.steeringwheel_2.geometry} material={materials['supra92_interior.7']} />
        <mesh name="steeringwheel_3" castShadow receiveShadow geometry={nodes.steeringwheel_3.geometry} material={materials['supra92_interior.8']} />
      </group>
      <mesh name="windscreen" castShadow receiveShadow geometry={nodes.windscreen.geometry} material={materials.window_glass} position={[0, 0.504, -0.668]} />
      <group name="dashboard_values" position={[-0.522, 0.265, -0.629]} rotation={[-0.2, 0, 0]}>
        <mesh name="dashboard_values_1" castShadow receiveShadow geometry={nodes.dashboard_values_1.geometry} material={materials.interior} />
        <mesh name="dashboard_values_2" castShadow receiveShadow geometry={nodes.dashboard_values_2.geometry} material={materials['odometr6.0']} />
      </group>
      <group name="trunk" position={[0, 0.73, 0.759]}>
        <mesh name="trunk_1" castShadow receiveShadow geometry={nodes.trunk_1.geometry} material={materials['tail_lights1.0']} />
        <mesh name="trunk_2" castShadow receiveShadow geometry={nodes.trunk_2.geometry} material={materials.primary} />
        <mesh name="trunk_3" castShadow receiveShadow geometry={nodes.trunk_3.geometry} material={materials['skirts2.1']} />
        <mesh name="trunk_4" castShadow receiveShadow geometry={nodes.trunk_4.geometry} material={materials['bumper_f0.10']} />
        <mesh name="trunk_5" castShadow receiveShadow geometry={nodes.trunk_5.geometry} material={materials['supra92_interior.5']} />
        <mesh name="trunk_6" castShadow receiveShadow geometry={nodes.trunk_6.geometry} material={materials['bot.5']} />
        <mesh name="trunk_7" castShadow receiveShadow geometry={nodes.trunk_7.geometry} material={materials.window_glass} />
      </group>
      <mesh name="alternate_glass_1" castShadow receiveShadow geometry={nodes.alternate_glass_1.geometry} material={materials.window_glass} />
      <group name="head_lights_1" position={[0, 0.134, -2.386]}>
        <mesh name="head_lights_1_1" castShadow receiveShadow geometry={nodes.head_lights_1_1.geometry} material={materials['tail_lights0.4']} />
        <mesh name="head_lights_1_2" castShadow receiveShadow geometry={nodes.head_lights_1_2.geometry} material={materials['right front light']} />
        <mesh name="head_lights_1_3" castShadow receiveShadow geometry={nodes.head_lights_1_3.geometry} material={materials['supra92_lights.5']} />
      </group>
      <mesh name="head_lights_glass" castShadow receiveShadow geometry={nodes.head_lights_glass.geometry} material={materials.lights_glass} position={[0, 0.134, -2.386]} />
      <mesh name="tail_lights_glass" castShadow receiveShadow geometry={nodes.tail_lights_glass.geometry} material={materials.window_glass} position={[0, 0.271, 2.288]} />
      <mesh name="chassis_1" castShadow receiveShadow geometry={nodes.chassis_1.geometry} material={materials['tail_lights1.0']} />
      <mesh name="chassis_2" castShadow receiveShadow geometry={nodes.chassis_2.geometry} material={materials.primary} />
      <mesh name="chassis_3" castShadow receiveShadow geometry={nodes.chassis_3.geometry} material={materials['spoiler2.1']} />
      <mesh name="chassis_4" castShadow receiveShadow geometry={nodes.chassis_4.geometry} material={materials['skirts2.1']} />
      <mesh name="chassis_5" castShadow receiveShadow geometry={nodes.chassis_5.geometry} material={materials['bumper_f0.10']} />
      <mesh name="chassis_6" castShadow receiveShadow geometry={nodes.chassis_6.geometry} material={materials['chassis.5']} />
      <mesh name="chassis_7" castShadow receiveShadow geometry={nodes.chassis_7.geometry} material={materials['chassis.6']} />
      <mesh name="chassis_8" castShadow receiveShadow geometry={nodes.chassis_8.geometry} material={materials['chassis.7']} />
      <mesh name="interior_1" castShadow receiveShadow geometry={nodes.interior_1.geometry} material={materials.primary} />
      <mesh name="interior_2" castShadow receiveShadow geometry={nodes.interior_2.geometry} material={materials['spoiler2.0']} />
      <mesh name="interior_3" castShadow receiveShadow geometry={nodes.interior_3.geometry} material={materials['skirts2.1']} />
      <mesh name="interior_4" castShadow receiveShadow geometry={nodes.interior_4.geometry} material={materials['bumper_f0.10']} />
      <mesh name="interior_5" castShadow receiveShadow geometry={nodes.interior_5.geometry} material={materials['bumper_f1.10']} />
      <mesh name="interior_6" castShadow receiveShadow geometry={nodes.interior_6.geometry} material={materials['supra92_interior.5']} />
      <mesh name="interior_7" castShadow receiveShadow geometry={nodes.interior_7.geometry} material={materials.interior} />
      <mesh name="interior_8" castShadow receiveShadow geometry={nodes.interior_8.geometry} material={materials['supra92_interior.7']} />
      <mesh name="interior_9" castShadow receiveShadow geometry={nodes.interior_9.geometry} material={materials['supra92_interior.8']} />
      <mesh name="interior_10" castShadow receiveShadow geometry={nodes.interior_10.geometry} material={materials['supra92_interior.9']} />
      <mesh name="interior_11" castShadow receiveShadow geometry={nodes.interior_11.geometry} material={materials['supra92_interior.10']} />
      <mesh name="interior_12" castShadow receiveShadow geometry={nodes.interior_12.geometry} material={materials['supra92_interior.11']} />
      <mesh name="interior_gauges_1" castShadow receiveShadow geometry={nodes.interior_gauges_1.geometry} material={materials.interior} />
      <mesh name="interior_gauges_2" castShadow receiveShadow geometry={nodes.interior_gauges_2.geometry} material={materials['supra92_interior.10']} />
      {/* <mesh name="dummy_bumper_front" castShadow receiveShadow geometry={nodes.dummy_bumper_front.geometry} material={nodes.dummy_bumper_front.material} position={[-0.007, -0.092, -2.742]} scale={0.1} />
      <mesh name="dummy_trunk" castShadow receiveShadow geometry={nodes.dummy_trunk.geometry} material={nodes.dummy_trunk.material} position={[0, 0.73, 0.759]} scale={0.1} />
      <mesh name="dummy_skirts" castShadow receiveShadow geometry={nodes.dummy_skirts.geometry} material={nodes.dummy_skirts.material} position={[0, -0.301, 0.463]} scale={0.3} />
      <mesh name="dummy_bonnet" castShadow receiveShadow geometry={nodes.dummy_bonnet.geometry} material={nodes.dummy_bonnet.material} position={[0, 0.321, -0.888]} scale={0.1} />
      <mesh name="dummy_head_lights" castShadow receiveShadow geometry={nodes.dummy_head_lights.geometry} material={nodes.dummy_head_lights.material} position={[0, 0.134, -2.386]} scale={0.05} />
      <mesh name="dummy_bumper_rear" castShadow receiveShadow geometry={nodes.dummy_bumper_rear.geometry} material={nodes.dummy_bumper_rear.material} position={[0, 0.197, 2.338]} scale={0.05} />
      <mesh name="dummy_tail_lights" castShadow receiveShadow geometry={nodes.dummy_tail_lights.geometry} material={nodes.dummy_tail_lights.material} position={[0, 0.271, 2.288]} scale={0.05} />
      <mesh name="dummy_door_front_right" castShadow receiveShadow geometry={nodes.dummy_door_front_right.geometry} material={nodes.dummy_door_front_right.material} position={[1.018, 0.004, -0.905]} scale={0.1} />
      <mesh name="dummy_door_front_left" castShadow receiveShadow geometry={nodes.dummy_door_front_left.geometry} material={nodes.dummy_door_front_left.material} position={[-1.018, 0.004, -0.905]} scale={0.1} />
      <mesh name="dummy_wheel_front_right" castShadow receiveShadow geometry={nodes.dummy_wheel_front_right.geometry} material={nodes.dummy_wheel_front_right.material} position={[0.858, -0.326, -1.663]} scale={0.2} />
      <mesh name="dummy_wheel_rear_right" castShadow receiveShadow geometry={nodes.dummy_wheel_rear_right.geometry} material={nodes.dummy_wheel_rear_right.material} position={[0.858, -0.326, 1.257]} scale={0.2} />
      <mesh name="dummy_wheel_front_left" castShadow receiveShadow geometry={nodes.dummy_wheel_front_left.geometry} material={nodes.dummy_wheel_front_left.material} position={[-0.856, -0.326, -1.663]} scale={0.2} />
      <mesh name="dummy_wheel_rear_left" castShadow receiveShadow geometry={nodes.dummy_wheel_rear_left.geometry} material={nodes.dummy_wheel_rear_left.material} position={[-0.856, -0.326, 1.257]} scale={0.2} /> */}
    </group>
  )
}

// useGLTF.preload('/3d/gltf/cars/ToyotaSupraMK4/toyota_supra.gltf')
