/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./audi_a8.gltf --types --transform --shadows --keepnames --keepmeshes --keepmaterials 
Files: ./audi_a8.gltf [206.05KB] > audi_a8-transformed.glb [1.55MB] (-652%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { degToRad } from 'three/src/math/MathUtils'
import { Euler, Vector3 } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    door_rf001: THREE.Mesh
    door_rf001_1: THREE.Mesh
    door_rf001_2: THREE.Mesh
    door_rf001_3: THREE.Mesh
    door_rf001_4: THREE.Mesh
    door_rf001_5: THREE.Mesh
    door_lf001: THREE.Mesh
    door_lf001_1: THREE.Mesh
    door_lf001_2: THREE.Mesh
    door_lf001_3: THREE.Mesh
    door_lf001_4: THREE.Mesh
    door_lf001_5: THREE.Mesh
    door_lr001: THREE.Mesh
    door_lr001_1: THREE.Mesh
    door_lr001_2: THREE.Mesh
    door_lr001_3: THREE.Mesh
    door_lr001_4: THREE.Mesh
    door_rr001: THREE.Mesh
    door_rr001_1: THREE.Mesh
    door_rr001_2: THREE.Mesh
    door_rr001_3: THREE.Mesh
    door_rr001_4: THREE.Mesh
    head_lights0001: THREE.Mesh
    head_lights0001_1: THREE.Mesh
    head_lights0001_2: THREE.Mesh
    head_lights0001_3: THREE.Mesh
    head_lights0001_4: THREE.Mesh
    head_lights0001_5: THREE.Mesh
    head_lights0001_6: THREE.Mesh
    head_lights0001_7: THREE.Mesh
    head_lights0001_8: THREE.Mesh
    head_lights0001_9: THREE.Mesh
    head_lights0001_10: THREE.Mesh
    head_lights1001: THREE.Mesh
    head_lights1001_1: THREE.Mesh
    head_lights1001_2: THREE.Mesh
    head_lights1001_3: THREE.Mesh
    head_lights1001_4: THREE.Mesh
    head_lights1001_5: THREE.Mesh
    head_lights1001_6: THREE.Mesh
    head_lights1001_7: THREE.Mesh
    bodyshell001: THREE.Mesh
    bodyshell001_1: THREE.Mesh
    bodyshell001_2: THREE.Mesh
    bodyshell001_3: THREE.Mesh
    bodyshell001_4: THREE.Mesh
    bodyshell001_5: THREE.Mesh
    bodyshell001_6: THREE.Mesh
    glass_rear: THREE.Mesh
    bumper_f0001: THREE.Mesh
    bumper_f0001_1: THREE.Mesh
    bumper_f0001_2: THREE.Mesh
    bumper_f0001_3: THREE.Mesh
    bumper_f0001_4: THREE.Mesh
    bumper_f0001_5: THREE.Mesh
    bumper_f0001_6: THREE.Mesh
    bumper_f1001: THREE.Mesh
    bumper_f1001_1: THREE.Mesh
    bumper_f1001_2: THREE.Mesh
    bumper_f1001_3: THREE.Mesh
    bumper_f1001_4: THREE.Mesh
    bumper_f1001_5: THREE.Mesh
    bumper_f1001_6: THREE.Mesh
    bumper_f1001_7: THREE.Mesh
    trunk1001: THREE.Mesh
    trunk1001_1: THREE.Mesh
    trunk1001_2: THREE.Mesh
    trunk1001_3: THREE.Mesh
    trunk1001_4: THREE.Mesh
    trunk1001_5: THREE.Mesh
    trunk1001_6: THREE.Mesh
    trunk1001_7: THREE.Mesh
    trunk1001_8: THREE.Mesh
    trunk1001_9: THREE.Mesh
    trunk0001: THREE.Mesh
    trunk0001_1: THREE.Mesh
    trunk0001_2: THREE.Mesh
    trunk0001_3: THREE.Mesh
    trunk0001_4: THREE.Mesh
    trunk0001_5: THREE.Mesh
    trunk0001_6: THREE.Mesh
    trunk0001_7: THREE.Mesh
    trunk0001_8: THREE.Mesh
    trunk0001_9: THREE.Mesh
    trunk0001_10: THREE.Mesh
    trunk0001_11: THREE.Mesh
    trunk0001_12: THREE.Mesh
    bonnet_2: THREE.Mesh
    bonnet0001: THREE.Mesh
    bonnet0001_1: THREE.Mesh
    wings_front_1: THREE.Mesh
    bumper_r0001: THREE.Mesh
    bumper_r0001_1: THREE.Mesh
    bumper_r0001_2: THREE.Mesh
    bumper_r0001_3: THREE.Mesh
    bumper_r0001_4: THREE.Mesh
    bumper_r1001: THREE.Mesh
    bumper_r1001_1: THREE.Mesh
    bumper_r1001_2: THREE.Mesh
    bumper_r1001_3: THREE.Mesh
    glass_front: THREE.Mesh
    wings_front_2: THREE.Mesh
    tail_lights0001: THREE.Mesh
    tail_lights0001_1: THREE.Mesh
    tail_lights0001_2: THREE.Mesh
    tail_lights0001_3: THREE.Mesh
    tail_lights0001_4: THREE.Mesh
    tail_lights0001_5: THREE.Mesh
    tail_lights0001_6: THREE.Mesh
    tail_lights0001_7: THREE.Mesh
    tail_lights1001: THREE.Mesh
    tail_lights1001_1: THREE.Mesh
    tail_lights1001_2: THREE.Mesh
    tail_lights1001_3: THREE.Mesh
    tail_lights1001_4: THREE.Mesh
    tail_lights1001_5: THREE.Mesh
    tail_lights1001_6: THREE.Mesh
    tail_lights1001_7: THREE.Mesh
    wheel001: THREE.Mesh
    wheel001_1: THREE.Mesh
    wheel001_2: THREE.Mesh
    wheel004: THREE.Mesh
    wheel004_1: THREE.Mesh
    wheel004_2: THREE.Mesh
    glass_door_front_right: THREE.Mesh
    glass_door_front_left: THREE.Mesh
    glass_door_rear_left: THREE.Mesh
    glass_door_rear_right: THREE.Mesh
    engine001: THREE.Mesh
    engine001_1: THREE.Mesh
    engine001_2: THREE.Mesh
    engine001_3: THREE.Mesh
    engine001_4: THREE.Mesh
    Interior002_1: THREE.Mesh
    Interior002_2: THREE.Mesh
    Interior002_3: THREE.Mesh
    Interior002_4: THREE.Mesh
    Interior002_5: THREE.Mesh
    Interior002_6: THREE.Mesh
    Interior002_7: THREE.Mesh
    Interior002_8: THREE.Mesh
    Interior002_9: THREE.Mesh
    Interior003: THREE.Mesh
  }
  materials: {
    primary: THREE.MeshPhysicalMaterial
    ['door_rf.004']: THREE.MeshStandardMaterial
    ['door_rf.006']: THREE.MeshStandardMaterial
    ['door_rf.007']: THREE.MeshStandardMaterial
    ['secondary.004']: THREE.MeshStandardMaterial
    ['door_rf.008']: THREE.MeshStandardMaterial
    ['head_lights0.001']: THREE.MeshStandardMaterial
    ['head_lights0.002']: THREE.MeshStandardMaterial
    ['right front light.001']: THREE.MeshStandardMaterial
    ['glass.008']: THREE.MeshStandardMaterial
    ['glass.009']: THREE.MeshStandardMaterial
    ['head_lights0.005']: THREE.MeshStandardMaterial
    glass_windows: THREE.MeshStandardMaterial
    ['head_lights1.001']: THREE.MeshStandardMaterial
    ['head_lights1.002']: THREE.MeshStandardMaterial
    ['bodyshell.001']: THREE.MeshStandardMaterial
    ['bodyshell.002']: THREE.MeshStandardMaterial
    ['bumper_f0.001']: THREE.MeshStandardMaterial
    ['bumper_f1.002']: THREE.MeshStandardMaterial
    ['door_lf.001']: THREE.MeshStandardMaterial
    ['secondary.005']: THREE.MeshStandardMaterial
    ['left rear light.001']: THREE.MeshStandardMaterial
    glass_rear_lights: THREE.MeshStandardMaterial
    ['trunk1.001']: THREE.MeshStandardMaterial
    glass_back_lights: THREE.MeshStandardMaterial
    ['trunk0.002']: THREE.MeshStandardMaterial
    ['trunk0.003']: THREE.MeshStandardMaterial
    ['primary.005']: THREE.MeshStandardMaterial
    ['Interior.001']: THREE.MeshStandardMaterial
    ['bumper_f0.002']: THREE.MeshStandardMaterial
    ['wheel.003']: THREE.MeshStandardMaterial
    ['wheel.004']: THREE.MeshStandardMaterial
    ['engine.001']: THREE.MeshStandardMaterial
    ['engine.002']: THREE.MeshStandardMaterial
    ['secondary.006']: THREE.MeshStandardMaterial
    ['Interior.002']: THREE.MeshStandardMaterial
    ['secondary.007']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const [defaultCarProps] = React.useState({
    position: [0, 1.1, 0] as Vector3,
    rotation: [degToRad(0), degToRad(-135), degToRad(0)] as Euler,
    scale: 1,
    materials: {
      primary: {
        color: new THREE.Color('#7f7f7f'),
        metalness: 0.3,
        roughness: 1,
        clearcoat: 0.05,
        specularIntensity: 0,
      },
    },
  })

  React.useEffect(() => {
    materials.primary.color = defaultCarProps.materials['primary'].color
    materials.primary.metalness = defaultCarProps.materials['primary'].metalness
    materials.primary.roughness = defaultCarProps.materials['primary'].roughness
    materials.primary.clearcoat = defaultCarProps.materials['primary'].clearcoat
    materials.primary.specularIntensity = defaultCarProps.materials['primary'].specularIntensity
  }, [])

  const { nodes, materials } = useGLTF('assets/3d/transformed_gltf/cars/audi/A8/audi_a8-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null} position={defaultCarProps.position} rotation={defaultCarProps.rotation} scale={defaultCarProps.scale}>
      <group name='door_front_right_1' position={[1.021, -0.217, -1.041]}>
        <mesh name='door_rf001' castShadow receiveShadow geometry={nodes.door_rf001.geometry} material={materials.primary} />
        <mesh name='door_rf001_1' castShadow receiveShadow geometry={nodes.door_rf001_1.geometry} material={materials['door_rf.004']} />
        <mesh name='door_rf001_2' castShadow receiveShadow geometry={nodes.door_rf001_2.geometry} material={materials['door_rf.006']} />
        <mesh name='door_rf001_3' castShadow receiveShadow geometry={nodes.door_rf001_3.geometry} material={materials['door_rf.007']} />
        <mesh name='door_rf001_4' castShadow receiveShadow geometry={nodes.door_rf001_4.geometry} material={materials['secondary.004']} />
        <mesh name='door_rf001_5' castShadow receiveShadow geometry={nodes.door_rf001_5.geometry} material={materials['door_rf.008']} />
      </group>
      <group name='door_front_left_1' position={[-1.008, -0.222, -1.037]}>
        <mesh name='door_lf001' castShadow receiveShadow geometry={nodes.door_lf001.geometry} material={materials.primary} />
        <mesh name='door_lf001_1' castShadow receiveShadow geometry={nodes.door_lf001_1.geometry} material={materials['door_rf.004']} />
        <mesh name='door_lf001_2' castShadow receiveShadow geometry={nodes.door_lf001_2.geometry} material={materials['door_rf.006']} />
        <mesh name='door_lf001_3' castShadow receiveShadow geometry={nodes.door_lf001_3.geometry} material={materials['door_rf.007']} />
        <mesh name='door_lf001_4' castShadow receiveShadow geometry={nodes.door_lf001_4.geometry} material={materials['secondary.004']} />
        <mesh name='door_lf001_5' castShadow receiveShadow geometry={nodes.door_lf001_5.geometry} material={materials['door_rf.008']} />
      </group>
      <group name='door_rear_left_1' position={[-1.025, -0.145, 0.205]}>
        <mesh name='door_lr001' castShadow receiveShadow geometry={nodes.door_lr001.geometry} material={materials.primary} />
        <mesh name='door_lr001_1' castShadow receiveShadow geometry={nodes.door_lr001_1.geometry} material={materials['door_rf.004']} />
        <mesh name='door_lr001_2' castShadow receiveShadow geometry={nodes.door_lr001_2.geometry} material={materials['door_rf.006']} />
        <mesh name='door_lr001_3' castShadow receiveShadow geometry={nodes.door_lr001_3.geometry} material={materials['door_rf.007']} />
        <mesh name='door_lr001_4' castShadow receiveShadow geometry={nodes.door_lr001_4.geometry} material={materials['secondary.004']} />
      </group>
      <group name='door_rear_right_1' position={[1.026, -0.097, 0.209]}>
        <mesh name='door_rr001' castShadow receiveShadow geometry={nodes.door_rr001.geometry} material={materials.primary} />
        <mesh name='door_rr001_1' castShadow receiveShadow geometry={nodes.door_rr001_1.geometry} material={materials['door_rf.004']} />
        <mesh name='door_rr001_2' castShadow receiveShadow geometry={nodes.door_rr001_2.geometry} material={materials['door_rf.006']} />
        <mesh name='door_rr001_3' castShadow receiveShadow geometry={nodes.door_rr001_3.geometry} material={materials['door_rf.007']} />
        <mesh name='door_rr001_4' castShadow receiveShadow geometry={nodes.door_rr001_4.geometry} material={materials['secondary.004']} />
      </group>
      <group name='head_lights_2' rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name='head_lights0001' castShadow receiveShadow geometry={nodes.head_lights0001.geometry} material={materials['door_rf.004']} />
        <mesh name='head_lights0001_1' castShadow receiveShadow geometry={nodes.head_lights0001_1.geometry} material={materials['door_rf.006']} />
        <mesh name='head_lights0001_2' castShadow receiveShadow geometry={nodes.head_lights0001_2.geometry} material={materials['head_lights0.001']} />
        <mesh name='head_lights0001_3' castShadow receiveShadow geometry={nodes.head_lights0001_3.geometry} material={materials['head_lights0.002']} />
        <mesh name='head_lights0001_4' castShadow receiveShadow geometry={nodes.head_lights0001_4.geometry} material={materials['right front light.001']} />
        <mesh name='head_lights0001_5' castShadow receiveShadow geometry={nodes.head_lights0001_5.geometry} material={materials['right front light.001']} />
        <mesh name='head_lights0001_6' castShadow receiveShadow geometry={nodes.head_lights0001_6.geometry} material={materials['glass.008']} />
        <mesh name='head_lights0001_7' castShadow receiveShadow geometry={nodes.head_lights0001_7.geometry} material={materials['glass.009']} />
        <mesh name='head_lights0001_8' castShadow receiveShadow geometry={nodes.head_lights0001_8.geometry} material={materials['head_lights0.005']} />
        <mesh name='head_lights0001_9' castShadow receiveShadow geometry={nodes.head_lights0001_9.geometry} material={materials['head_lights0.005']} />
        <mesh name='head_lights0001_10' castShadow receiveShadow geometry={nodes.head_lights0001_10.geometry} material={materials.glass_windows} />
      </group>
      <group name='body_shell' rotation={[-Math.PI / 2, 0, 0]}>
        <mesh name='bodyshell001' castShadow receiveShadow geometry={nodes.bodyshell001.geometry} material={materials.primary} />
        <mesh name='bodyshell001_1' castShadow receiveShadow geometry={nodes.bodyshell001_1.geometry} material={materials['door_rf.004']} />
        <mesh name='bodyshell001_2' castShadow receiveShadow geometry={nodes.bodyshell001_2.geometry} material={materials['door_rf.006']} />
        <mesh name='bodyshell001_3' castShadow receiveShadow geometry={nodes.bodyshell001_3.geometry} material={materials['door_rf.007']} />
        <mesh name='bodyshell001_4' castShadow receiveShadow geometry={nodes.bodyshell001_4.geometry} material={materials['head_lights0.001']} />
        <mesh name='bodyshell001_5' castShadow receiveShadow geometry={nodes.bodyshell001_5.geometry} material={materials['bodyshell.001']} />
        <mesh name='bodyshell001_6' castShadow receiveShadow geometry={nodes.bodyshell001_6.geometry} material={materials['bodyshell.002']} />
      </group>
      <mesh
        name='glass_rear'
        castShadow
        receiveShadow
        geometry={nodes.glass_rear.geometry}
        material={materials.glass_windows}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      {/* <group name="bumper_front_2" rotation={[-Math.PI, 0, 0]} scale={-1}>
        <mesh name="bumper_f0001" castShadow receiveShadow geometry={nodes.bumper_f0001.geometry} material={materials.primary} />
        <mesh name="bumper_f0001_1" castShadow receiveShadow geometry={nodes.bumper_f0001_1.geometry} material={materials['door_rf.004']} />
        <mesh name="bumper_f0001_2" castShadow receiveShadow geometry={nodes.bumper_f0001_2.geometry} material={materials['door_rf.006']} />
        <mesh name="bumper_f0001_3" castShadow receiveShadow geometry={nodes.bumper_f0001_3.geometry} material={materials['door_rf.007']} />
        <mesh name="bumper_f0001_4" castShadow receiveShadow geometry={nodes.bumper_f0001_4.geometry} material={materials['glass.009']} />
        <mesh name="bumper_f0001_5" castShadow receiveShadow geometry={nodes.bumper_f0001_5.geometry} material={materials.primary} />
        <mesh name="bumper_f0001_6" castShadow receiveShadow geometry={nodes.bumper_f0001_6.geometry} material={materials['bumper_f0.001']} />
      </group> */}
      <group name='bumper_front_1' position={[1.004, -0.404, -2.111]}>
        <mesh name='bumper_f1001' castShadow receiveShadow geometry={nodes.bumper_f1001.geometry} material={materials.primary} />
        <mesh name='bumper_f1001_1' castShadow receiveShadow geometry={nodes.bumper_f1001_1.geometry} material={materials['door_rf.004']} />
        <mesh name='bumper_f1001_2' castShadow receiveShadow geometry={nodes.bumper_f1001_2.geometry} material={materials['door_rf.006']} />
        <mesh name='bumper_f1001_3' castShadow receiveShadow geometry={nodes.bumper_f1001_3.geometry} material={materials['head_lights1.001']} />
        <mesh name='bumper_f1001_4' castShadow receiveShadow geometry={nodes.bumper_f1001_4.geometry} material={materials['head_lights1.002']} />
        <mesh name='bumper_f1001_5' castShadow receiveShadow geometry={nodes.bumper_f1001_5.geometry} material={materials.primary} />
        <mesh name='bumper_f1001_6' castShadow receiveShadow geometry={nodes.bumper_f1001_6.geometry} material={materials['door_rf.004']} />
        <mesh name='bumper_f1001_7' castShadow receiveShadow geometry={nodes.bumper_f1001_7.geometry} material={materials['bumper_f1.002']} />
      </group>
      <group name='trunk_1' position={[0, 0.325, 2.054]}>
        <mesh name='trunk1001' castShadow receiveShadow geometry={nodes.trunk1001.geometry} material={materials.primary} />
        <mesh name='trunk1001_1' castShadow receiveShadow geometry={nodes.trunk1001_1.geometry} material={materials['door_rf.004']} />
        <mesh name='trunk1001_2' castShadow receiveShadow geometry={nodes.trunk1001_2.geometry} material={materials['door_rf.006']} />
        <mesh name='trunk1001_3' castShadow receiveShadow geometry={nodes.trunk1001_3.geometry} material={materials['door_rf.008']} />
        <mesh name='trunk1001_4' castShadow receiveShadow geometry={nodes.trunk1001_4.geometry} material={materials['door_lf.001']} />
        <mesh name='trunk1001_5' castShadow receiveShadow geometry={nodes.trunk1001_5.geometry} material={materials['secondary.005']} />
        <mesh name='trunk1001_6' castShadow receiveShadow geometry={nodes.trunk1001_6.geometry} material={materials['bumper_f1.002']} />
        <mesh name='trunk1001_7' castShadow receiveShadow geometry={nodes.trunk1001_7.geometry} material={materials['left rear light.001']} />
        <mesh name='trunk1001_8' castShadow receiveShadow geometry={nodes.trunk1001_8.geometry} material={materials.glass_rear_lights} />
        <mesh name='trunk1001_9' castShadow receiveShadow geometry={nodes.trunk1001_9.geometry} material={materials['trunk1.001']} />
      </group>
      {/* <group name="trunk_2" position={[0, 0.325, 2.054]}>
        <mesh name="trunk0001" castShadow receiveShadow geometry={nodes.trunk0001.geometry} material={materials.primary} />
        <mesh name="trunk0001_1" castShadow receiveShadow geometry={nodes.trunk0001_1.geometry} material={materials['door_rf.004']} />
        <mesh name="trunk0001_2" castShadow receiveShadow geometry={nodes.trunk0001_2.geometry} material={materials['door_rf.006']} />
        <mesh name="trunk0001_3" castShadow receiveShadow geometry={nodes.trunk0001_3.geometry} material={materials['door_rf.008']} />
        <mesh name="trunk0001_4" castShadow receiveShadow geometry={nodes.trunk0001_4.geometry} material={materials['door_lf.001']} />
        <mesh name="trunk0001_5" castShadow receiveShadow geometry={nodes.trunk0001_5.geometry} material={materials['secondary.005']} />
        <mesh name="trunk0001_6" castShadow receiveShadow geometry={nodes.trunk0001_6.geometry} material={materials['left rear light.001']} />
        <mesh name="trunk0001_7" castShadow receiveShadow geometry={nodes.trunk0001_7.geometry} material={materials.glass_back_lights} />
        <mesh name="trunk0001_8" castShadow receiveShadow geometry={nodes.trunk0001_8.geometry} material={materials.glass_rear_lights} />
        <mesh name="trunk0001_9" castShadow receiveShadow geometry={nodes.trunk0001_9.geometry} material={materials['trunk1.001']} />
        <mesh name="trunk0001_10" castShadow receiveShadow geometry={nodes.trunk0001_10.geometry} material={materials['secondary.005']} />
        <mesh name="trunk0001_11" castShadow receiveShadow geometry={nodes.trunk0001_11.geometry} material={materials['trunk0.002']} />
        <mesh name="trunk0001_12" castShadow receiveShadow geometry={nodes.trunk0001_12.geometry} material={materials['trunk0.003']} />
      </group> */}
      {/* <mesh name="bonnet_2" castShadow receiveShadow geometry={nodes.bonnet_2.geometry} material={materials.primary} position={[0, 0.193, -1.074]} /> */}
      <group name='bonnet_1' position={[0, 0.193, -1.074]}>
        <mesh name='bonnet0001' castShadow receiveShadow geometry={nodes.bonnet0001.geometry} material={materials.primary} />
        <mesh name='bonnet0001_1' castShadow receiveShadow geometry={nodes.bonnet0001_1.geometry} material={materials['primary.005']} />
      </group>
      <mesh name='wings_front_1' castShadow receiveShadow geometry={nodes.wings_front_1.geometry} material={materials.primary} />
      {/* <group name="bumper_rear_2" position={[-0.917, -0.035, 2.536]}>
        <mesh name="bumper_r0001" castShadow receiveShadow geometry={nodes.bumper_r0001.geometry} material={materials.primary} />
        <mesh name="bumper_r0001_1" castShadow receiveShadow geometry={nodes.bumper_r0001_1.geometry} material={materials['door_rf.006']} />
        <mesh name="bumper_r0001_2" castShadow receiveShadow geometry={nodes.bumper_r0001_2.geometry} material={materials['Interior.001']} />
        <mesh name="bumper_r0001_3" castShadow receiveShadow geometry={nodes.bumper_r0001_3.geometry} material={materials.primary} />
        <mesh name="bumper_r0001_4" castShadow receiveShadow geometry={nodes.bumper_r0001_4.geometry} material={materials['bumper_f0.002']} />
      </group> */}
      <group name='bumper_rear_1' position={[-0.917, -0.035, 2.536]}>
        <mesh name='bumper_r1001' castShadow receiveShadow geometry={nodes.bumper_r1001.geometry} material={materials.primary} />
        <mesh name='bumper_r1001_1' castShadow receiveShadow geometry={nodes.bumper_r1001_1.geometry} material={materials['door_rf.004']} />
        <mesh name='bumper_r1001_2' castShadow receiveShadow geometry={nodes.bumper_r1001_2.geometry} material={materials['door_rf.006']} />
        <mesh name='bumper_r1001_3' castShadow receiveShadow geometry={nodes.bumper_r1001_3.geometry} material={materials['Interior.001']} />
      </group>
      <mesh
        name='glass_front'
        castShadow
        receiveShadow
        geometry={nodes.glass_front.geometry}
        material={materials.glass_windows}
        position={[0, 0.608, -0.381]}
      />
      {/* <mesh name="wings_front_2" castShadow receiveShadow geometry={nodes.wings_front_2.geometry} material={materials.primary} rotation={[-Math.PI / 2, 0, 0]} /> */}
      <group name='wheel_front_left' position={[-0.979, -0.5, -1.662]} scale={1.057}>
        <mesh name='wheel001' castShadow receiveShadow geometry={nodes.wheel001.geometry} material={materials['door_rf.007']} />
        <mesh name='wheel001_1' castShadow receiveShadow geometry={nodes.wheel001_1.geometry} material={materials['wheel.003']} />
        <mesh name='wheel001_2' castShadow receiveShadow geometry={nodes.wheel001_2.geometry} material={materials['wheel.004']} />
      </group>
      <group name='wheel_rear_left' position={[-0.979, -0.5, 1.618]} scale={1.057}>
        <mesh name='wheel001' castShadow receiveShadow geometry={nodes.wheel001.geometry} material={materials['door_rf.007']} />
        <mesh name='wheel001_1' castShadow receiveShadow geometry={nodes.wheel001_1.geometry} material={materials['wheel.003']} />
        <mesh name='wheel001_2' castShadow receiveShadow geometry={nodes.wheel001_2.geometry} material={materials['wheel.004']} />
      </group>
      <group name='wheel_front_right' position={[0.979, -0.5, -1.662]} scale={1.057}>
        <mesh name='wheel004' castShadow receiveShadow geometry={nodes.wheel004.geometry} material={materials['door_rf.007']} />
        <mesh name='wheel004_1' castShadow receiveShadow geometry={nodes.wheel004_1.geometry} material={materials['wheel.003']} />
        <mesh name='wheel004_2' castShadow receiveShadow geometry={nodes.wheel004_2.geometry} material={materials['wheel.004']} />
      </group>
      <group name='wheel_rear_right' position={[0.979, -0.5, 1.618]} scale={1.057}>
        <mesh name='wheel004' castShadow receiveShadow geometry={nodes.wheel004.geometry} material={materials['door_rf.007']} />
        <mesh name='wheel004_1' castShadow receiveShadow geometry={nodes.wheel004_1.geometry} material={materials['wheel.003']} />
        <mesh name='wheel004_2' castShadow receiveShadow geometry={nodes.wheel004_2.geometry} material={materials['wheel.004']} />
      </group>
      <mesh
        name='glass_door_front_right'
        castShadow
        receiveShadow
        geometry={nodes.glass_door_front_right.geometry}
        material={materials.glass_windows}
        position={[1.021, -0.217, -1.041]}
      />
      <mesh
        name='glass_door_front_left'
        castShadow
        receiveShadow
        geometry={nodes.glass_door_front_left.geometry}
        material={materials.glass_windows}
        position={[-1.008, -0.222, -1.037]}
      />
      <mesh
        name='glass_door_rear_left'
        castShadow
        receiveShadow
        geometry={nodes.glass_door_rear_left.geometry}
        material={materials.glass_windows}
        position={[-1.025, -0.145, 0.205]}
      />
      <mesh
        name='glass_door_rear_right'
        castShadow
        receiveShadow
        geometry={nodes.glass_door_rear_right.geometry}
        material={materials.glass_windows}
        position={[1.026, -0.097, 0.209]}
      />
      <group name='engine002' scale={[-1, 1, 1]}>
        <mesh name='engine001' castShadow receiveShadow geometry={nodes.engine001.geometry} material={materials['head_lights1.001']} />
        <mesh name='engine001_1' castShadow receiveShadow geometry={nodes.engine001_1.geometry} material={materials['Interior.001']} />
        <mesh name='engine001_2' castShadow receiveShadow geometry={nodes.engine001_2.geometry} material={materials.primary} />
        <mesh name='engine001_3' castShadow receiveShadow geometry={nodes.engine001_3.geometry} material={materials['engine.001']} />
        <mesh name='engine001_4' castShadow receiveShadow geometry={nodes.engine001_4.geometry} material={materials['engine.002']} />
      </group>
      <mesh name='Interior003' castShadow receiveShadow geometry={nodes.Interior003.geometry} material={materials['door_rf.007']} />
      <mesh name='head_lights1001' castShadow receiveShadow geometry={nodes.head_lights1001.geometry} material={materials['door_rf.004']} />
      <mesh name='head_lights1001_1' castShadow receiveShadow geometry={nodes.head_lights1001_1.geometry} material={materials['door_rf.006']} />
      <mesh name='head_lights1001_2' castShadow receiveShadow geometry={nodes.head_lights1001_2.geometry} material={materials['right front light.001']} />
      <mesh name='head_lights1001_3' castShadow receiveShadow geometry={nodes.head_lights1001_3.geometry} material={materials['head_lights0.005']} />
      <mesh name='head_lights1001_4' castShadow receiveShadow geometry={nodes.head_lights1001_4.geometry} material={materials['head_lights0.005']} />
      <mesh name='head_lights1001_5' castShadow receiveShadow geometry={nodes.head_lights1001_5.geometry} material={materials.glass_windows} />
      <mesh name='head_lights1001_6' castShadow receiveShadow geometry={nodes.head_lights1001_6.geometry} material={materials['head_lights1.001']} />
      <mesh name='head_lights1001_7' castShadow receiveShadow geometry={nodes.head_lights1001_7.geometry} material={materials['head_lights1.002']} />
      <mesh name='tail_lights0001' castShadow receiveShadow geometry={nodes.tail_lights0001.geometry} material={materials['door_rf.006']} />
      <mesh name='tail_lights0001_1' castShadow receiveShadow geometry={nodes.tail_lights0001_1.geometry} material={materials['door_rf.008']} />
      <mesh name='tail_lights0001_2' castShadow receiveShadow geometry={nodes.tail_lights0001_2.geometry} material={materials['door_lf.001']} />
      <mesh name='tail_lights0001_3' castShadow receiveShadow geometry={nodes.tail_lights0001_3.geometry} material={materials['left rear light.001']} />
      <mesh name='tail_lights0001_4' castShadow receiveShadow geometry={nodes.tail_lights0001_4.geometry} material={materials.glass_back_lights} />
      <mesh name='tail_lights0001_5' castShadow receiveShadow geometry={nodes.tail_lights0001_5.geometry} material={materials['trunk1.001']} />
      <mesh name='tail_lights0001_6' castShadow receiveShadow geometry={nodes.tail_lights0001_6.geometry} material={materials['trunk0.002']} />
      <mesh name='tail_lights0001_7' castShadow receiveShadow geometry={nodes.tail_lights0001_7.geometry} material={materials['trunk0.003']} />
      <mesh name='tail_lights1001' castShadow receiveShadow geometry={nodes.tail_lights1001.geometry} material={materials['door_rf.006']} />
      <mesh name='tail_lights1001_1' castShadow receiveShadow geometry={nodes.tail_lights1001_1.geometry} material={materials['door_rf.008']} />
      <mesh name='tail_lights1001_2' castShadow receiveShadow geometry={nodes.tail_lights1001_2.geometry} material={materials['door_lf.001']} />
      <mesh name='tail_lights1001_3' castShadow receiveShadow geometry={nodes.tail_lights1001_3.geometry} material={materials['bumper_f1.002']} />
      <mesh name='tail_lights1001_4' castShadow receiveShadow geometry={nodes.tail_lights1001_4.geometry} material={materials['left rear light.001']} />
      <mesh name='tail_lights1001_5' castShadow receiveShadow geometry={nodes.tail_lights1001_5.geometry} material={materials.glass_rear_lights} />
      <mesh name='tail_lights1001_6' castShadow receiveShadow geometry={nodes.tail_lights1001_6.geometry} material={materials['trunk1.001']} />
      <mesh name='tail_lights1001_7' castShadow receiveShadow geometry={nodes.tail_lights1001_7.geometry} material={materials['trunk0.003']} />
      <mesh name='Interior002_1' castShadow receiveShadow geometry={nodes.Interior002_1.geometry} material={materials['door_rf.004']} />
      <mesh name='Interior002_2' castShadow receiveShadow geometry={nodes.Interior002_2.geometry} material={materials['door_rf.006']} />
      <mesh name='Interior002_3' castShadow receiveShadow geometry={nodes.Interior002_3.geometry} material={materials['door_rf.007']} />
      <mesh name='Interior002_4' castShadow receiveShadow geometry={nodes.Interior002_4.geometry} material={materials['secondary.004']} />
      <mesh name='Interior002_5' castShadow receiveShadow geometry={nodes.Interior002_5.geometry} material={materials['secondary.005']} />
      <mesh name='Interior002_6' castShadow receiveShadow geometry={nodes.Interior002_6.geometry} material={materials['Interior.001']} />
      <mesh name='Interior002_7' castShadow receiveShadow geometry={nodes.Interior002_7.geometry} material={materials['secondary.006']} />
      <mesh name='Interior002_8' castShadow receiveShadow geometry={nodes.Interior002_8.geometry} material={materials['Interior.002']} />
      <mesh name='Interior002_9' castShadow receiveShadow geometry={nodes.Interior002_9.geometry} material={materials['secondary.007']} />
    </group>
  )
}

useGLTF.preload('assets/3d/transformed_gltf/cars/audi/A8/audi_a8-transformed.glb')
