/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./audi_r8.gltf --types --transform --shadows --keepnames --keepmeshes --keepmaterials 
Files: ./audi_r8.gltf [159.84KB] > audi_r8-transformed.glb [904.04KB] (-466%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { degToRad } from 'three/src/math/MathUtils'
import { Euler, Vector3 } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    wheel: THREE.Mesh
    wheel_1: THREE.Mesh
    wheel_2: THREE.Mesh
    wheel_3: THREE.Mesh
    wheel_4: THREE.Mesh
    wheel_5: THREE.Mesh
    spoiler_base2: THREE.Mesh
    spoiler_base2_1: THREE.Mesh
    lights_front_1: THREE.Mesh
    lights_front_2: THREE.Mesh
    bodyshell: THREE.Mesh
    bodyshell_1: THREE.Mesh
    bodyshell_2: THREE.Mesh
    bodyshell_3: THREE.Mesh
    bodyshell_4: THREE.Mesh
    bodyshell_5: THREE.Mesh
    bodyshell_6: THREE.Mesh
    bodyshell_7: THREE.Mesh
    bodyshell_8: THREE.Mesh
    bodyshell_9: THREE.Mesh
    bonnet_ok: THREE.Mesh
    bonnet_ok_1: THREE.Mesh
    bump_front_ok: THREE.Mesh
    bump_front_ok_1: THREE.Mesh
    bump_front_ok_2: THREE.Mesh
    bump_front_ok_3: THREE.Mesh
    bump_front_ok_4: THREE.Mesh
    bump_rear_ok: THREE.Mesh
    bump_rear_ok_1: THREE.Mesh
    bump_rear_ok_2: THREE.Mesh
    bump_rear_ok_3: THREE.Mesh
    bump_rear_ok_4: THREE.Mesh
    bump_rear_ok_5: THREE.Mesh
    bump_rear_ok_6: THREE.Mesh
    door_rf: THREE.Mesh
    door_rf_1: THREE.Mesh
    door_rf_2: THREE.Mesh
    door_rf_3: THREE.Mesh
    door_rf_4: THREE.Mesh
    door_rf_5: THREE.Mesh
    door_rf_6: THREE.Mesh
    door_rf_7: THREE.Mesh
    door_lf: THREE.Mesh
    door_lf_1: THREE.Mesh
    door_lf_2: THREE.Mesh
    door_lf_3: THREE.Mesh
    door_lf_4: THREE.Mesh
    door_lf_5: THREE.Mesh
    door_lf_6: THREE.Mesh
    door_lf_7: THREE.Mesh
    glass_door_front_right: THREE.Mesh
    glass_door_front_left: THREE.Mesh
    windscreen_ok: THREE.Mesh
    windscreen_ok_1: THREE.Mesh
    windscreen_ok_2: THREE.Mesh
    bonnet1: THREE.Mesh
    bonnet1_1: THREE.Mesh
    bonnet1_2: THREE.Mesh
    bonnet1_3: THREE.Mesh
    airintake_rear_1: THREE.Mesh
    side_mirrors_1: THREE.Mesh
    spoiler1: THREE.Mesh
    spoiler1_1: THREE.Mesh
    spoiler1_2: THREE.Mesh
    spoiler1_3: THREE.Mesh
    spoiler1_4: THREE.Mesh
    skirts_1: THREE.Mesh
    splitter_front_1: THREE.Mesh
    diffuser_rear_1: THREE.Mesh
    wheel001: THREE.Mesh
    wheel001_1: THREE.Mesh
    wheel001_2: THREE.Mesh
    wheel001_3: THREE.Mesh
    wheel001_4: THREE.Mesh
    wheel001_5: THREE.Mesh
    Base: THREE.Mesh
    engine: THREE.Mesh
    engine_1: THREE.Mesh
    engine_2: THREE.Mesh
    engine_3: THREE.Mesh
    engine_4: THREE.Mesh
    engine_5: THREE.Mesh
    engine_6: THREE.Mesh
    engine_7: THREE.Mesh
    glass_rear: THREE.Mesh
    Interior_1: THREE.Mesh
    Interior_2: THREE.Mesh
    Interior_3: THREE.Mesh
    Interior_4: THREE.Mesh
    Interior_5: THREE.Mesh
    Interior_6: THREE.Mesh
    Interior_7: THREE.Mesh
    Interior_8: THREE.Mesh
    lights_1: THREE.Mesh
    lights_2: THREE.Mesh
    lights_3: THREE.Mesh
    lights_4: THREE.Mesh
    lights_5: THREE.Mesh
    lights_6: THREE.Mesh
    lights_7: THREE.Mesh
    Glass_1: THREE.Mesh
    Glass_2: THREE.Mesh
    Engine: THREE.Mesh
  }
  materials: {
    ['wheel.0']: THREE.MeshStandardMaterial
    ['wheel.7']: THREE.MeshStandardMaterial
    secondary: THREE.MeshStandardMaterial
    ['wheel.4']: THREE.MeshStandardMaterial
    ['spoiler_base2.0']: THREE.MeshStandardMaterial
    ['spoiler_base2.1']: THREE.MeshStandardMaterial
    ['chassis_vlo.0']: THREE.MeshStandardMaterial
    ['right front light']: THREE.MeshStandardMaterial
    primary: THREE.MeshPhysicalMaterial
    ['bodyshell.2']: THREE.MeshStandardMaterial
    ['bodyshell.3']: THREE.MeshStandardMaterial
    interior: THREE.MeshStandardMaterial
    ['bodyshell.6']: THREE.MeshStandardMaterial
    ['bodyshell.7']: THREE.MeshStandardMaterial
    ['Base.0']: THREE.MeshStandardMaterial
    glass_windows: THREE.MeshStandardMaterial
    ['bump_front_ok.4']: THREE.MeshStandardMaterial
    ['bump_rear_ok.6']: THREE.MeshStandardMaterial
    ['interior.001']: THREE.MeshStandardMaterial
    ['lights.4']: THREE.MeshStandardMaterial
    ['misc1.2']: THREE.MeshStandardMaterial
    ['misc1.3']: THREE.MeshStandardMaterial
    ['engine.5']: THREE.MeshStandardMaterial
    ['engine.6']: THREE.MeshStandardMaterial
    ['engine.7']: THREE.MeshStandardMaterial
    ['right rear light']: THREE.MeshStandardMaterial
    ['lights.2']: THREE.MeshStandardMaterial
    ['lights.6']: THREE.MeshStandardMaterial
    ['glass.001']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('assets/3d/transformed_gltf/cars/audi/R8/audi_r8-transformed.glb') as GLTFResult

  const [defaultCarProps] = React.useState({
    position: [0, 1.0075, 0] as Vector3,
    rotation: [degToRad(0), degToRad(-135), degToRad(0)] as Euler,
    scale: 1.1,
    materials: {
      primary: {
        color: new THREE.Color('orange'),
        metalness: 0.3,
        roughness: 1,
        clearcoat: 0.05,
        specularIntensity: 0,
      },
      'interior.001': {
        color: new THREE.Color('red'),
      },
    },
  })

  React.useEffect(() => {
    materials.primary.color = defaultCarProps.materials['primary'].color
    materials.primary.metalness = defaultCarProps.materials['primary'].metalness
    materials.primary.roughness = defaultCarProps.materials['primary'].roughness
    materials.primary.clearcoat = defaultCarProps.materials['primary'].clearcoat
    materials.primary.specularIntensity = defaultCarProps.materials['primary'].specularIntensity

    materials['interior.001'].color = defaultCarProps.materials['interior.001'].color
  }, [])

  return (
    <group {...props} dispose={null} position={defaultCarProps.position} rotation={defaultCarProps.rotation} scale={defaultCarProps.scale}>
      <group name='wheel_front_left' position={[-0.994, -0.372, -1.461]}>
        <mesh name='wheel' castShadow receiveShadow geometry={nodes.wheel.geometry} material={materials['wheel.0']} />
        <mesh name='wheel_1' castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name='wheel_2' castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.7']} />
        <mesh name='wheel_3' castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials.secondary} />
        <mesh name='wheel_4' castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.4']} />
        <mesh name='wheel_5' castShadow receiveShadow geometry={nodes.wheel_5.geometry} material={materials['wheel.7']} />
      </group>
      <group name='wheel_rear_left' position={[-1.021, -0.372, 1.519]}>
        <mesh name='wheel' castShadow receiveShadow geometry={nodes.wheel.geometry} material={materials['wheel.0']} />
        <mesh name='wheel_1' castShadow receiveShadow geometry={nodes.wheel_1.geometry} material={materials['wheel.0']} />
        <mesh name='wheel_2' castShadow receiveShadow geometry={nodes.wheel_2.geometry} material={materials['wheel.7']} />
        <mesh name='wheel_3' castShadow receiveShadow geometry={nodes.wheel_3.geometry} material={materials.secondary} />
        <mesh name='wheel_4' castShadow receiveShadow geometry={nodes.wheel_4.geometry} material={materials['wheel.4']} />
        <mesh name='wheel_5' castShadow receiveShadow geometry={nodes.wheel_5.geometry} material={materials['wheel.7']} />
      </group>
      <group name='spoiler_base' position={[0, -0.009, 0.039]}>
        <mesh name='spoiler_base2' castShadow receiveShadow geometry={nodes.spoiler_base2.geometry} material={materials['spoiler_base2.0']} />
        <mesh name='spoiler_base2_1' castShadow receiveShadow geometry={nodes.spoiler_base2_1.geometry} material={materials['spoiler_base2.1']} />
      </group>
      <group name='bonnet_1' position={[0, 0.051, -1.118]}>
        <mesh name='bonnet_ok' castShadow receiveShadow geometry={nodes.bonnet_ok.geometry} material={materials.secondary} />
        <mesh name='bonnet_ok_1' castShadow receiveShadow geometry={nodes.bonnet_ok_1.geometry} material={materials.primary} />
      </group>
      <group name='bumper_front_1' position={[0, -0.323, -2.568]}>
        <mesh name='bump_front_ok' castShadow receiveShadow geometry={nodes.bump_front_ok.geometry} material={materials.secondary} />
        <mesh name='bump_front_ok_1' castShadow receiveShadow geometry={nodes.bump_front_ok_1.geometry} material={materials.primary} />
        <mesh name='bump_front_ok_2' castShadow receiveShadow geometry={nodes.bump_front_ok_2.geometry} material={materials['Base.0']} />
        <mesh name='bump_front_ok_3' castShadow receiveShadow geometry={nodes.bump_front_ok_3.geometry} material={materials['Base.0']} />
        <mesh name='bump_front_ok_4' castShadow receiveShadow geometry={nodes.bump_front_ok_4.geometry} material={materials['bump_front_ok.4']} />
      </group>
      <group name='bumper_rear_1' position={[0, -0.22, 2.386]}>
        <mesh name='bump_rear_ok' castShadow receiveShadow geometry={nodes.bump_rear_ok.geometry} material={materials.secondary} />
        <mesh name='bump_rear_ok_1' castShadow receiveShadow geometry={nodes.bump_rear_ok_1.geometry} material={materials.primary} />
        <mesh name='bump_rear_ok_2' castShadow receiveShadow geometry={nodes.bump_rear_ok_2.geometry} material={materials.interior} />
        <mesh name='bump_rear_ok_3' castShadow receiveShadow geometry={nodes.bump_rear_ok_3.geometry} material={materials['Base.0']} />
        <mesh name='bump_rear_ok_4' castShadow receiveShadow geometry={nodes.bump_rear_ok_4.geometry} material={materials.secondary} />
        <mesh name='bump_rear_ok_5' castShadow receiveShadow geometry={nodes.bump_rear_ok_5.geometry} material={materials['Base.0']} />
        <mesh name='bump_rear_ok_6' castShadow receiveShadow geometry={nodes.bump_rear_ok_6.geometry} material={materials['bump_rear_ok.6']} />
      </group>
      <group name='door_front_right' position={[0.971, -0.193, -0.948]}>
        <mesh name='door_rf' castShadow receiveShadow geometry={nodes.door_rf.geometry} material={materials.secondary} />
        <mesh name='door_rf_1' castShadow receiveShadow geometry={nodes.door_rf_1.geometry} material={materials.primary} />
        <mesh name='door_rf_2' castShadow receiveShadow geometry={nodes.door_rf_2.geometry} material={materials['bodyshell.3']} />
        <mesh name='door_rf_3' castShadow receiveShadow geometry={nodes.door_rf_3.geometry} material={materials.interior} />
        <mesh name='door_rf_4' castShadow receiveShadow geometry={nodes.door_rf_4.geometry} material={materials['bodyshell.7']} />
        <mesh name='door_rf_5' castShadow receiveShadow geometry={nodes.door_rf_5.geometry} material={materials['interior.001']} />
        <mesh name='door_rf_6' castShadow receiveShadow geometry={nodes.door_rf_6.geometry} material={materials['Base.0']} />
        <mesh name='door_rf_7' castShadow receiveShadow geometry={nodes.door_rf_7.geometry} material={materials['lights.4']} />
      </group>
      <group name='door_front_left' position={[-0.971, -0.193, -0.945]}>
        <mesh name='door_lf' castShadow receiveShadow geometry={nodes.door_lf.geometry} material={materials.secondary} />
        <mesh name='door_lf_1' castShadow receiveShadow geometry={nodes.door_lf_1.geometry} material={materials.primary} />
        <mesh name='door_lf_2' castShadow receiveShadow geometry={nodes.door_lf_2.geometry} material={materials['bodyshell.3']} />
        <mesh name='door_lf_3' castShadow receiveShadow geometry={nodes.door_lf_3.geometry} material={materials.interior} />
        <mesh name='door_lf_4' castShadow receiveShadow geometry={nodes.door_lf_4.geometry} material={materials['bodyshell.7']} />
        <mesh name='door_lf_5' castShadow receiveShadow geometry={nodes.door_lf_5.geometry} material={materials['interior.001']} />
        <mesh name='door_lf_6' castShadow receiveShadow geometry={nodes.door_lf_6.geometry} material={materials['Base.0']} />
        <mesh name='door_lf_7' castShadow receiveShadow geometry={nodes.door_lf_7.geometry} material={materials['lights.4']} />
      </group>
      <mesh
        name='glass_door_front_right'
        castShadow
        receiveShadow
        geometry={nodes.glass_door_front_right.geometry}
        material={materials.glass_windows}
        position={[0.971, -0.193, -0.948]}
      />
      <mesh
        name='glass_door_front_left'
        castShadow
        receiveShadow
        geometry={nodes.glass_door_front_left.geometry}
        material={materials.glass_windows}
        position={[-0.971, -0.193, -0.945]}
      />
      <group name='glass_front' position={[0, 0.354, -1.005]}>
        <mesh name='windscreen_ok' castShadow receiveShadow geometry={nodes.windscreen_ok.geometry} material={materials.secondary} />
        <mesh name='windscreen_ok_1' castShadow receiveShadow geometry={nodes.windscreen_ok_1.geometry} material={materials['Base.0']} />
        <mesh name='windscreen_ok_2' castShadow receiveShadow geometry={nodes.windscreen_ok_2.geometry} material={materials.glass_windows} />
      </group>
      <mesh name='airintake_rear_1' castShadow receiveShadow geometry={nodes.airintake_rear_1.geometry} material={materials['bodyshell.3']} />
      <mesh
        name='side_mirrors_1'
        castShadow
        receiveShadow
        geometry={nodes.side_mirrors_1.geometry}
        material={materials['bodyshell.3']}
        position={[0.971, -0.193, -0.948]}
      />
      <group name='spoiler_1' position={[0, -0.009, 0.039]}>
        <mesh name='spoiler1' castShadow receiveShadow geometry={nodes.spoiler1.geometry} material={materials['spoiler_base2.0']} />
        <mesh name='spoiler1_1' castShadow receiveShadow geometry={nodes.spoiler1_1.geometry} material={materials.primary} />
        <mesh name='spoiler1_2' castShadow receiveShadow geometry={nodes.spoiler1_2.geometry} material={materials['bodyshell.2']} />
        <mesh name='spoiler1_3' castShadow receiveShadow geometry={nodes.spoiler1_3.geometry} material={materials['bodyshell.3']} />
        <mesh name='spoiler1_4' castShadow receiveShadow geometry={nodes.spoiler1_4.geometry} material={materials['Base.0']} />
      </group>
      <mesh name='skirts_1' castShadow receiveShadow geometry={nodes.skirts_1.geometry} material={materials['bodyshell.7']} />
      <mesh name='splitter_front_1' castShadow receiveShadow geometry={nodes.splitter_front_1.geometry} material={materials['bodyshell.7']} />
      <mesh name='diffuser_rear_1' castShadow receiveShadow geometry={nodes.diffuser_rear_1.geometry} material={materials['bodyshell.7']} />
      <group name='wheel_front_right' position={[0.994, -0.372, -1.461]}>
        <mesh name='wheel001' castShadow receiveShadow geometry={nodes.wheel001.geometry} material={materials['wheel.0']} />
        <mesh name='wheel001_1' castShadow receiveShadow geometry={nodes.wheel001_1.geometry} material={materials['wheel.0']} />
        <mesh name='wheel001_2' castShadow receiveShadow geometry={nodes.wheel001_2.geometry} material={materials['wheel.7']} />
        <mesh name='wheel001_3' castShadow receiveShadow geometry={nodes.wheel001_3.geometry} material={materials.secondary} />
        <mesh name='wheel001_4' castShadow receiveShadow geometry={nodes.wheel001_4.geometry} material={materials['wheel.4']} />
        <mesh name='wheel001_5' castShadow receiveShadow geometry={nodes.wheel001_5.geometry} material={materials['wheel.7']} />
      </group>
      <group name='wheel_rear_right' position={[1.021, -0.372, 1.519]}>
        <mesh name='wheel001' castShadow receiveShadow geometry={nodes.wheel001.geometry} material={materials['wheel.0']} />
        <mesh name='wheel001_1' castShadow receiveShadow geometry={nodes.wheel001_1.geometry} material={materials['wheel.0']} />
        <mesh name='wheel001_2' castShadow receiveShadow geometry={nodes.wheel001_2.geometry} material={materials['wheel.7']} />
        <mesh name='wheel001_3' castShadow receiveShadow geometry={nodes.wheel001_3.geometry} material={materials.secondary} />
        <mesh name='wheel001_4' castShadow receiveShadow geometry={nodes.wheel001_4.geometry} material={materials['wheel.4']} />
        <mesh name='wheel001_5' castShadow receiveShadow geometry={nodes.wheel001_5.geometry} material={materials['wheel.7']} />
      </group>
      <mesh name='Base' castShadow receiveShadow geometry={nodes.Base.geometry} material={materials['Base.0']} />
      <mesh name='glass_rear' castShadow receiveShadow geometry={nodes.glass_rear.geometry} material={materials.glass_windows} />
      <mesh name='Engine' castShadow receiveShadow geometry={nodes.Engine.geometry} material={materials.secondary} position={[0, 0.051, -1.118]} />
      <mesh name='lights_front_1' castShadow receiveShadow geometry={nodes.lights_front_1.geometry} material={materials['chassis_vlo.0']} />
      <mesh name='lights_front_2' castShadow receiveShadow geometry={nodes.lights_front_2.geometry} material={materials['right front light']} />
      <mesh name='bodyshell' castShadow receiveShadow geometry={nodes.bodyshell.geometry} material={materials.secondary} />
      <mesh name='bodyshell_1' castShadow receiveShadow geometry={nodes.bodyshell_1.geometry} material={materials.primary} />
      <mesh name='bodyshell_2' castShadow receiveShadow geometry={nodes.bodyshell_2.geometry} material={materials['bodyshell.2']} />
      <mesh name='bodyshell_3' castShadow receiveShadow geometry={nodes.bodyshell_3.geometry} material={materials['bodyshell.3']} />
      <mesh name='bodyshell_4' castShadow receiveShadow geometry={nodes.bodyshell_4.geometry} material={materials.interior} />
      <mesh name='bodyshell_5' castShadow receiveShadow geometry={nodes.bodyshell_5.geometry} material={materials['bodyshell.6']} />
      <mesh name='bodyshell_6' castShadow receiveShadow geometry={nodes.bodyshell_6.geometry} material={materials['bodyshell.7']} />
      <mesh name='bodyshell_7' castShadow receiveShadow geometry={nodes.bodyshell_7.geometry} material={materials['Base.0']} />
      <mesh name='bodyshell_8' castShadow receiveShadow geometry={nodes.bodyshell_8.geometry} material={materials['Base.0']} />
      <mesh name='bodyshell_9' castShadow receiveShadow geometry={nodes.bodyshell_9.geometry} material={materials.glass_windows} />
      <mesh name='bonnet1' castShadow receiveShadow geometry={nodes.bonnet1.geometry} material={materials.secondary} />
      <mesh name='bonnet1_1' castShadow receiveShadow geometry={nodes.bonnet1_1.geometry} material={materials['misc1.2']} />
      <mesh name='bonnet1_2' castShadow receiveShadow geometry={nodes.bonnet1_2.geometry} material={materials['misc1.3']} />
      <mesh name='bonnet1_3' castShadow receiveShadow geometry={nodes.bonnet1_3.geometry} material={materials['bodyshell.2']} />
      <mesh name='engine' castShadow receiveShadow geometry={nodes.engine.geometry} material={materials.secondary} />
      <mesh name='engine_1' castShadow receiveShadow geometry={nodes.engine_1.geometry} material={materials['bodyshell.2']} />
      <mesh name='engine_2' castShadow receiveShadow geometry={nodes.engine_2.geometry} material={materials['bodyshell.3']} />
      <mesh name='engine_3' castShadow receiveShadow geometry={nodes.engine_3.geometry} material={materials.interior} />
      <mesh name='engine_4' castShadow receiveShadow geometry={nodes.engine_4.geometry} material={materials['bodyshell.6']} />
      <mesh name='engine_5' castShadow receiveShadow geometry={nodes.engine_5.geometry} material={materials['engine.5']} />
      <mesh name='engine_6' castShadow receiveShadow geometry={nodes.engine_6.geometry} material={materials['engine.6']} />
      <mesh name='engine_7' castShadow receiveShadow geometry={nodes.engine_7.geometry} material={materials['engine.7']} />
      <mesh name='Interior_1' castShadow receiveShadow geometry={nodes.Interior_1.geometry} material={materials.secondary} />
      <mesh name='Interior_2' castShadow receiveShadow geometry={nodes.Interior_2.geometry} material={materials['bodyshell.2']} />
      <mesh name='Interior_3' castShadow receiveShadow geometry={nodes.Interior_3.geometry} material={materials['bodyshell.3']} />
      <mesh name='Interior_4' castShadow receiveShadow geometry={nodes.Interior_4.geometry} material={materials.interior} />
      <mesh name='Interior_5' castShadow receiveShadow geometry={nodes.Interior_5.geometry} material={materials['bodyshell.6']} />
      <mesh name='Interior_6' castShadow receiveShadow geometry={nodes.Interior_6.geometry} material={materials['interior.001']} />
      <mesh name='Interior_7' castShadow receiveShadow geometry={nodes.Interior_7.geometry} material={materials['interior.001']} />
      <mesh name='Interior_8' castShadow receiveShadow geometry={nodes.Interior_8.geometry} material={materials['interior.001']} />
      <mesh name='lights_1' castShadow receiveShadow geometry={nodes.lights_1.geometry} material={materials.glass_windows} />
      <mesh name='lights_2' castShadow receiveShadow geometry={nodes.lights_2.geometry} material={materials['right rear light']} />
      <mesh name='lights_3' castShadow receiveShadow geometry={nodes.lights_3.geometry} material={materials['lights.2']} />
      <mesh name='lights_4' castShadow receiveShadow geometry={nodes.lights_4.geometry} material={materials['lights.4']} />
      <mesh name='lights_5' castShadow receiveShadow geometry={nodes.lights_5.geometry} material={materials['lights.4']} />
      <mesh name='lights_6' castShadow receiveShadow geometry={nodes.lights_6.geometry} material={materials['right front light']} />
      <mesh name='lights_7' castShadow receiveShadow geometry={nodes.lights_7.geometry} material={materials['lights.6']} />
      <mesh name='Glass_1' castShadow receiveShadow geometry={nodes.Glass_1.geometry} material={materials.glass_windows} />
      <mesh name='Glass_2' castShadow receiveShadow geometry={nodes.Glass_2.geometry} material={materials['glass.001']} />
    </group>
  )
}

useGLTF.preload('assets/3d/transformed_gltf/cars/audi/R8/audi_r8-transformed.glb')
