/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./audi_rs6.gltf --types --transform --shadows --keepnames --keepmeshes --keepmaterials 
Files: ./audi_rs6.gltf [245.41KB] > audi_rs6-transformed.glb [1.61MB] (-554%)
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { degToRad } from 'three/src/math/MathUtils'

import { observer } from 'mobx-react-lite'
import storeStyling from '@stores/storeStyling'
import IDeclaredBodypartData from '@models/styling/IDeclaredBodypartData'
import IDemonstrativeBodyparts from '@models/styling/IDemonstrativeBodyparts'

type GLTFResult = GLTF & {
  nodes: {
    door_rf: THREE.Mesh
    door_rf_1: THREE.Mesh
    door_rf_2: THREE.Mesh
    door_rf_3: THREE.Mesh
    door_rf_4: THREE.Mesh
    door_rf_5: THREE.Mesh
    door_rf_6: THREE.Mesh
    door_rf_7: THREE.Mesh
    door_rf_8: THREE.Mesh
    door_rf_9: THREE.Mesh
    door_rf_10: THREE.Mesh
    door_rr: THREE.Mesh
    door_rr_1: THREE.Mesh
    door_rr_2: THREE.Mesh
    door_rr_3: THREE.Mesh
    door_rr_4: THREE.Mesh
    door_rr_5: THREE.Mesh
    door_rr_6: THREE.Mesh
    door_rr_7: THREE.Mesh
    door_rr_8: THREE.Mesh
    door_lr: THREE.Mesh
    door_lr_1: THREE.Mesh
    door_lr_2: THREE.Mesh
    door_lr_3: THREE.Mesh
    door_lr_4: THREE.Mesh
    door_lr_5: THREE.Mesh
    door_lr_6: THREE.Mesh
    door_lr_7: THREE.Mesh
    door_lr_8: THREE.Mesh
    door_lf: THREE.Mesh
    door_lf_1: THREE.Mesh
    door_lf_2: THREE.Mesh
    door_lf_3: THREE.Mesh
    door_lf_4: THREE.Mesh
    door_lf_5: THREE.Mesh
    door_lf_6: THREE.Mesh
    door_lf_7: THREE.Mesh
    door_lf_8: THREE.Mesh
    door_lf_9: THREE.Mesh
    door_lf_10: THREE.Mesh
    lights: THREE.Mesh
    lights_1: THREE.Mesh
    lights_2: THREE.Mesh
    lights_3: THREE.Mesh
    lights_4: THREE.Mesh
    lights_5: THREE.Mesh
    lights_6: THREE.Mesh
    lights_7: THREE.Mesh
    lights_8: THREE.Mesh
    lights_9: THREE.Mesh
    lights_10: THREE.Mesh
    lights_11: THREE.Mesh
    lights_12: THREE.Mesh
    lights_13: THREE.Mesh
    lights_14: THREE.Mesh
    lights_15: THREE.Mesh
    rearlights: THREE.Mesh
    rearlights_1: THREE.Mesh
    rearlights_2: THREE.Mesh
    rearlights_3: THREE.Mesh
    rearlights_4: THREE.Mesh
    rearlights_5: THREE.Mesh
    rearlights_6: THREE.Mesh
    rearlights_7: THREE.Mesh
    rearlights_8: THREE.Mesh
    tail_glass_1: THREE.Mesh
    speed: THREE.Mesh
    speed_1: THREE.Mesh
    speed_2: THREE.Mesh
    speed_3: THREE.Mesh
    main2: THREE.Mesh
    main2_1: THREE.Mesh
    engine_1_1: THREE.Mesh
    engine_1_2: THREE.Mesh
    engine_1_3: THREE.Mesh
    engine_1_4: THREE.Mesh
    engine_1_5: THREE.Mesh
    engine_1_6: THREE.Mesh
    engine_1_7: THREE.Mesh
    engine_1_8: THREE.Mesh
    body_shell_1: THREE.Mesh
    body_shell_2: THREE.Mesh
    body_shell_3: THREE.Mesh
    body_shell_4: THREE.Mesh
    body_shell_5: THREE.Mesh
    body_shell_6: THREE.Mesh
    body_shell_7: THREE.Mesh
    body_shell_8: THREE.Mesh
    body_shell_9: THREE.Mesh
    body_shell_10: THREE.Mesh
    body_shell_11: THREE.Mesh
    body_shell_12: THREE.Mesh
    body_shell_13: THREE.Mesh
    body_shell_14: THREE.Mesh
    body_shell_15: THREE.Mesh
    body_shell_16: THREE.Mesh
    glass_head_lights_1: THREE.Mesh
    bumper_f0: THREE.Mesh
    bumper_f0_1: THREE.Mesh
    bumper_f0_2: THREE.Mesh
    bumper_f0_3: THREE.Mesh
    bumper_f0_4: THREE.Mesh
    bumper_f0_5: THREE.Mesh
    bumper_f0_6: THREE.Mesh
    bumper_f0_7: THREE.Mesh
    bumper_f0_8: THREE.Mesh
    bumper_r0: THREE.Mesh
    bumper_r0_1: THREE.Mesh
    bumper_r0_2: THREE.Mesh
    bumper_r0_3: THREE.Mesh
    bonnet_1_1: THREE.Mesh
    bonnet_1_2: THREE.Mesh
    steeringwheel_ok: THREE.Mesh
    steeringwheel_ok_1: THREE.Mesh
    steeringwheel_ok_2: THREE.Mesh
    steeringwheel_ok_3: THREE.Mesh
    steeringwheel_ok_4: THREE.Mesh
    steeringwheel_ok_5: THREE.Mesh
    steeringwheel_ok_6: THREE.Mesh
    glass_rear_1: THREE.Mesh
    glass_front_1: THREE.Mesh
    trunk0: THREE.Mesh
    trunk0_1: THREE.Mesh
    trunk0_2: THREE.Mesh
    trunk0_3: THREE.Mesh
    trunk0_4: THREE.Mesh
    trunk0_5: THREE.Mesh
    trunk0_6: THREE.Mesh
    trunk0_7: THREE.Mesh
    trunk0_8: THREE.Mesh
    bootlights: THREE.Mesh
    bootlights_1: THREE.Mesh
    bootlights_2: THREE.Mesh
    bootlights_3: THREE.Mesh
    bootlights_4: THREE.Mesh
    bootlights_5: THREE.Mesh
    bootlights_6: THREE.Mesh
    bootlights_7: THREE.Mesh
    bootlights_8: THREE.Mesh
    bootlights_9: THREE.Mesh
    bootlights_10: THREE.Mesh
    bootlights_11: THREE.Mesh
    tail_trunk_lights_glass_1: THREE.Mesh
    wheel_front_left_1_1: THREE.Mesh
    wheel_front_left_1_2: THREE.Mesh
    wheel_front_left_1_3: THREE.Mesh
    wheel_front_left_1_4: THREE.Mesh
    wheel_front_left_1_5: THREE.Mesh
    wheel_front_right_1_1: THREE.Mesh
    wheel_front_right_1_2: THREE.Mesh
    wheel_front_right_1_3: THREE.Mesh
    wheel_front_right_1_4: THREE.Mesh
    wheel_front_right_1_5: THREE.Mesh
    roof_diffuser_1: THREE.Mesh
    glass_front_frame: THREE.Mesh
    glass_door_front_right: THREE.Mesh
    glass_door_rear_right: THREE.Mesh
    glass_door_rear_left: THREE.Mesh
    glass_door_front_left: THREE.Mesh
  }
  materials: {
    ['door_rf.0']: THREE.MeshStandardMaterial
    ['wheel.0']: THREE.MeshStandardMaterial
    ['wheel.1']: THREE.MeshStandardMaterial
    ['chassis_vlo.0']: THREE.MeshStandardMaterial
    ['door_rf.4']: THREE.MeshPhysicalMaterial
    primary: THREE.MeshStandardMaterial
    ['door_rf.6']: THREE.MeshStandardMaterial
    ['door_rf.7']: THREE.MeshStandardMaterial
    ['door_rf.8']: THREE.MeshStandardMaterial
    ['door_rf.9']: THREE.MeshStandardMaterial
    ['door_rf.10']: THREE.MeshStandardMaterial
    ['right front light']: THREE.MeshStandardMaterial
    ['lights.1']: THREE.MeshStandardMaterial
    ['right front light.001']: THREE.MeshStandardMaterial
    ['lights.3']: THREE.MeshStandardMaterial
    ['lights.4']: THREE.MeshStandardMaterial
    ['lights.5']: THREE.MeshStandardMaterial
    ['rearlights.1']: THREE.MeshStandardMaterial
    glass_rear_lights: THREE.MeshStandardMaterial
    ['speed.2']: THREE.MeshStandardMaterial
    ['speed.3']: THREE.MeshStandardMaterial
    ['engine.9']: THREE.MeshStandardMaterial
    ['bodyshell2.2']: THREE.MeshStandardMaterial
    ['seats.1']: THREE.MeshStandardMaterial
    ['bodyshell2.11']: THREE.MeshStandardMaterial
    ['bodyshell2.12']: THREE.MeshStandardMaterial
    ['bodyshell2.13']: THREE.MeshStandardMaterial
    glass_window: THREE.MeshStandardMaterial
    ['bumper_f0.5']: THREE.MeshStandardMaterial
    ['bumper_f0.10']: THREE.MeshStandardMaterial
    interior: THREE.MeshStandardMaterial
    ['steeringwheel_ok.4']: THREE.MeshStandardMaterial
    ['steeringwheel_ok.5']: THREE.MeshStandardMaterial
    ['chassis_vlo.2']: THREE.MeshStandardMaterial
    mat_wheel_primary: THREE.MeshStandardMaterial
    mat_wheel_disk_brakes: THREE.MeshStandardMaterial
    mat_wheel_tire_side: THREE.MeshStandardMaterial
    mat_wheel_tire_ground: THREE.MeshStandardMaterial
  }
}

export const declaredBodypartsData: IDeclaredBodypartData[] = [
  { from_category: 'bonnets', id: 1, name: 'hello', price: 1200 },
  { from_category: 'bonnets', id: 2, name: 'Streexes', price: 5000 },
]

function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('assets/3d/transformed_gltf/cars/audi/RS6/audi_rs6-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name='door_front_right_1' position={[0.914, 0.005, -0.788]}>
        <mesh name='door_rf' castShadow receiveShadow geometry={nodes.door_rf.geometry} material={materials['door_rf.0']} />
        <mesh name='door_rf_1' castShadow receiveShadow geometry={nodes.door_rf_1.geometry} material={materials['wheel.0']} />
        <mesh name='door_rf_2' castShadow receiveShadow geometry={nodes.door_rf_2.geometry} material={materials['wheel.1']} />
        <mesh name='door_rf_3' castShadow receiveShadow geometry={nodes.door_rf_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name='door_rf_4' castShadow receiveShadow geometry={nodes.door_rf_4.geometry} material={materials['door_rf.4']} />
        <mesh name='door_rf_5' castShadow receiveShadow geometry={nodes.door_rf_5.geometry} material={materials.primary} />
        <mesh name='door_rf_6' castShadow receiveShadow geometry={nodes.door_rf_6.geometry} material={materials['door_rf.6']} />
        <mesh name='door_rf_7' castShadow receiveShadow geometry={nodes.door_rf_7.geometry} material={materials['door_rf.7']} />
        <mesh name='door_rf_8' castShadow receiveShadow geometry={nodes.door_rf_8.geometry} material={materials['door_rf.8']} />
        <mesh name='door_rf_9' castShadow receiveShadow geometry={nodes.door_rf_9.geometry} material={materials['door_rf.9']} />
        <mesh name='door_rf_10' castShadow receiveShadow geometry={nodes.door_rf_10.geometry} material={materials['door_rf.10']} />
      </group>
      <group name='door_rear_right_1' position={[0.941, -0.153, 0.438]}>
        <mesh name='door_rr' castShadow receiveShadow geometry={nodes.door_rr.geometry} material={materials['door_rf.0']} />
        <mesh name='door_rr_1' castShadow receiveShadow geometry={nodes.door_rr_1.geometry} material={materials['wheel.0']} />
        <mesh name='door_rr_2' castShadow receiveShadow geometry={nodes.door_rr_2.geometry} material={materials['wheel.1']} />
        <mesh name='door_rr_3' castShadow receiveShadow geometry={nodes.door_rr_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name='door_rr_4' castShadow receiveShadow geometry={nodes.door_rr_4.geometry} material={materials['door_rf.4']} />
        <mesh name='door_rr_5' castShadow receiveShadow geometry={nodes.door_rr_5.geometry} material={materials.primary} />
        <mesh name='door_rr_6' castShadow receiveShadow geometry={nodes.door_rr_6.geometry} material={materials['door_rf.7']} />
        <mesh name='door_rr_7' castShadow receiveShadow geometry={nodes.door_rr_7.geometry} material={materials['door_rf.8']} />
        <mesh name='door_rr_8' castShadow receiveShadow geometry={nodes.door_rr_8.geometry} material={materials['door_rf.9']} />
      </group>
      <group name='door_rear_left_1' position={[-0.942, -0.153, 0.438]}>
        <mesh name='door_lr' castShadow receiveShadow geometry={nodes.door_lr.geometry} material={materials['door_rf.0']} />
        <mesh name='door_lr_1' castShadow receiveShadow geometry={nodes.door_lr_1.geometry} material={materials['wheel.0']} />
        <mesh name='door_lr_2' castShadow receiveShadow geometry={nodes.door_lr_2.geometry} material={materials['wheel.1']} />
        <mesh name='door_lr_3' castShadow receiveShadow geometry={nodes.door_lr_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name='door_lr_4' castShadow receiveShadow geometry={nodes.door_lr_4.geometry} material={materials['door_rf.4']} />
        <mesh name='door_lr_5' castShadow receiveShadow geometry={nodes.door_lr_5.geometry} material={materials.primary} />
        <mesh name='door_lr_6' castShadow receiveShadow geometry={nodes.door_lr_6.geometry} material={materials['door_rf.7']} />
        <mesh name='door_lr_7' castShadow receiveShadow geometry={nodes.door_lr_7.geometry} material={materials['door_rf.8']} />
        <mesh name='door_lr_8' castShadow receiveShadow geometry={nodes.door_lr_8.geometry} material={materials['door_rf.9']} />
      </group>
      <group name='door_front_left_1' position={[-0.923, 0.005, -0.788]}>
        <mesh name='door_lf' castShadow receiveShadow geometry={nodes.door_lf.geometry} material={materials['door_rf.0']} />
        <mesh name='door_lf_1' castShadow receiveShadow geometry={nodes.door_lf_1.geometry} material={materials['wheel.0']} />
        <mesh name='door_lf_2' castShadow receiveShadow geometry={nodes.door_lf_2.geometry} material={materials['wheel.1']} />
        <mesh name='door_lf_3' castShadow receiveShadow geometry={nodes.door_lf_3.geometry} material={materials['chassis_vlo.0']} />
        <mesh name='door_lf_4' castShadow receiveShadow geometry={nodes.door_lf_4.geometry} material={materials['door_rf.4']} />
        <mesh name='door_lf_5' castShadow receiveShadow geometry={nodes.door_lf_5.geometry} material={materials.primary} />
        <mesh name='door_lf_6' castShadow receiveShadow geometry={nodes.door_lf_6.geometry} material={materials['door_rf.6']} />
        <mesh name='door_lf_7' castShadow receiveShadow geometry={nodes.door_lf_7.geometry} material={materials['door_rf.7']} />
        <mesh name='door_lf_8' castShadow receiveShadow geometry={nodes.door_lf_8.geometry} material={materials['door_rf.8']} />
        <mesh name='door_lf_9' castShadow receiveShadow geometry={nodes.door_lf_9.geometry} material={materials['door_rf.9']} />
        <mesh name='door_lf_10' castShadow receiveShadow geometry={nodes.door_lf_10.geometry} material={materials['door_rf.10']} />
      </group>
      <mesh name='tail_glass_1' castShadow receiveShadow geometry={nodes.tail_glass_1.geometry} material={materials.glass_rear_lights} />
      <group name='speedometer_1' position={[0, 0, -0.002]}>
        <mesh name='speed' castShadow receiveShadow geometry={nodes.speed.geometry} material={materials['door_rf.0']} />
        <mesh name='speed_1' castShadow receiveShadow geometry={nodes.speed_1.geometry} material={materials['wheel.1']} />
        <mesh name='speed_2' castShadow receiveShadow geometry={nodes.speed_2.geometry} material={materials['speed.2']} />
        <mesh name='speed_3' castShadow receiveShadow geometry={nodes.speed_3.geometry} material={materials['speed.3']} />
      </group>
      <group name='misc_1' position={[0, 0, -0.002]}>
        <mesh name='main2' castShadow receiveShadow geometry={nodes.main2.geometry} material={materials['door_rf.4']} />
        <mesh name='main2_1' castShadow receiveShadow geometry={nodes.main2_1.geometry} material={materials.glass_rear_lights} />
      </group>
      <group name='engine_1' position={[0, -1, -0.002]}>
        <mesh name='engine_1_1' castShadow receiveShadow geometry={nodes.engine_1_1.geometry} material={materials['door_rf.0']} />
        <mesh name='engine_1_2' castShadow receiveShadow geometry={nodes.engine_1_2.geometry} material={materials['wheel.1']} />
        <mesh name='engine_1_3' castShadow receiveShadow geometry={nodes.engine_1_3.geometry} material={materials['door_rf.4']} />
        <mesh name='engine_1_4' castShadow receiveShadow geometry={nodes.engine_1_4.geometry} material={materials.primary} />
        <mesh name='engine_1_5' castShadow receiveShadow geometry={nodes.engine_1_5.geometry} material={materials['door_rf.6']} />
        <mesh name='engine_1_6' castShadow receiveShadow geometry={nodes.engine_1_6.geometry} material={materials['door_rf.7']} />
        <mesh name='engine_1_7' castShadow receiveShadow geometry={nodes.engine_1_7.geometry} material={materials['speed.2']} />
        <mesh name='engine_1_8' castShadow receiveShadow geometry={nodes.engine_1_8.geometry} material={materials['engine.9']} />
      </group>
      <mesh name='glass_head_lights_1' castShadow receiveShadow geometry={nodes.glass_head_lights_1.geometry} material={materials.glass_window} />
      <group name='bumper_front_1' position={[-0.896, -0.187, -1.766]}>
        <mesh name='bumper_f0' castShadow receiveShadow geometry={nodes.bumper_f0.geometry} material={materials['wheel.0']} />
        <mesh name='bumper_f0_1' castShadow receiveShadow geometry={nodes.bumper_f0_1.geometry} material={materials['wheel.1']} />
        <mesh name='bumper_f0_2' castShadow receiveShadow geometry={nodes.bumper_f0_2.geometry} material={materials['chassis_vlo.0']} />
        <mesh name='bumper_f0_3' castShadow receiveShadow geometry={nodes.bumper_f0_3.geometry} material={materials['door_rf.4']} />
        <mesh name='bumper_f0_4' castShadow receiveShadow geometry={nodes.bumper_f0_4.geometry} material={materials.primary} />
        <mesh name='bumper_f0_5' castShadow receiveShadow geometry={nodes.bumper_f0_5.geometry} material={materials['bumper_f0.5']} />
        <mesh name='bumper_f0_6' castShadow receiveShadow geometry={nodes.bumper_f0_6.geometry} material={materials['bumper_f0.10']} />
        <mesh name='bumper_f0_7' castShadow receiveShadow geometry={nodes.bumper_f0_7.geometry} material={materials['lights.3']} />
        <mesh name='bumper_f0_8' castShadow receiveShadow geometry={nodes.bumper_f0_8.geometry} material={materials['speed.2']} />
      </group>
      <group name='bumper_rear_1' position={[1.012, -0.202, 2.198]}>
        <mesh name='bumper_r0' castShadow receiveShadow geometry={nodes.bumper_r0.geometry} material={materials.primary} />
        <mesh name='bumper_r0_1' castShadow receiveShadow geometry={nodes.bumper_r0_1.geometry} material={materials['lights.4']} />
        <mesh name='bumper_r0_2' castShadow receiveShadow geometry={nodes.bumper_r0_2.geometry} material={materials['wheel.0']} />
        <mesh name='bumper_r0_3' castShadow receiveShadow geometry={nodes.bumper_r0_3.geometry} material={materials['chassis_vlo.0']} />
      </group>

      <group name='bonnet_1' position={[0, 0.25, -0.797]} visible={storeStyling.demonstrativeBodyparts.bonnet_id === 1}>
        <mesh name='bonnet_1_1' castShadow receiveShadow geometry={nodes.bonnet_1_1.geometry} material={materials['wheel.1']} />
        <mesh name='bonnet_1_2' castShadow receiveShadow geometry={nodes.bonnet_1_2.geometry} material={materials.primary} />
      </group>
      <group name='bonnet_2' position={[0, 1.25, -0.797]} visible={storeStyling.demonstrativeBodyparts.bonnet_id === 2}>
        <mesh name='bonnet_2_1' castShadow receiveShadow geometry={nodes.bonnet_1_1.geometry} material={materials['wheel.1']} />
        <mesh name='bonnet_2_2' castShadow receiveShadow geometry={nodes.bonnet_1_2.geometry} material={materials.primary} />
      </group>

      <group name='steeringwheel_1' position={[-0.408, 0.078, -0.361]} rotation={[-0.396, 0, 0]}>
        <mesh name='steeringwheel_ok' castShadow receiveShadow geometry={nodes.steeringwheel_ok.geometry} material={materials['chassis_vlo.0']} />
        <mesh name='steeringwheel_ok_1' castShadow receiveShadow geometry={nodes.steeringwheel_ok_1.geometry} material={materials.interior} />
        <mesh name='steeringwheel_ok_2' castShadow receiveShadow geometry={nodes.steeringwheel_ok_2.geometry} material={materials['door_rf.6']} />
        <mesh name='steeringwheel_ok_3' castShadow receiveShadow geometry={nodes.steeringwheel_ok_3.geometry} material={materials['door_rf.9']} />
        <mesh name='steeringwheel_ok_4' castShadow receiveShadow geometry={nodes.steeringwheel_ok_4.geometry} material={materials['steeringwheel_ok.4']} />
        <mesh name='steeringwheel_ok_5' castShadow receiveShadow geometry={nodes.steeringwheel_ok_5.geometry} material={materials['steeringwheel_ok.5']} />
        <mesh name='steeringwheel_ok_6' castShadow receiveShadow geometry={nodes.steeringwheel_ok_6.geometry} material={materials['bodyshell2.11']} />
      </group>
      <mesh name='glass_rear_1' castShadow receiveShadow geometry={nodes.glass_rear_1.geometry} material={materials.glass_window} position={[0, 0, 0.002]} />
      <mesh
        name='glass_front_1'
        castShadow
        receiveShadow
        geometry={nodes.glass_front_1.geometry}
        material={materials.glass_window}
        position={[0, 0.441, -0.619]}
      />
      <group name='trunk_1' position={[0, 0.698, 2.128]}>
        <mesh name='trunk0' castShadow receiveShadow geometry={nodes.trunk0.geometry} material={materials.glass_window} />
        <mesh name='trunk0_1' castShadow receiveShadow geometry={nodes.trunk0_1.geometry} material={materials['door_rf.0']} />
        <mesh name='trunk0_2' castShadow receiveShadow geometry={nodes.trunk0_2.geometry} material={materials['wheel.1']} />
        <mesh name='trunk0_3' castShadow receiveShadow geometry={nodes.trunk0_3.geometry} material={materials['door_rf.4']} />
        <mesh name='trunk0_4' castShadow receiveShadow geometry={nodes.trunk0_4.geometry} material={materials.primary} />
        <mesh name='trunk0_5' castShadow receiveShadow geometry={nodes.trunk0_5.geometry} material={materials['door_rf.6']} />
        <mesh name='trunk0_6' castShadow receiveShadow geometry={nodes.trunk0_6.geometry} material={materials['speed.2']} />
        <mesh name='trunk0_7' castShadow receiveShadow geometry={nodes.trunk0_7.geometry} material={materials['wheel.0']} />
        <mesh name='trunk0_8' castShadow receiveShadow geometry={nodes.trunk0_8.geometry} material={materials.glass_window} />
      </group>
      <group name='tail_trunk_lights_1' position={[0, 0.698, 2.128]}>
        <mesh name='bootlights' castShadow receiveShadow geometry={nodes.bootlights.geometry} material={materials['right front light']} />
        <mesh name='bootlights_1' castShadow receiveShadow geometry={nodes.bootlights_1.geometry} material={materials['chassis_vlo.2']} />
        <mesh name='bootlights_2' castShadow receiveShadow geometry={nodes.bootlights_2.geometry} material={materials['rearlights.1']} />
        <mesh name='bootlights_3' castShadow receiveShadow geometry={nodes.bootlights_3.geometry} material={materials['lights.1']} />
        <mesh name='bootlights_4' castShadow receiveShadow geometry={nodes.bootlights_4.geometry} material={materials['lights.5']} />
        <mesh name='bootlights_5' castShadow receiveShadow geometry={nodes.bootlights_5.geometry} material={materials['lights.5']} />
        <mesh name='bootlights_6' castShadow receiveShadow geometry={nodes.bootlights_6.geometry} material={materials['lights.5']} />
        <mesh name='bootlights_7' castShadow receiveShadow geometry={nodes.bootlights_7.geometry} material={materials['lights.5']} />
        <mesh name='bootlights_8' castShadow receiveShadow geometry={nodes.bootlights_8.geometry} material={materials['lights.5']} />
        <mesh name='bootlights_9' castShadow receiveShadow geometry={nodes.bootlights_9.geometry} material={materials['lights.5']} />
        <mesh name='bootlights_10' castShadow receiveShadow geometry={nodes.bootlights_10.geometry} material={materials['lights.5']} />
        <mesh name='bootlights_11' castShadow receiveShadow geometry={nodes.bootlights_11.geometry} material={materials['lights.5']} />
      </group>
      <mesh
        name='tail_trunk_lights_glass_1'
        castShadow
        receiveShadow
        geometry={nodes.tail_trunk_lights_glass_1.geometry}
        material={materials.glass_rear_lights}
        position={[0, 0.698, 2.128]}
      />
      <group name='wheel_front_left_1' position={[-0.967, -0.489, -1.435]}>
        <mesh name='wheel_front_left_1_1' castShadow receiveShadow geometry={nodes.wheel_front_left_1_1.geometry} material={materials['wheel.0']} />
        <mesh name='wheel_front_left_1_2' castShadow receiveShadow geometry={nodes.wheel_front_left_1_2.geometry} material={materials.mat_wheel_primary} />
        <mesh name='wheel_front_left_1_3' castShadow receiveShadow geometry={nodes.wheel_front_left_1_3.geometry} material={materials.mat_wheel_disk_brakes} />
        <mesh name='wheel_front_left_1_4' castShadow receiveShadow geometry={nodes.wheel_front_left_1_4.geometry} material={materials.mat_wheel_tire_side} />
        <mesh name='wheel_front_left_1_5' castShadow receiveShadow geometry={nodes.wheel_front_left_1_5.geometry} material={materials.mat_wheel_tire_ground} />
      </group>
      <group name='wheel_rear_left_1' position={[-0.967, -0.489, 1.821]}>
        <mesh name='wheel_front_left_1_1' castShadow receiveShadow geometry={nodes.wheel_front_left_1_1.geometry} material={materials['wheel.0']} />
        <mesh name='wheel_front_left_1_2' castShadow receiveShadow geometry={nodes.wheel_front_left_1_2.geometry} material={materials.mat_wheel_primary} />
        <mesh name='wheel_front_left_1_3' castShadow receiveShadow geometry={nodes.wheel_front_left_1_3.geometry} material={materials.mat_wheel_disk_brakes} />
        <mesh name='wheel_front_left_1_4' castShadow receiveShadow geometry={nodes.wheel_front_left_1_4.geometry} material={materials.mat_wheel_tire_side} />
        <mesh name='wheel_front_left_1_5' castShadow receiveShadow geometry={nodes.wheel_front_left_1_5.geometry} material={materials.mat_wheel_tire_ground} />
      </group>
      <mesh
        name='roof_diffuser_1'
        castShadow
        receiveShadow
        geometry={nodes.roof_diffuser_1.geometry}
        material={materials['door_rf.0']}
        position={[0, -1, -0.002]}
      />
      <mesh
        name='glass_front_frame'
        castShadow
        receiveShadow
        geometry={nodes.glass_front_frame.geometry}
        material={materials['wheel.0']}
        position={[0, -1, -0.002]}
      />
      <group name='wheel_front_right_1' position={[0.967, -0.489, -1.435]}>
        <mesh name='wheel_front_right_1_1' castShadow receiveShadow geometry={nodes.wheel_front_right_1_1.geometry} material={materials['wheel.0']} />
        <mesh name='wheel_front_right_1_2' castShadow receiveShadow geometry={nodes.wheel_front_right_1_2.geometry} material={materials.mat_wheel_primary} />
        <mesh
          name='wheel_front_right_1_3'
          castShadow
          receiveShadow
          geometry={nodes.wheel_front_right_1_3.geometry}
          material={materials.mat_wheel_disk_brakes}
        />
        <mesh name='wheel_front_right_1_4' castShadow receiveShadow geometry={nodes.wheel_front_right_1_4.geometry} material={materials.mat_wheel_tire_side} />
        <mesh
          name='wheel_front_right_1_5'
          castShadow
          receiveShadow
          geometry={nodes.wheel_front_right_1_5.geometry}
          material={materials.mat_wheel_tire_ground}
        />
      </group>
      <group name='wheel_rear_right_1' position={[0.967, -0.489, 1.821]}>
        <mesh name='wheel_front_right_1_1' castShadow receiveShadow geometry={nodes.wheel_front_right_1_1.geometry} material={materials['wheel.0']} />
        <mesh name='wheel_front_right_1_2' castShadow receiveShadow geometry={nodes.wheel_front_right_1_2.geometry} material={materials.mat_wheel_primary} />
        <mesh
          name='wheel_front_right_1_3'
          castShadow
          receiveShadow
          geometry={nodes.wheel_front_right_1_3.geometry}
          material={materials.mat_wheel_disk_brakes}
        />
        <mesh name='wheel_front_right_1_4' castShadow receiveShadow geometry={nodes.wheel_front_right_1_4.geometry} material={materials.mat_wheel_tire_side} />
        <mesh
          name='wheel_front_right_1_5'
          castShadow
          receiveShadow
          geometry={nodes.wheel_front_right_1_5.geometry}
          material={materials.mat_wheel_tire_ground}
        />
      </group>
      <mesh
        name='glass_door_front_right'
        castShadow
        receiveShadow
        geometry={nodes.glass_door_front_right.geometry}
        material={materials.glass_window}
        position={[0.914, 0.005, -0.79]}
      />
      <mesh
        name='glass_door_rear_right'
        castShadow
        receiveShadow
        geometry={nodes.glass_door_rear_right.geometry}
        material={materials.glass_window}
        position={[0.941, -0.153, 0.438]}
      />
      <mesh
        name='glass_door_rear_left'
        castShadow
        receiveShadow
        geometry={nodes.glass_door_rear_left.geometry}
        material={materials.glass_window}
        position={[-0.942, -0.153, 0.438]}
      />
      <mesh
        name='glass_door_front_left'
        castShadow
        receiveShadow
        geometry={nodes.glass_door_front_left.geometry}
        material={materials.glass_window}
        position={[-0.923, 0.005, -0.79]}
      />
      <mesh name='lights' castShadow receiveShadow geometry={nodes.lights.geometry} material={materials['right front light']} />
      <mesh name='lights_1' castShadow receiveShadow geometry={nodes.lights_1.geometry} material={materials['lights.1']} />
      <mesh name='lights_2' castShadow receiveShadow geometry={nodes.lights_2.geometry} material={materials['right front light.001']} />
      <mesh name='lights_3' castShadow receiveShadow geometry={nodes.lights_3.geometry} material={materials['lights.3']} />
      <mesh name='lights_4' castShadow receiveShadow geometry={nodes.lights_4.geometry} material={materials['lights.4']} />
      <mesh name='lights_5' castShadow receiveShadow geometry={nodes.lights_5.geometry} material={materials['lights.5']} />
      <mesh name='lights_6' castShadow receiveShadow geometry={nodes.lights_6.geometry} material={materials['lights.5']} />
      <mesh name='lights_7' castShadow receiveShadow geometry={nodes.lights_7.geometry} material={materials['lights.5']} />
      <mesh name='lights_8' castShadow receiveShadow geometry={nodes.lights_8.geometry} material={materials['lights.5']} />
      <mesh name='lights_9' castShadow receiveShadow geometry={nodes.lights_9.geometry} material={materials['lights.5']} />
      <mesh name='lights_10' castShadow receiveShadow geometry={nodes.lights_10.geometry} material={materials['lights.5']} />
      <mesh name='lights_11' castShadow receiveShadow geometry={nodes.lights_11.geometry} material={materials['lights.5']} />
      <mesh name='lights_12' castShadow receiveShadow geometry={nodes.lights_12.geometry} material={materials['lights.5']} />
      <mesh name='lights_13' castShadow receiveShadow geometry={nodes.lights_13.geometry} material={materials['lights.5']} />
      <mesh name='lights_14' castShadow receiveShadow geometry={nodes.lights_14.geometry} material={materials['lights.5']} />
      <mesh name='lights_15' castShadow receiveShadow geometry={nodes.lights_15.geometry} material={materials['lights.5']} />
      <mesh name='rearlights' castShadow receiveShadow geometry={nodes.rearlights.geometry} material={materials['right front light']} />
      <mesh name='rearlights_1' castShadow receiveShadow geometry={nodes.rearlights_1.geometry} material={materials['rearlights.1']} />
      <mesh name='rearlights_2' castShadow receiveShadow geometry={nodes.rearlights_2.geometry} material={materials['lights.1']} />
      <mesh name='rearlights_3' castShadow receiveShadow geometry={nodes.rearlights_3.geometry} material={materials['lights.5']} />
      <mesh name='rearlights_4' castShadow receiveShadow geometry={nodes.rearlights_4.geometry} material={materials['lights.5']} />
      <mesh name='rearlights_5' castShadow receiveShadow geometry={nodes.rearlights_5.geometry} material={materials['lights.5']} />
      <mesh name='rearlights_6' castShadow receiveShadow geometry={nodes.rearlights_6.geometry} material={materials['lights.5']} />
      <mesh name='rearlights_7' castShadow receiveShadow geometry={nodes.rearlights_7.geometry} material={materials['lights.5']} />
      <mesh name='rearlights_8' castShadow receiveShadow geometry={nodes.rearlights_8.geometry} material={materials['lights.5']} />
      <mesh name='body_shell_1' castShadow receiveShadow geometry={nodes.body_shell_1.geometry} material={materials['wheel.0']} />
      <mesh name='body_shell_2' castShadow receiveShadow geometry={nodes.body_shell_2.geometry} material={materials['chassis_vlo.0']} />
      <mesh name='body_shell_3' castShadow receiveShadow geometry={nodes.body_shell_3.geometry} material={materials['bodyshell2.2']} />
      <mesh name='body_shell_4' castShadow receiveShadow geometry={nodes.body_shell_4.geometry} material={materials['door_rf.4']} />
      <mesh name='body_shell_5' castShadow receiveShadow geometry={nodes.body_shell_5.geometry} material={materials.primary} />
      <mesh name='body_shell_6' castShadow receiveShadow geometry={nodes.body_shell_6.geometry} material={materials['door_rf.6']} />
      <mesh name='body_shell_7' castShadow receiveShadow geometry={nodes.body_shell_7.geometry} material={materials['door_rf.7']} />
      <mesh name='body_shell_8' castShadow receiveShadow geometry={nodes.body_shell_8.geometry} material={materials['door_rf.8']} />
      <mesh name='body_shell_9' castShadow receiveShadow geometry={nodes.body_shell_9.geometry} material={materials['door_rf.9']} />
      <mesh name='body_shell_10' castShadow receiveShadow geometry={nodes.body_shell_10.geometry} material={materials['speed.2']} />
      <mesh name='body_shell_11' castShadow receiveShadow geometry={nodes.body_shell_11.geometry} material={materials['seats.1']} />
      <mesh name='body_shell_12' castShadow receiveShadow geometry={nodes.body_shell_12.geometry} material={materials['bodyshell2.11']} />
      <mesh name='body_shell_13' castShadow receiveShadow geometry={nodes.body_shell_13.geometry} material={materials['bodyshell2.12']} />
      <mesh name='body_shell_14' castShadow receiveShadow geometry={nodes.body_shell_14.geometry} material={materials['bodyshell2.13']} />
      <mesh name='body_shell_15' castShadow receiveShadow geometry={nodes.body_shell_15.geometry} material={materials['door_rf.0']} />
      <mesh name='body_shell_16' castShadow receiveShadow geometry={nodes.body_shell_16.geometry} material={materials['wheel.1']} />
    </group>
  )
}

useGLTF.preload('assets/3d/transformed_gltf/cars/audi/RS6/audi_rs6-transformed.glb')

export default observer(Model)
