/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 ./audi_rs7.gltf --types --transform --shadows --keepnames --keepmeshes --keepmaterials 
Files: ./audi_rs7.gltf [134.82KB] > audi_rs7-transformed.glb [1.83MB] (-1258%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { degToRad } from 'three/src/math/MathUtils'
import { Euler, Vector3 } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    body_shell_1: THREE.Mesh
    body_shell_2: THREE.Mesh
    body_shell_3: THREE.Mesh
    body_interior_1: THREE.Mesh
    body_interior_2: THREE.Mesh
    body_interior_3: THREE.Mesh
    body_interior_4: THREE.Mesh
    dashboard_1: THREE.Mesh
    dashboard_2: THREE.Mesh
    dashboard_3: THREE.Mesh
    dashboard_4: THREE.Mesh
    dashboard_5: THREE.Mesh
    seats_1: THREE.Mesh
    seats_2: THREE.Mesh
    seats_3: THREE.Mesh
    lights_front_1: THREE.Mesh
    lights_front_2: THREE.Mesh
    lights_front_3: THREE.Mesh
    lights_front_4: THREE.Mesh
    lights_front_5: THREE.Mesh
    lights_glass_front: THREE.Mesh
    steeringwheel_1: THREE.Mesh
    steeringwheel_2: THREE.Mesh
    steeringwheel_3: THREE.Mesh
    steeringwheel_4: THREE.Mesh
    misc: THREE.Mesh
    bumper_front_1: THREE.Mesh
    bumper_front_2: THREE.Mesh
    bumper_front_3: THREE.Mesh
    bumper_front_4: THREE.Mesh
    bumper_front_5: THREE.Mesh
    bumper_rear_1: THREE.Mesh
    bumper_rear_2: THREE.Mesh
    bumper_rear_3: THREE.Mesh
    bumper_rear_4: THREE.Mesh
    door_front_right_1: THREE.Mesh
    door_front_right_2: THREE.Mesh
    door_front_right_3: THREE.Mesh
    door_front_right_4: THREE.Mesh
    door_front_right_5: THREE.Mesh
    door_front_right_6: THREE.Mesh
    door_front_right_7: THREE.Mesh
    door_front_right_8: THREE.Mesh
    door_front_left_1: THREE.Mesh
    door_front_left_2: THREE.Mesh
    door_front_left_3: THREE.Mesh
    door_front_left_4: THREE.Mesh
    door_front_left_5: THREE.Mesh
    door_front_left_6: THREE.Mesh
    door_front_left_7: THREE.Mesh
    door_rear_right_1: THREE.Mesh
    door_rear_right_2: THREE.Mesh
    door_rear_right_3: THREE.Mesh
    door_rear_right_4: THREE.Mesh
    door_rear_right_5: THREE.Mesh
    door_rear_right_6: THREE.Mesh
    door_rear_right_7: THREE.Mesh
    door_rear_left_1: THREE.Mesh
    door_rear_left_2: THREE.Mesh
    door_rear_left_3: THREE.Mesh
    door_rear_left_4: THREE.Mesh
    door_rear_left_5: THREE.Mesh
    door_rear_left_6: THREE.Mesh
    door_rear_left_7: THREE.Mesh
    glass_rear: THREE.Mesh
    glass_front: THREE.Mesh
    door_glass_rear_right: THREE.Mesh
    door_glass_front_right: THREE.Mesh
    door_glass_front_left: THREE.Mesh
    door_glass_rear_left: THREE.Mesh
    glass_rear_alternative: THREE.Mesh
    lights_glass_rear: THREE.Mesh
    lights_rear_1: THREE.Mesh
    lights_rear_2: THREE.Mesh
    lights_rear_3: THREE.Mesh
    lights_rear_4: THREE.Mesh
    lights_rear_5: THREE.Mesh
    glass_front_frame: THREE.Mesh
    glass_rear_alternative_frames: THREE.Mesh

    wheel_front_left_1: THREE.Mesh
    wheel_front_left_2: THREE.Mesh
    wheel_front_left_3: THREE.Mesh
    wheel_front_left_4: THREE.Mesh
    wheel_rear_left_1: THREE.Mesh
    wheel_rear_left_2: THREE.Mesh
    wheel_rear_left_3: THREE.Mesh
    wheel_rear_left_4: THREE.Mesh
    wheel_front_right_1: THREE.Mesh
    wheel_front_right_2: THREE.Mesh
    wheel_front_right_3: THREE.Mesh
    wheel_front_right_4: THREE.Mesh
    wheel_rear_right_1: THREE.Mesh
    wheel_rear_right_2: THREE.Mesh
    wheel_rear_right_3: THREE.Mesh
    wheel_rear_right_4: THREE.Mesh
  }
  materials: {
    wheel_disk_primary: THREE.MeshStandardMaterial
    img_wheel_brakes: THREE.MeshStandardMaterial
    img_wheel_tire: THREE.MeshStandardMaterial
    wheel_cap: THREE.MeshStandardMaterial
    secondary: THREE.MeshStandardMaterial
    primary: THREE.MeshPhysicalMaterial
    img_interior_dfs: THREE.MeshStandardMaterial
    img_carpet_black: THREE.MeshStandardMaterial
    img_interior_dashboard: THREE.MeshStandardMaterial
    img_dark_fabric: THREE.MeshStandardMaterial
    img_carbon: THREE.MeshStandardMaterial
    img_white_fabric: THREE.MeshStandardMaterial
    head_lights_1: THREE.MeshStandardMaterial
    img_head_lights_2: THREE.MeshStandardMaterial
    head_lights_3: THREE.MeshStandardMaterial
    img_head_lights_4: THREE.MeshStandardMaterial
    turn_light: THREE.MeshStandardMaterial
    glass: THREE.MeshStandardMaterial
    brand: THREE.MeshStandardMaterial
    img_grille: THREE.MeshStandardMaterial
    img_brand_nameplates: THREE.MeshStandardMaterial
    img_rear_lights_3: THREE.MeshStandardMaterial
    img_dark_fabric_2: THREE.MeshStandardMaterial
    glass_rear_lights: THREE.MeshStandardMaterial
    rear_lights_1: THREE.MeshStandardMaterial
    img_rear_lights_2: THREE.MeshStandardMaterial
    rear_lights_4: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('assets/3d/transformed_gltf/cars/audi/RS7/audi_rs7-transformed.glb') as GLTFResult

  const [defaultCarProps] = React.useState({
    position: [0, 1.025, 0] as Vector3,
    rotation: [degToRad(0), degToRad(-135), degToRad(0)] as Euler,
    scale: 1,
  })

  return (
    <group {...props} dispose={null} position={defaultCarProps.position} rotation={defaultCarProps.rotation} scale={defaultCarProps.scale}>
      <group name='wheel_front_right' position={[0.997, -0.408, -1.559]}>
        <mesh name='wheel_front_right_1' castShadow receiveShadow geometry={nodes.wheel_front_right_1.geometry} material={materials.wheel_disk_primary} />
        <mesh name='wheel_front_right_2' castShadow receiveShadow geometry={nodes.wheel_front_right_2.geometry} material={materials.img_wheel_brakes} />
        <mesh name='wheel_front_right_3' castShadow receiveShadow geometry={nodes.wheel_front_right_3.geometry} material={materials.img_wheel_tire} />
        <mesh name='wheel_front_right_4' castShadow receiveShadow geometry={nodes.wheel_front_right_4.geometry} material={materials.wheel_cap} />
      </group>
      <group name='wheel_rear_right' position={[0.997, -0.408, 1.652]}>
        <mesh name='wheel_front_right_1' castShadow receiveShadow geometry={nodes.wheel_front_right_1.geometry} material={materials.wheel_disk_primary} />
        <mesh name='wheel_front_right_2' castShadow receiveShadow geometry={nodes.wheel_front_right_2.geometry} material={materials.img_wheel_brakes} />
        <mesh name='wheel_front_right_3' castShadow receiveShadow geometry={nodes.wheel_front_right_3.geometry} material={materials.img_wheel_tire} />
        <mesh name='wheel_front_right_4' castShadow receiveShadow geometry={nodes.wheel_front_right_4.geometry} material={materials.wheel_cap} />
      </group>
      <mesh name='lights_glass_front' castShadow receiveShadow geometry={nodes.lights_glass_front.geometry} material={materials.glass} />
      <group name='steeringwheel' position={[-0.413, 0.192, -0.457]} rotation={[-0.397, 0, 0]}>
        <mesh name='steeringwheel_1' castShadow receiveShadow geometry={nodes.steeringwheel_1.geometry} material={materials.secondary} />
        <mesh name='steeringwheel_2' castShadow receiveShadow geometry={nodes.steeringwheel_2.geometry} material={materials.img_interior_dfs} />
        <mesh name='steeringwheel_3' castShadow receiveShadow geometry={nodes.steeringwheel_3.geometry} material={materials.img_white_fabric} />
        <mesh name='steeringwheel_4' castShadow receiveShadow geometry={nodes.steeringwheel_4.geometry} material={materials.img_dark_fabric} />
      </group>
      <mesh
        name='misc'
        castShadow
        receiveShadow
        geometry={nodes.misc.geometry}
        material={materials.primary}
        position={[0, 0.304, 2.644]}
        rotation={[0.001, 0, 0]}
      />
      <group name='door_front_right' position={[1.005, -0.02, -0.93]}>
        <mesh name='door_front_right_1' castShadow receiveShadow geometry={nodes.door_front_right_1.geometry} material={materials.secondary} />
        <mesh name='door_front_right_2' castShadow receiveShadow geometry={nodes.door_front_right_2.geometry} material={materials.img_interior_dfs} />
        <mesh name='door_front_right_3' castShadow receiveShadow geometry={nodes.door_front_right_3.geometry} material={materials.secondary} />
        <mesh name='door_front_right_4' castShadow receiveShadow geometry={nodes.door_front_right_4.geometry} material={materials.img_dark_fabric_2} />
        <mesh name='door_front_right_5' castShadow receiveShadow geometry={nodes.door_front_right_5.geometry} material={materials.img_dark_fabric} />
        <mesh name='door_front_right_6' castShadow receiveShadow geometry={nodes.door_front_right_6.geometry} material={materials.img_carbon} />
        <mesh name='door_front_right_7' castShadow receiveShadow geometry={nodes.door_front_right_7.geometry} material={materials.turn_light} />
        <mesh name='door_front_right_8' castShadow receiveShadow geometry={nodes.door_front_right_8.geometry} material={materials.primary} />
      </group>
      <group name='door_front_left' position={[-1.005, -0.02, -0.93]}>
        <mesh name='door_front_left_1' castShadow receiveShadow geometry={nodes.door_front_left_1.geometry} material={materials.secondary} />
        <mesh name='door_front_left_2' castShadow receiveShadow geometry={nodes.door_front_left_2.geometry} material={materials.img_interior_dfs} />
        <mesh name='door_front_left_3' castShadow receiveShadow geometry={nodes.door_front_left_3.geometry} material={materials.secondary} />
        <mesh name='door_front_left_4' castShadow receiveShadow geometry={nodes.door_front_left_4.geometry} material={materials.img_dark_fabric_2} />
        <mesh name='door_front_left_5' castShadow receiveShadow geometry={nodes.door_front_left_5.geometry} material={materials.img_dark_fabric} />
        <mesh name='door_front_left_6' castShadow receiveShadow geometry={nodes.door_front_left_6.geometry} material={materials.img_carbon} />
        <mesh name='door_front_left_7' castShadow receiveShadow geometry={nodes.door_front_left_7.geometry} material={materials.primary} />
      </group>
      <group name='door_rear_right' position={[1.005, -0.02, 0.267]}>
        <mesh name='door_rear_right_1' castShadow receiveShadow geometry={nodes.door_rear_right_1.geometry} material={materials.secondary} />
        <mesh name='door_rear_right_2' castShadow receiveShadow geometry={nodes.door_rear_right_2.geometry} material={materials.img_interior_dfs} />
        <mesh name='door_rear_right_3' castShadow receiveShadow geometry={nodes.door_rear_right_3.geometry} material={materials.img_white_fabric} />
        <mesh name='door_rear_right_4' castShadow receiveShadow geometry={nodes.door_rear_right_4.geometry} material={materials.img_dark_fabric_2} />
        <mesh name='door_rear_right_5' castShadow receiveShadow geometry={nodes.door_rear_right_5.geometry} material={materials.img_dark_fabric} />
        <mesh name='door_rear_right_6' castShadow receiveShadow geometry={nodes.door_rear_right_6.geometry} material={materials.img_carbon} />
        <mesh name='door_rear_right_7' castShadow receiveShadow geometry={nodes.door_rear_right_7.geometry} material={materials.primary} />
      </group>
      <group name='door_rear_left' position={[-1.005, -0.02, 0.267]}>
        <mesh name='door_rear_left_1' castShadow receiveShadow geometry={nodes.door_rear_left_1.geometry} material={materials.secondary} />
        <mesh name='door_rear_left_2' castShadow receiveShadow geometry={nodes.door_rear_left_2.geometry} material={materials.img_interior_dfs} />
        <mesh name='door_rear_left_3' castShadow receiveShadow geometry={nodes.door_rear_left_3.geometry} material={materials.img_white_fabric} />
        <mesh name='door_rear_left_4' castShadow receiveShadow geometry={nodes.door_rear_left_4.geometry} material={materials.img_dark_fabric_2} />
        <mesh name='door_rear_left_5' castShadow receiveShadow geometry={nodes.door_rear_left_5.geometry} material={materials.img_dark_fabric} />
        <mesh name='door_rear_left_6' castShadow receiveShadow geometry={nodes.door_rear_left_6.geometry} material={materials.img_carbon} />
        <mesh name='door_rear_left_7' castShadow receiveShadow geometry={nodes.door_rear_left_7.geometry} material={materials.primary} />
      </group>
      <mesh name='glass_rear' castShadow receiveShadow geometry={nodes.glass_rear.geometry} material={materials.glass} position={[0, 0.002, 0]} />
      <mesh name='glass_front' castShadow receiveShadow geometry={nodes.glass_front.geometry} material={materials.glass} />
      <mesh
        name='door_glass_rear_right'
        castShadow
        receiveShadow
        geometry={nodes.door_glass_rear_right.geometry}
        material={materials.glass}
        position={[1.005, -0.02, 0.267]}
      />
      <mesh
        name='door_glass_front_right'
        castShadow
        receiveShadow
        geometry={nodes.door_glass_front_right.geometry}
        material={materials.glass}
        position={[1.005, -0.02, -0.93]}
      />
      <mesh
        name='door_glass_front_left'
        castShadow
        receiveShadow
        geometry={nodes.door_glass_front_left.geometry}
        material={materials.glass}
        position={[-1.005, -0.02, -0.93]}
      />
      <mesh
        name='door_glass_rear_left'
        castShadow
        receiveShadow
        geometry={nodes.door_glass_rear_left.geometry}
        material={materials.glass}
        position={[-1.005, -0.02, 0.267]}
      />
      <mesh name='glass_rear_alternative' castShadow receiveShadow geometry={nodes.glass_rear_alternative.geometry} material={materials.glass} />
      <mesh name='lights_glass_rear' castShadow receiveShadow geometry={nodes.lights_glass_rear.geometry} material={materials.glass_rear_lights} />
      <mesh name='glass_front_frame' castShadow receiveShadow geometry={nodes.glass_front_frame.geometry} material={materials.wheel_cap} />
      <mesh
        name='glass_rear_alternative_frames'
        castShadow
        receiveShadow
        geometry={nodes.glass_rear_alternative_frames.geometry}
        material={materials.wheel_cap}
      />
      <group name='wheel_front_left' position={[-0.997, -0.408, -1.559]}>
        <mesh name='wheel_front_left_1' castShadow receiveShadow geometry={nodes.wheel_front_left_1.geometry} material={materials.wheel_disk_primary} />
        <mesh name='wheel_front_left_2' castShadow receiveShadow geometry={nodes.wheel_front_left_2.geometry} material={materials.img_wheel_brakes} />
        <mesh name='wheel_front_left_3' castShadow receiveShadow geometry={nodes.wheel_front_left_3.geometry} material={materials.img_wheel_tire} />
        <mesh name='wheel_front_left_4' castShadow receiveShadow geometry={nodes.wheel_front_left_4.geometry} material={materials.wheel_cap} />
      </group>
      <group name='wheel_rear_left' position={[-0.997, -0.408, 1.652]}>
        <mesh name='wheel_front_left_1' castShadow receiveShadow geometry={nodes.wheel_front_left_1.geometry} material={materials.wheel_disk_primary} />
        <mesh name='wheel_front_left_2' castShadow receiveShadow geometry={nodes.wheel_front_left_2.geometry} material={materials.img_wheel_brakes} />
        <mesh name='wheel_front_left_3' castShadow receiveShadow geometry={nodes.wheel_front_left_3.geometry} material={materials.img_wheel_tire} />
        <mesh name='wheel_front_left_4' castShadow receiveShadow geometry={nodes.wheel_front_left_4.geometry} material={materials.wheel_cap} />
      </group>
      <mesh name='body_shell_1' castShadow receiveShadow geometry={nodes.body_shell_1.geometry} material={materials.secondary} />
      <mesh name='body_shell_2' castShadow receiveShadow geometry={nodes.body_shell_2.geometry} material={materials.primary} />
      <mesh name='body_shell_3' castShadow receiveShadow geometry={nodes.body_shell_3.geometry} material={materials.wheel_cap} />
      <mesh name='body_interior_1' castShadow receiveShadow geometry={nodes.body_interior_1.geometry} material={materials.secondary} />
      <mesh name='body_interior_2' castShadow receiveShadow geometry={nodes.body_interior_2.geometry} material={materials.wheel_cap} />
      <mesh name='body_interior_3' castShadow receiveShadow geometry={nodes.body_interior_3.geometry} material={materials.img_interior_dfs} />
      <mesh name='body_interior_4' castShadow receiveShadow geometry={nodes.body_interior_4.geometry} material={materials.img_carpet_black} />
      <mesh name='dashboard_1' castShadow receiveShadow geometry={nodes.dashboard_1.geometry} material={materials.secondary} />
      <mesh name='dashboard_2' castShadow receiveShadow geometry={nodes.dashboard_2.geometry} material={materials.img_interior_dfs} />
      <mesh name='dashboard_3' castShadow receiveShadow geometry={nodes.dashboard_3.geometry} material={materials.img_interior_dashboard} />
      <mesh name='dashboard_4' castShadow receiveShadow geometry={nodes.dashboard_4.geometry} material={materials.img_dark_fabric} />
      <mesh name='dashboard_5' castShadow receiveShadow geometry={nodes.dashboard_5.geometry} material={materials.img_carbon} />
      <mesh name='seats_1' castShadow receiveShadow geometry={nodes.seats_1.geometry} material={materials.secondary} />
      <mesh name='seats_2' castShadow receiveShadow geometry={nodes.seats_2.geometry} material={materials.img_dark_fabric} />
      <mesh name='seats_3' castShadow receiveShadow geometry={nodes.seats_3.geometry} material={materials.img_white_fabric} />
      <mesh name='lights_front_1' castShadow receiveShadow geometry={nodes.lights_front_1.geometry} material={materials.head_lights_1} />
      <mesh name='lights_front_2' castShadow receiveShadow geometry={nodes.lights_front_2.geometry} material={materials.img_head_lights_2} />
      <mesh name='lights_front_3' castShadow receiveShadow geometry={nodes.lights_front_3.geometry} material={materials.head_lights_3} />
      <mesh name='lights_front_4' castShadow receiveShadow geometry={nodes.lights_front_4.geometry} material={materials.img_head_lights_4} />
      <mesh name='lights_front_5' castShadow receiveShadow geometry={nodes.lights_front_5.geometry} material={materials.turn_light} />
      <mesh name='bumper_front_1' castShadow receiveShadow geometry={nodes.bumper_front_1.geometry} material={materials.brand} />
      <mesh name='bumper_front_2' castShadow receiveShadow geometry={nodes.bumper_front_2.geometry} material={materials.secondary} />
      <mesh name='bumper_front_3' castShadow receiveShadow geometry={nodes.bumper_front_3.geometry} material={materials.primary} />
      <mesh name='bumper_front_4' castShadow receiveShadow geometry={nodes.bumper_front_4.geometry} material={materials.img_grille} />
      <mesh name='bumper_front_5' castShadow receiveShadow geometry={nodes.bumper_front_5.geometry} material={materials.img_brand_nameplates} />
      <mesh name='bumper_rear_1' castShadow receiveShadow geometry={nodes.bumper_rear_1.geometry} material={materials.secondary} />
      <mesh name='bumper_rear_2' castShadow receiveShadow geometry={nodes.bumper_rear_2.geometry} material={materials.primary} />
      <mesh name='bumper_rear_3' castShadow receiveShadow geometry={nodes.bumper_rear_3.geometry} material={materials.img_rear_lights_3} />
      <mesh name='bumper_rear_4' castShadow receiveShadow geometry={nodes.bumper_rear_4.geometry} material={materials.img_grille} />
      <mesh name='lights_rear_1' castShadow receiveShadow geometry={nodes.lights_rear_1.geometry} material={materials.rear_lights_1} />
      <mesh name='lights_rear_2' castShadow receiveShadow geometry={nodes.lights_rear_2.geometry} material={materials.img_rear_lights_2} />
      <mesh name='lights_rear_3' castShadow receiveShadow geometry={nodes.lights_rear_3.geometry} material={materials.img_rear_lights_3} />
      <mesh name='lights_rear_4' castShadow receiveShadow geometry={nodes.lights_rear_4.geometry} material={materials.rear_lights_4} />
      <mesh name='lights_rear_5' castShadow receiveShadow geometry={nodes.lights_rear_5.geometry} material={materials.turn_light} />
    </group>
  )
}

useGLTF.preload('assets/3d/transformed_gltf/cars/audi/RS7/audi_rs7-transformed.glb')
