// models
import IShopPaintColor from "@models/IShopPaintColor"

const shop_colors: IShopPaintColor[] = [
    { id: 1, type: 'paint_color', hex: '#FBCEB1', present_name: 'Абрикосовый', price: 1000, },
    { id: 2, type: 'paint_color', hex: '#B5B8B1', present_name: 'Агатовый серый', price: 1000, },
    { id: 3, type: 'paint_color', hex: '#7FFFD4', present_name: 'Аквамариновый', price: 1000, },
    { id: 4, type: 'paint_color', hex: '#E32636', present_name: 'Ализариновый красный', price: 1000, },
    { id: 5, type: 'paint_color', hex: '#AB274F', present_name: 'Амарантово-пурпурный', price: 1000, },
    { id: 6, type: 'paint_color', hex: '#9966CC', present_name: 'Аметистовый', price: 1000, },
    { id: 7, type: 'paint_color', hex: '#CD9575', present_name: 'Античная латунь', price: 1000, },
    { id: 8, type: 'paint_color', hex: '#464451', present_name: 'Антрацитовый', price: 1000, },
    { id: 9, type: 'paint_color', hex: '#44944A', present_name: 'Арлекин', price: 1000, },
    { id: 10, type: 'paint_color', hex: '#6A5ACD', present_name: 'Аспидно-синий', price: 1000, },
    { id: 11, type: 'paint_color', hex: '#003153', present_name: 'Берлинская лазурь', price: 1000, },
    { id: 12, type: 'paint_color', hex: '#A5260A', present_name: 'Бисмарк-фуриозо', price: 1000, },
    { id: 13, type: 'paint_color', hex: '#6495ED', present_name: 'Васильковый', price: 1000, },
    { id: 14, type: 'paint_color', hex: '#FFCF48', present_name: 'Восход солнца', price: 1000, },
    { id: 15, type: 'paint_color', hex: '#DCDCDC', present_name: 'Гейнсборо', price: 1000, },
    { id: 16, type: 'paint_color', hex: '#30BA8F', present_name: 'Горный луг', price: 1000, },
    { id: 17, type: 'paint_color', hex: '#F34723', present_name: 'Гранатовый', price: 1000, },
    { id: 18, type: 'paint_color', hex: '#1C1C1C', present_name: 'Графитно-черный', price: 1000, },
    { id: 19, type: 'paint_color', hex: '#474A51', present_name: 'Графитовый серый', price: 1000, },
    { id: 20, type: 'paint_color', hex: '#2F353B', present_name: 'Гранитный', price: 1000, },
    { id: 21, type: 'paint_color', hex: '#D1E231', present_name: 'Грушево-зеленый', price: 1000, },
    { id: 22, type: 'paint_color', hex: '#00693E', present_name: 'Дартмутский зеленый', price: 1000, },
    { id: 23, type: 'paint_color', hex: '#CA3767', present_name: 'Джазовый джем', price: 1000, },
    { id: 24, type: 'paint_color', hex: '#1560BD', present_name: 'Джинсовый синий', price: 1000, },
    { id: 25, type: 'paint_color', hex: '#009B77', present_name: 'Изумруд', price: 1000, },
    { id: 26, type: 'paint_color', hex: '#4B0082', present_name: 'Индиго', price: 1000, },
    { id: 27, type: 'paint_color', hex: '#4C5866', present_name: 'Маренго', price: 1000, },
    { id: 28, type: 'paint_color', hex: '#AD655F', present_name: 'Марсала', price: 1000, },
    { id: 29, type: 'paint_color', hex: '#B87333', present_name: 'Медный', price: 1000, },
    { id: 30, type: 'paint_color', hex: '#808000', present_name: 'Оливковый', price: 1000, },
    { id: 31, type: 'paint_color', hex: '#121910', present_name: 'Оливково-черный', price: 1000, },
    { id: 32, type: 'paint_color', hex: '#015D52', present_name: 'Опаловый зеленый', price: 1000, },
    { id: 33, type: 'paint_color', hex: '#FD5E53', present_name: 'Оранжевая заря', price: 1000, },
    { id: 34, type: 'paint_color', hex: '#A65E2E', present_name: 'Оранжево-коричневый', price: 1000, },
]

export default shop_colors